### ISSUE TITLE
Out-of-stock Default Variant: show next in-stock variant

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1000]
If the default variant is out of stock, show the next variant in line that is *in stock*.

This seems to exactly revert #899  - So make sure we're not just reverting to some behavior we don't want.

CC @ifixitmaxb @jeffsnyder

**Comment by jeffsnyder** [comment]
> seems to exactly revert

I thought we had problems with order by when both/all products were in stock. I don't believe this is as simple as changing back to the old code.

**Comment by danielbeardsley** [comment]
[Slack discussion](https://ifixit.slack.com/archives/C0252FETV2S/p1667853604276979)

Let's make sure we're sending the data correctly (so that it makes it all the way through to the graphql query):

https://github.com/iFixit/ifixit/blob/master/iFixit/Service/ShopifyWebhook/ProductBodyFactory.php#L205

I'd say play with this in dev and ensure that changing orderbys in akeneo results in different order of variants in the graphql query results that we get back from shopify.
