### ISSUE TITLE
Collections: Clicking a device item type facet should clear all other facets

### ISSUE THREAD

**Issue by masonmcelvain** [iFixit/react-commerce#1005]
## Problem

When on a device page (like https://www.ifixit.com/Parts/iPhone_6s?p=2), and you click an item type (like Case Components), the item type is applied but the other facets remain, and consequently sometimes there are no results.

## Expected behavior

Clicking an item type facet on a device page should clear all other facets.

**Comment by masonmcelvain** [comment]
Related to https://github.com/iFixit/react-commerce/issues/697

**Comment by sterlinghirsh** [comment]
I don't think this is right. Sounds like a problem with the ?p=2, but changing item type facet shouldn't clear other non-item-type facets.
