### ISSUE TITLE
Bug: No safe-guard against long search query

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#101]
# Description:

While QAing https://github.com/iFixit/react-commerce/pull/97 I realized that I did not test a long entry for the search field in https://github.com/iFixit/react-commerce/pull/94. This is an issue since the search query is added to the url as a parameter, therefore, if the search query is long it seems to cause an internal server error.

https://user-images.githubusercontent.com/22064420/136464932-07170a7b-e324-469c-921a-0a4a4a855a35.mp4

# Reproduction Steps:
1. Go the product search field
2. Enter an absurd amount of text
3. Reload the page
4. Notice there `500` error that is displayed

# Expected Behavior

I am not sure what should be the expected behavior on this (i.e. limit the amount of characters we can search, not have the search text added to the url, etc.) however, I do expect that we should safe-guard or prevent this from occurring.

**Comment by dhmacs** [comment]
> Not yet since I don't think we have production next.js running yet. We can certainly make sure the url is <512 bytes when constructing the url on the client side, though.

Yes, but we can prevent malformed url request from happening. I can certainly limit search input size though 👍
