### ISSUE TITLE
Collections: Facets "show more" option appearing when there are no more to show

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1012]
https://www.ifixit.com/Parts/Teenage_Engineering_OP-Z

https://user-images.githubusercontent.com/72166715/200901851-7e2c32c5-fb60-4eeb-b859-8eb65c755c9d.mp4

cc: @kwiens

**Comment by dhmacs** [comment]
I know why this happens, I've fixed it while working on another issue. I think I'll be able to open the PR later or tomorrow
