### ISSUE TITLE
Shopify GraphQL: Report exception if `response.errors`

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1014]
We recently dealt with a situation where the graphql response didn't contain `userErrors` but a higher-level `.errors` array and our client just ignores that and passes `null` to the requestor.  See pull #1011 We were missing out on this graphql error and are liking missing other errors (or breaking the page instead of handling the error).

### Do This
* Gracefully handle a null response to all shopify graphql queries
* Alter graphql client to check for and report errors to sentry
   * Consider throwing an exception? Though a nullable response ought to be easier to enforce the checking of
   * There may be some false positives, but we'll deal with those as they come

CC @sterlinghirsh

**Comment by sterlinghirsh** [comment]
Note: We don't check for this in ifixit/ifixit either.
