### ISSUE TITLE
Try increasing Algolia timeouts to avoid unreachable hosts errors

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1016]
Docs: https://www.algolia.com/doc/api-reference/api-methods/configuring-timeouts/?client=javascript
Slack ref: https://ifixit.slack.com/archives/C6QL70G9Z/p1667227831078949

Algolia's suggestion is to increase out timeouts. The default connectTimeout in js is 2 seconds. Let's try 5 and see if that fixes it. I'm also curious if we're auto-retrying if it does timeout after 2 seconds, which would mean that we wouldn't want to go too long with the timeout, but 5 seconds is probably fine.

After deploying, check sentry and see if the frequency of these errors has decreased.

**Comment by danielbeardsley** [comment]
We tried this. It didn't seem to help. We're ignoring these errors instead.
