### ISSUE TITLE
CORS error on subdomain, not on www

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1022]
My subdomain is on the latest master, and I can't view or add to my cart.

https://www.cominor.com/Parts
![image](https://user-images.githubusercontent.com/72166715/201398369-478bc2ea-7e41-41e1-b4f1-9dedc752f48c.png)

https://me.cominor.com/Parts
![image](https://user-images.githubusercontent.com/72166715/201398269-89e2a5a5-f205-4f04-9f99-3a4fda16e16c.png)

**Comment by masonmcelvain** [comment]
This didn't get fixed

**Comment by masonmcelvain** [comment]
The new header from https://github.com/iFixit/ifixit/pull/45558 isn't making it to vercel

![image](https://user-images.githubusercontent.com/52104630/202752018-32cc4c46-5754-4466-b8c4-eb673c1e78ef.png)
