### ISSUE TITLE
Research: Add mocking system for external api calls

### ISSUE THREAD

**Issue by batbattur** [iFixit/react-commerce#1023]
## Problem
Currently, we don't have many tests implemented yet for the product pages in react-commerce.

It would be easier for us to write more tests if we had a testing system to easily mock the external apis, 
such as the user api and the shopify api data for product pages. 

## Do This
Research on mocking systems for external api calls in react-commerce to accomplish the following:
> I'd like to see a system that lets us make a small number of fixtures with full product data but then lets us override various field. 

## Background
This came up after visiting https://github.com/iFixit/react-commerce/issues/452. 

From @sterlinghirsh:

> There have been some aspects that are difficult to test involving external apis, but I'm sure once we figure out a good way to mock them it'll get a lot simpler. One good one might be testing the product price display. It's a sort of tricky interaction between multiple fields (price, compare-at price, price tiers) and the user's discount tier. Tricky to test by literally creating pro users for the test, but if we can mock the user api and the shopify api data, it could work.

> I'd like to see a system that lets us make a small number of fixtures with full product data but then lets us override various fields. For example, suppose you have a simple product with 1 variant and no shipping restrictions. We can assert that no shipping restriction is shown. Then we can reuse the same product, but override just the shipping restrictions with `['is_battery']` and then assert that the battery warning is shown. We can do that again for a handful of combinations without needing a dozen full products.

> I was thinking of whether something like Mockingbird would work for our nextjs app. It would get conditionally injected in our api client code and let you run the test in record mode to save a snapshot, proxying the real api. Then in normal non-record test runs, it would use the saved data. There may be a better option for recording fixtures, but that was just my first thought

- [x] #1030
- [x] #1031
- [x] #1076

cc: @mlahargou

**Comment by batbattur** [comment]
I think mocking the api calls on client side might be easily done using cypress with [`cy.intercept()`](https://docs.cypress.io/api/commands/intercept#Stubbing-a-response).

We already intercept some user api endpoints and stub the response here: https://github.com/iFixit/react-commerce/blob/6089c7518f8aa10dda297d613e88ffde877d3f85/frontend/test/cypress/support/commands.ts#L42-L49

However, for any server/build time requests (e.g. happening in `getServerSideProps`), they're can't be intercepted using `cy.intercept()`. I think we need to tackle this before we get to the `record` and `overriding various fields` part.

<hr>

Then I've found the following [article](https://blog.byndyusoft.com/testing-next-js-website-with-cypress-a8475fd087e2), where they tried to use [MWS package](https://www.npmjs.com/package/msw) but instead ended up using [nock package](https://www.npmjs.com/package/nock). 

- Example with nock: https://glebbahmutov.com/blog/mock-network-from-server/
- Example with MSW: https://github.com/vercel/next.js/tree/canary/examples/with-msw#readme 

The article explains the issue with MSW and proposed solution using Cypress with Nock package (although I'm not sure how feasible it would be to start the next.js server as child process of Cypress test runner): 

> Spawn your Next.js server as a child process of Cypress test runner and mock all HTTP communication with [Nock](https://github.com/nock/nock).

**Comment by mlahargou** [comment]
I think msw seems like a good option. It looks like this is also possible with Playwright: https://frontend-digest.com/using-playwright-to-test-next-js-applications-80a767540091

cc @sterlinghirsh

**Comment by mlahargou** [comment]
@dhmacs Have you ever mocked server-side requests with Cypress?

**Comment by dhmacs** [comment]
No, I haven't since I try to keep integration tests as closely as possible to a live environment. 
User api can be mocked client side because there aren't requests being made server side.
Basically you want to mock Shopify storefront API? What tests would you like to write where you need to mock the Storefront API?

**Comment by mlahargou** [comment]
We'd like to have a system where we could easily implement tests on a product page with a product that has specific settings. https://github.com/iFixit/react-commerce/issues/452

i.e. View the product page but have the product be some mocked product that has the prop65 as true. Then, we could have UI assertions guaranteeing that the product had that setting true in the ui. 

The problem with live data for us is that products get deleted, go out of stock, change settings, etc. so we can't always guarentee the state of products and thus tests might start to fail.

Totally open to opinions here.

**Comment by batbattur** [comment]
We are currently testing out using [`msw`](https://mswjs.io/docs/) library to mock the Shopify storefront API:

Here is a testing branch that mocks `findProduct` query and returns a mocked response: https://github.com/iFixit/react-commerce/compare/testing-msw

Note: we're currently still playing around with `msw` so the test branch is just a prototype.

**Comment by dhmacs** [comment]
> The problem with live data for us is that products get deleted, go out of stock, change settings, etc. so we can't always guarentee the state of products and thus tests might start to fail.

I see, that makes sense to me, although we should make sure that we tests also against the live API to make sure that we aren't breaking anything when we change API versions.

> We are currently testing out using [msw](https://mswjs.io/docs/) library to mock the Shopify storefront API

This sounds like the right approach to me 👍  
I haven't used MSW directly, but I know many smart folks who recommend it, so I trust this is probably the best solution for mocking server side requests.

**Comment by mlahargou** [comment]
> I see, that makes sense to me, although we should make sure that we test also against the live API to make sure that we aren't breaking anything when we change API versions.

Yes totally. I think we would only use the server side mock when we need a product with specific properties.

**Comment by batbattur** [comment]
@ardelato found a good article for adding [Testing Next.JS with Cypress and Mock Service Worker](https://dillonshook.com/testing-nextjs-with-cypress-and-msw/). 

We're planning to add `msw` and `jest` tests first, and then after we finish `jest/msw` tests, we will integrate `msw` with `Cypress` if we need to. 

The reason why we are starting `msw` for jest tests is because it doesn't need to be added in the main app.
Whereas for Cypress tests, `msw` needs to be imported in `frontend/pages/_app.tsx` in order to intercept the server-side requests.
