### ISSUE TITLE
React Commerce Testing: Determine which tests do not need mocking

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1029]
## Description

https://github.com/iFixit/react-commerce/issues/452 has a lot of tests to create, but we are not sure which ones we can start working on. 

## To Do:

- [ ] Figure out which tests do not need mocking so we can start creating tests

**Comment by mlahargou** [comment]
I'm having trouble figuring out what ones we don't want mocked. They all seem like we need some sort of mocking. I'm wondering if it makes sense to just start writing tests with prod data and then when we get the mocking working, we can switch over to using mocked products.

**Comment by ardelato** [comment]
My testing terminology is probably not correct, but what do you mean by mocking? Does that mean mocking the `prop` data or `api` endpoints?

**Comment by mlahargou** [comment]
The issue title said to figure out what tests don't need mocking. I was imagining you were talking about api mocking. Basically set the response you want back so that you can do testing on expected data.

**Comment by ardelato** [comment]
Ahh, gotcha! 

Then yeah I was thinking of mocking the `API`'s when writing the title.

> They all seem like we need some sort of mocking. I'm wondering if it makes sense to just start writing tests with live data and then when we get the mocking working

Hmm, I think that works, since we will have a test that is already written, and all we would need to do, is change the data with the mocked one.

**Comment by mlahargou** [comment]
Cool, I'm going to close this as done. I'll open a few issues to implement some of the tests in https://github.com/iFixit/react-commerce/issues/452
