### ISSUE TITLE
See about creating a `dev-ci` type of environment to help create mocked items

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1031]
## Description

Currently, it is very hard to mock API requests with Cypress because some of them are server-side requests to external services like Shopify. 

It might be easier to boot up the `backend` and `frontend` docker containers in a different mode that is meant for testing. For instance, if we boot up for `testing` mode then we could override some of the API endpoints we make to external services and instead serve data from fixtures. Essentially mimicking what we do for the `ubreakit` machine.

We can possibly make use of the `NODE_ENV` we set for `Cypress` testing
https://github.com/iFixit/react-commerce/blob/7e440609660a715355af3b1c479719f3746cce0c/.github/workflows/main.yml#L30

## To Do:
- [ ] Figure out what behavior we want to modify for `testing`
- [ ] Figure out how to configure the way the `backend` and `frontend` boot up

**Comment by mlahargou** [comment]
What's the difference between this and using something like msw to mock the requests?

**Comment by dhmacs** [comment]
What APIs do we want to mock and why?

**Comment by ardelato** [comment]
> What APIs do we want to mock and why?

That would be part of the research that would be completed for this issue.

**Comment by ardelato** [comment]
Closing this issue, we don't need to change a lot of environment settings to help create mocked items. Therefore, creating an entire `dev-ci` environment would be overkill.
