### ISSUE TITLE
Collections: Reset `page` when deselecting facets

### ISSUE THREAD

**Issue by masonmcelvain** [iFixit/react-commerce#1034]
## Problem

~~When a multi select is selected/deselected, the `?page=` param should disappear from the url and the view should reset to the first page.~~

It also seems that deselecting a single select using the X in the blue boxes doesn't reset the page param.

[Screencast from 11-16-2022 02:33:13 PM.webm](https://user-images.githubusercontent.com/52104630/202276808-375fc75b-ab0f-4aaa-83ab-e943647a6a41.webm)

## Background 

#1010

CC @sterlinghirsh @danielbeardsley @rickisXP

**Comment by danielbeardsley** [comment]
> When a multi select is selected/deselected, the ?page= param should disappear from the url and the view should reset to the first page.
 
 This was fixed with #1004. The `Item Type` selector doesn't clear the other filters. I'm not 100% sure if that's desired or not.

**Comment by masonmcelvain** [comment]
> This was fixed with https://github.com/iFixit/react-commerce/issues/1004.

Oh yea you're right, derp. 

> On the other hand, the Item Type selector doesn't clear the other filters. I'm not 100% sure if that's desired or not.

@sterlinghirsh answered that question here I think: https://github.com/iFixit/react-commerce/issues/1005#issuecomment-1315663610

**Comment by masonmcelvain** [comment]
I updated the issue to just be about resetting `page` when the facets are deselected using the blue box.
