### ISSUE TITLE
Add structured data on Collection page

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#104]
Structured data facilitates the understanding of pages to search engines. 

## Reference

- [Understand how structured data works](https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data)

**Comment by JFleischhauer** [comment]
We should include [breadcrumbList](https://schema.org/BreadcrumbList) and either [WebSite](https://schema.org/WebSite) (thorough and extensive information), or [WebPage](https://schema.org/WebPage) (very basic information). I vote for WebSite and including all the information we can. What do you think @ifixitmaxb? 

Here is an [implementation of webpage and breadcrumbList](https://validator.schema.org/#url=https%3A%2F%2Fwww.korodrogerie.de%2Fsuperfoods%2F)

I agree on productCollection, seems like we should wait until that has been finalized. 

We are currently using [itemList](https://schema.org/ItemList), but that seems quite wrong:
"A list of items of any sort—for example, Top 10 Movies About Weathermen, or Top 100 Party Songs. Not to be confused with HTML lists, which are often used only for formatting."
I found one implementation for clothing, using [ProductGroup](https://schema.org/ProductGroup), but it sounds like this doesn't work for us as well: 
"A ProductGroup represents a group of Products that vary only in certain well-described ways, such as by size, color, material etc."

**Comment by federicobadini** [comment]
I've submitted a PR to include the product-list breadcrumbs structured data.

Regarding the inclusion of structured data describing a collection, [`ProductCollection`](https://schema.org/ProductCollection) is still WIP. 

`WebSite` seems quite a generic schema and the example linked [above](https://github.com/iFixit/react-commerce/issues/104#issuecomment-966308204) shows that most of the included properties are ignored:

<img width="1625" alt="Screenshot 2023-01-03 at 14 00 58" src="https://user-images.githubusercontent.com/7805759/210364224-695c24ac-0717-40c3-b8fc-6f1fe7a7f404.png">

I found that there are two other candidate schemas, namely [`Collection`](https://schema.org/Collection) and [`CollectionPage`](https://schema.org/CollectionPage).

- `CollectionPage` has more specificity than WebPage but still is considered a schema to describe a group of creativeWorks, not products.
- `Collection` on the contrary is described as `A collection of items, e.g. creative works or products.` so seems to be a better choice for describing a group of products.

However I've found no usage online (even Bestbuy and other players only include breadcrumbs).
So I'd like to ask @ifixitmaxb if he has some insights on which of these is best to implement.

**Comment by davidrans** [comment]
I think breadcrumb schema data is useful, but I don't think it's worth the effort to implement these more obscure schema
