### ISSUE TITLE
Product Page: Add tests for Product Description

### ISSUE THREAD

**Issue by mlahargou** [iFixit/react-commerce#1042]
- [ ] Verify that the product description is visible
   - [ ] For products with the following sections, verify that they show up if available:
       - [ ] notes
       - [ ] disclaimer
       - [ ] warning

**Comment by ardelato** [comment]
working prototype https://github.com/iFixit/react-commerce/compare/main...testing--msw-infastructure-for-products

**Comment by mlahargou** [comment]
That looks great!
