### ISSUE TITLE
Product Page: Add tests for a product with different variants

### ISSUE THREAD

**Issue by mlahargou** [iFixit/react-commerce#1044]
- [ ] `Condition`
   - [ ] `Style`
   - [ ] `Color`
   - [ ] Ensure the price in the cart matches the price for specific condition/variant/color.

**Comment by batbattur** [comment]
Added a new test for a product with different **`style`** variants in https://github.com/iFixit/react-commerce/pull/1062. 

Going to skip creating tests for the `Condition` and `Color`, since it's going to be essentially a duplicate of the #1062.
