### ISSUE TITLE
Sentry frontend web vitals recording: We're missing most of the data

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1077]
Not 100% sure why, but likely this issue is describing the same problem:

https://github.com/getsentry/sentry-javascript/issues/3803 and
https://github.com/getsentry/sentry-javascript/issues/3833

Specifically, only ~2.5% of our [performance samples](https://sentry.io/organizations/ifixit/discover/results/?display=default&field=count%28%29&field=count_if%28measurements.lcp%2Cgreater%2C0%29&field=equation%7Ccount_if%28measurements.lcp%2Cgreater%2C0%29+%2Fcount%28%29&field=avg%28measurements.lcp%29&interval=1h&name=All+Events&project=6469069&query=event.type%3Atransaction+transaction.op%3Apageload++browser.name%3AChrome&sort=-count%28%29&statsPeriod=14d&user=669438&yAxis=equation%7Ccount_if%28measurements.lcp%2Cgreater%2C0%29+%2Fcount%28%29&yAxis=count%28%29) actually have FCP / LCP values: (Note, this is already limited to Chrome browsers)

![image](https://user-images.githubusercontent.com/26855/204607607-507a3fdc-229c-4c34-a3bf-9b369c3f8325.png)

### Do This
Possibly this can be fixed with this option: 
https://github.com/getsentry/sentry-javascript/issues/3833#issuecomment-909652059

CC @jarstelfox

**Comment by danielbeardsley** [comment]
I've experimented (and failed) and read all the issues about LCP on sentry's github. It didn't seem like my concern (LCP is not being captured) wasn't represented so I made an issue:
https://github.com/getsentry/sentry-javascript/issues/6742

Note: they've deprecated and removed the option referenced in the description. This isn't a problem with next.js, nor this app, [the same thing is present in our php app too](https://sentry.io/organizations/ifixit/discover/results/?display=default&field=count%28%29&field=count_if%28measurements.lcp%2Cgreater%2C0%29&field=equation%7Ccount_if%28measurements.lcp%2Cgreater%2C0%29+%2Fcount%28%29&field=avg%28measurements.lcp%29&interval=1h&name=All+Events&project=1281569&query=event.type%3Atransaction+transaction.op%3Apageload&sort=-count%28%29&statsPeriod=14d&user=669438&yAxis=equation%7Ccount_if%28measurements.lcp%2Cgreater%2C0%29+%2Fcount%28%29&yAxis=count%28%29)

**Comment by danielbeardsley** [comment]
@federicobadini -- sentry's performance metrics are pretty much useless (at least for LCP) right now so we may still have a use for that script that queries metrics from Google.

**Comment by federicobadini** [comment]
> @federicobadini -- sentry's performance metrics are pretty much useless (at least for LCP) right now so we may still have a use for that script that queries metrics from Google.

In last week call we discussed the usage of Sentry for monitoring CWV, and we also discussed that some metric type were reporting fewer events than others.
Since we are collecting just a very tiny fraction of transaction on this project though, we wanted to try to augment that quota to verify if we could reach a reasonable amount of samples even on those metrics that right now are reporting only a few measurements.
If we can find a good compromise, it could allow to have reliable insights while we wait for the resolution on sentry side.

cc @davidrans

**Comment by danielbeardsley** [comment]
> If we can find a good compromise, it could allow to have reliable insights while we wait for the resolution on sentry side.

I'll bump the sampling rate, but I still don't think the numbers (at least LCP) should be trusted at all because of the reason I gave in the sentry issue:

> Only ~3% of our page pageload transactions have a recorded LCP. I've looked at all the issues regarding LCP but none of them quite capture that it's broken and recording so little data. Given the descriptions in the other issues, it seems to be about timing. If that's the case and we're missing all LCP events that happen after something, or missing all LCP events that happen before something, then surely the data is not to be trusted.
