### ISSUE TITLE
Clear search button is hidden after resetting filters

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#1084]
### Issue Overview:

![firefox_tTWFR95QGw](https://user-images.githubusercontent.com/95656772/204855788-bd95b0e1-3d04-4301-b934-c5b7500a39f9.gif)

### Reproduction Steps:
1. Navigate to https://ifixit.com/Parts
2. Search for something to return no results
3. Click on `Reset filters`
4. Notice that the clear button is hidden when going back to the search bar

**Comment by dhmacs** [comment]
I think here the expected behaviour when you click reset filters is that all filters **including** the search query are cleared right?

**Comment by jordycosta** [comment]
@dhmacs Yeah I would expect that, that's probably a good way to resolve this
