### ISSUE TITLE
Cart view: non-uniform cart items

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#1089]
### Overview:
![IMG_5267 2051](https://user-images.githubusercontent.com/95656772/204895187-2f945c14-c97c-437a-8e17-e5844bc4a959.PNG)

The UI for these items aren't aligned (looks like this is due to the aspect ratio of the cart item image being unconstrained)

It would be great to have the cart items be uniform; so that the product title, inventory increment/decrement, and item codes are all in-line with each other.

**Comment by federicobadini** [comment]
Not reproducible, [already corrected](https://github.com/iFixit/react-commerce/commit/2e5c90868e35b57646ecdd308f0a36fcc44143d4) by applying fixed width and height + `objectFit="cover"`
