### ISSUE TITLE
Don't zoom low-res images

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1097]
On Product Detail Page, disable hover zoom when product images are not high resolution enough to make zooming useful. I'm not sure at what resolution zooming is useful but I feel like it would be an easy question for dev to answer.

![image](https://user-images.githubusercontent.com/7053450/205136292-71998cb6-5a6c-487b-a659-4e62d25afee9.png)

Example product: https://www.ifixit.com/products/lenovo-ideapad-c340-15iil-c340-15iwl-laptop-battery

Not a high priority, but this should be done at some point.

**Comment by deltuh-vee** [comment]
I looked at some of the image sizes in ifixit_cart.cart_images.
```
WITH sizes AS (
	SELECT
		width * height size
	FROM
		cart_images
	ORDER BY
		size DESC
)
SELECT
    size,
	count(size)
FROM sizes
GROUP BY
	size
order by size DESC
```
![image](https://user-images.githubusercontent.com/5289715/205778253-c6875770-fd93-4fcf-821e-48348cab86d8.png)
It seems like most of the images have an area of 37,210,000 so we should probably disable zoom for the images somewhere below that limit.

**Comment by federicobadini** [comment]
Product images are retrieved from Shopify CDN, so in terms of picture quality we are limited to a maximum of 20MP images (~4472x4472). However picking some random product I see that most images are available in 2000x2000 as maximum dimension. So the first thing to clarify is if we are uploading downscaled images to Shopify (cc @sterlinghirsh).

There is the possibility that for a specific product some images end up being below the threshold and some others above it. In my opinion it may be counterintuitive for the user to have the zoom feature only on a subset of the product images, so I would enable or disable the feature for the whole product. Let me know if you disagree on this point.

Still I consider not offering the zoom feature on some product something that is not super intuitive for the user. 
So I hope that even though we introduce this feature, maybe we can start an activity aiming at retaking those low res image, to offer the best experience possible on any product page

**Comment by jeffsnyder** [comment]
> retaking those low res image, to offer the best experience possible on any product page?

We are adding many dropshipped parts to the catalog. These are items we never physically touch. So we're reliant on our partners to provide images. Unfortunately a lot of their images are not great. If the products sell well enough, we will likely try to get better photographs. But in the meantime, we need to make the best of what we have. 

> I would enable or disable the feature for the whole selected variant or the whole product

I am certain that when we have a single image below the threshold, all images for the product will be below the threshold. 

@deltuh-vee can you give a couple example skus for the peaks in the query result you screenshot above? We could just look at some relevent product pages to find a reasonable cutoff.

**Comment by deltuh-vee** [comment]
@jeffsnyder 
Here's some Product codes at the various size peaks: 

16,000,000 - 179022, 179039, 340033, 341027, 162039

24,127,744 - 235006, 297032, 308007, 239095, 239022

36,000,000 - 108051, 123135, 171043, 117063, 297071

37,210,000 - 453012, 429013, 245176, 245248, 245263

**Comment by federicobadini** [comment]
We decided to disable the zoom whenever the inner size of the image is below the size of the containing element (basically when `image intrinsic width * image intrinsic height < container width * container height`).

In that case allowing to zoom is not providing any sort of advantage to the user.

This seemed a reasonable point to start from. We can easily harden this threshold in a future PR if needed.

**Comment by davidrans** [comment]
Here's an example of another product that doesn't look good when zoomed. Seems like the issues is that the image is only slightly bigger than the container:
https://www.ifixit.com/products/razer-blade-15-2018-laptop-battery
![image](https://user-images.githubusercontent.com/806152/217030150-8b944170-b2f3-4f74-a0e5-31404e0e6fe5.png)

**Comment by federicobadini** [comment]
We can define a zooming factor that harden a bit the formula that disables the zoom. 
Something like:
```ts
isDisabled = image intrinsic width * image intrinsic height < container width * container height * FACTOR
```

**Comment by davidrans** [comment]
Yeah, I think that makes sense. We should be able to calculate whether the zoom is going to be blurry. Maybe even change the zoom level based on the size of the original image?

**Comment by federicobadini** [comment]
Currently the zoom is applying a static magnification factor of 3 (vertically).
Most images are available at a maximum resolution of 2000x2000.
The zoom area depends from the user screen size.

I think we have 3 possible ways to move from what we have:

1. Add a static `FACTOR` that enables zoom only for images that are larger than the gallery container by at least a `FACTOR`  
2. Keep a constant zooming factor and enable zoom only when that constant factor does not imply showing a blurred image
3. Modulate the zooming factor so as to avoid that the image gets blurry

Option number 1 allows some blurriness in images but we might find a good compromise.

Option number 2 might be too restrictive unless the zooming factor is reduced: for example on a 16" screen with pixel-density 2 and a zoom container height equal to `~750px`, we would need an image with ~4500 vertical pixels to achieve pixel perfection with a zooming factor of 3.

Option number 3 is a bit more complex to achieve but it can be done too.

I feel it is just a matter of deciding what solution we prefer.

**Comment by davidrans** [comment]
I'm fine with option 1 for now, and we can be cleverer if we continue to find images that look bad.

**Comment by sterlinghirsh** [comment]
I'm fine with that too, though I'll also say I am fine going with the 0-effort approach, letting it zoom even if it's a bit blurry if that's the best quality we have.

**Comment by danielbeardsley** [comment]
A lot of screens these days have high DPI and a lot of people don't have above-average vision. I think there's a lot of value in being able to make a picture larger even if we don't have the resolution to show more pixels. In other words, even though zooming in on picture that's already shown at 1:1 doesn't show more pixel information, people may still appreciate being able to make that picture larger.

Thoughts?

**Comment by sterlinghirsh** [comment]
@danielbeardsley I agree generally. It's nice to have the ability to open the full size image in a new tab to account for cases like that. But if the worst that happens is we show a blurry zoomed image when it's the best size we have, it doesn't seem like that big of a problem.
