### ISSUE TITLE
Add search functionalities of parts collection page

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#11]
![Screen Shot 2021-05-12 at 16 45 50](https://user-images.githubusercontent.com/4640135/117995320-845f0d00-b341-11eb-9441-677b00bc529e.png)

## ❓ Questions

- [x] What is the facet that should be used as parts category?
- [x] What is the "manufacturer" facet?
- [x] What's the scenario for this feature? Is the user supposed to search "iPhone" and get iPhone collection pages, or should the user get just a list of products that matches that keyword? Is this just a quicker way to get to some subcategory collection, or is this used to quickly find specific products?

**Comment by sterlinghirsh** [comment]
>  What is the facet that should be used as "Parts" category?

Right now there's no specific tag we're using for parts vs tools. I'll make sure we add one soon, but in the mean time you can use `named_tag_names = 'worksin'` to get all the parts. If we're trying to make a tools page collection page, we'd have to filter those out. But I'll make sure we add a part/tool tag soon so we don't have to rely on the worksin tag directly. It might be a few days or a week before we get it all filled in though.

> What is the "manufacturer" facet?

"named_tags.Device Brand" should be the one. I added some data for this recently, so it probably wasn't showing up before. There might not be complete data filled in for all products yet, but most of them should work fine.

**Comment by sterlinghirsh** [comment]
Oh I filled in "named_tags.Device Category" too.

**Comment by dhmacs** [comment]
We need icons category mapping

**Comment by kwiens** [comment]
Let's hard-code the icons in a JSON file or something now, and we'll add it to the API later.

**Comment by dhmacs** [comment]
During last call we've decided to focus on nailing the user experience of the generic use case. We'll come back to thinking about this when we'll have specific use cases in mind (e.g. car parts)
