### ISSUE TITLE
findProduct GraphQL Query: move querying product ref metafields to client side

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1110]
The `findProduct.graphql` query is very slow (1000 - 1500ms). Turns out, removing the product reference metafields from the query takes it down to 200ms.

Do This
===
Move the query on the two product reference metafields to the client side and get us that product page 800ms earlier.

CC @sterlinghirsh @iFixit/shopify

**Comment by dhmacs** [comment]
I'm looking into this as well. Have you conducted some experimentations already?

**Comment by danielbeardsley** [comment]
> Have you conducted some experimentations already?

We tried playing with this query via process of elmination, determined the above fact: removing these two metafields from the query, makes it 800-1000ms faster. We haven't written any code to defer it to the client side.

**Comment by danielbeardsley** [comment]
I've approached this several ways and the short answer is: it's not possible with the Shopify Storefront API.

The Storefront API is deficient:

* Doesn't have a `productVariant` endpoint
   * So, we can't get the variant ids on the server and then query their details client-side
* Doesn't support product_reference metafields
   * We can only retrieve the encoded value of the metafield (json-encoded array of ids) 
   * The `references()` function isn't available client-side

I think this is another instance where trying to use Shopify's API as a storage medium is hampering us. There is a [*lot*](https://github.com/iFixit/react-commerce/blob/main/frontend/models/product.ts) [of](https://github.com/iFixit/react-commerce/blob/main/frontend/lib/shopify-storefront-sdk/operations/productVariantCard.fragment.graphql) [code](https://github.com/iFixit/react-commerce/blob/main/frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql) that supports querying graphQL and extracting / decoding / transforming the values that come out. Not to mention the API appears well documented, but definitely has missing / wrong pieces which  results in more time being spent understanding the system.

**Comment by dhmacs** [comment]
> * Doesn't have a `productVariant` endpoint
>   * So, we can't get the variant ids on the server and then query their details client-side

Doesn't have an explicit query for variant, but you can grab the variant like this:

```graphql
query findVariant($id: ID!) {
  variant: node(id: $id) {
    id
    ... on ProductVariant {
      title
      quantityAvailable
    }
  }
}
```
The node query operation let's you grab any available object by its id.

* Doesn't support product_reference metafields
   * We can only retrieve the encoded value of the metafield (json-encoded array of ids) 
   * The `references()` function isn't available client-side

> There is a [*lot*](https://github.com/iFixit/react-commerce/blob/main/frontend/models/product.ts) [of](https://github.com/iFixit/react-commerce/blob/main/frontend/lib/shopify-storefront-sdk/operations/productVariantCard.fragment.graphql) [code](https://github.com/iFixit/react-commerce/blob/main/frontend/lib/shopify-storefront-sdk/operations/findProduct.graphql) that supports querying graphQL and extracting / decoding / transforming the values that come out. 

As much as I would like this code to be much shorter, there are two aspects that justify this. First is type safety, second is that if we didn't parse this, all the polishing would be done in the frontend within the components, making the frontend code more complex.

Having said that, I don't think we need to embark into trying to do more things client side. I think we need a Redis cache. There's a lot of room for improvement in how we're managing the cache at the CDN level as well. So I'd suggest to postpone this effort and improve caching first. I'm confident this would fix our slow response issues

**Comment by dhmacs** [comment]
Beside this, I'll open a PR this week to introduce an swr server cache

**Comment by masonmcelvain** [comment]
https://shopify.dev/api/storefront/unstable/queries/node

**Comment by dhmacs** [comment]
@danielbeardsley It seems that with the Redis cache we fixed our slow queries issue, so I'm going to close this.
