### ISSUE TITLE
Fix responsive images loading too big

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1136]
Related to #1131 and #1067 

We have some images that are displayed quite small, but the loaded image is huge, causing unnecessarily poor performance.

Example: On /Parts/iPhone, at screen-width 997px, in grid view, the first product image showing at 301px wide is actually downloading a 1000x1000 image. According to the `sizes` attr, we have `(max-width: 1000px) 400px`, meaning that the image will download the best size to show a 400px image. 
![image](https://user-images.githubusercontent.com/589425/207208571-3b794a60-dce9-4cd8-85d8-8cbe749c0f0a.png)

However, in the srcset, the image that would be shown at 400px is the size1000 image, due to the large gap between size400 and size1000.
![image](https://user-images.githubusercontent.com/589425/207208917-f947db48-ef59-4ce9-9a43-9bf4df2826d3.png)

Try out making a custom image component that uses correct sizes from our image size map.

**Comment by danielbeardsley** [comment]
I think this was mostly fixed with https://github.com/iFixit/ifixit/pull/52942
