### ISSUE TITLE
Bug: Review hiding logic isn't working

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1140]
Two problems with the Reviews section. 

1) Ratings with no text Review should not show up in the Reviews section 
2) If the average Rating is <4 and there are <10 total reviews, we should not show the Reviews section. (We might want to still show the "Write a review" banner.. this component is new since we defined the desired logic.)

Possibly related to https://github.com/iFixit/react-commerce/issues/215  ? Or maybe this issue didn't solve the problem? 

Issue from old template with links to related issues, logic, etc: https://github.com/iFixit/shopify-v2/issues/784

Example product: https://www.ifixit.com/products/anti-clamp

![image](https://user-images.githubusercontent.com/7053450/207442813-9a30a985-281c-48b1-95fd-d58c9c320fe8.png)

This should be fixed ASAP as it is affecting our new release products. 

@erinemay @dhmacs @sterlinghirsh

**Comment by davidrans** [comment]
This is only partially complete. We're still including the review schema data so Google is still indexing these values:
![image](https://user-images.githubusercontent.com/806152/210281570-2df6fad5-63a9-4e6a-afd8-947a714dccee.png)
and Google is still indexing it:
![image](https://user-images.githubusercontent.com/806152/210281582-f7f1baa2-d3e3-4994-9a04-d19f083377fb.png)
