### ISSUE TITLE
Product Page: Add Test for Banner Section

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1164]
## Description

This is an ongoing effort in addressing https://github.com/iFixit/react-commerce/issues/452

### Requirements

WIP

**Comment by batbattur** [comment]
It looks like we haven't implemented this feature yet (not 100% sure, cc: @dhmacs).
Maybe still planning? (I can see the banner in [figma](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=5108%3A54091)).

Should we close this issue for the moment?

**Comment by ardelato** [comment]
Closing this issue for now. We can reopen this issue once we implemented the feature and decide to add tests around it.
