### ISSUE TITLE
Product Page: Add Tests for Products with Stories

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1167]
## Description

This is an ongoing effort in addressing https://github.com/iFixit/react-commerce/issues/452

### Requirements

 - [ ] If the product has associated Stories, make sure this section shows up.
 - [ ] Make sure the links are clickable.
 - [ ] If the product has no associated Stories, make sure this section doesn't show up.

**Comment by mlahargou** [comment]
There aren't any stories on products

https://ifixit.slack.com/archives/C01GMQXJC95/p1671489818030619?thread_ts=1671479249.497589&cid=C01GMQXJC95
