### ISSUE TITLE
Fix store selector links

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1174]
We added store selector links to product pages in https://github.com/iFixit/react-commerce/pull/1078, and they work for products offered internationally like https://www.ifixit.com/products/iphone-6s-replacement-battery. Its footer links go to the appropriate corresponding Shopify product page for each store. 

### Product page 
Not offered internationally:
https://www.ifixit.com/products/dji-spark-led-cover-mount-front-left-or-rear-right

Behavior: It looks like we just pick a random (popular?) product page and link to that?
Expected: If the product is not available, it should be a link to the appropriate store's homepage.

Footer links:
- https://australia.ifixit.com/products/everyday-carry-bundle
- https://canada.ifixit.com/products/everyday-carry-bundle
- https://eustore.ifixit.com/products/oneplus-7-pro-replacement-battery
- https://store.ifixit.fr/products/oneplus-7-pro-replacement-battery
- https://store.ifixit.de/products/oneplus-7-pro-replacement-battery
- https://www.ifixit.com/products/dji-spark-led-cover-mount-front-left-or-rear-right
- https://store.ifixit.co.uk/products/oneplus-7-pro-replacement-battery

### Collection page
https://www.ifixit.com/Parts/iPhone

Behavior: These also look like random popular part pages. Even the US link is to a product page. 
Expected: Not spec'd. Ideally they'd link to the appropriate corresponding collection, but I don't think we've had that functionality previously. Probably just link to the correct store homepage for now. (cc: @jeffsnyder)

Footer links:
- https://australia.ifixit.com/products/repair-business-toolkit
- https://canada.ifixit.com/products/repair-business-toolkit
- https://eustore.ifixit.com/products/mac-mini-late-2018-memory-maxxer-ram-upgrade-kit
- https://store.ifixit.fr/products/mac-mini-late-2018-memory-maxxer-ram-upgrade-kit
- https://store.ifixit.de/products/mac-mini-late-2018-memory-maxxer-ram-upgrade-kit
- https://www.ifixit.com/products/macbook-pro-17-unibody-early-2009-memory-maxxer-ram-upgrade-kit
- https://store.ifixit.co.uk/products/mac-mini-late-2018-memory-maxxer-ram-upgrade-kit

cc: @masonmcelvain

**Comment by masonmcelvain** [comment]
I see the enabled domains metafield value for the [product](https://ifixit-us.myshopify.com/admin/products/6565821513831) you linked is

```json
[{"code":"us","domain":"https://www.ifixit.com","locales":["en-US"]}]
```

I think the expected behavior in this situation is to link to `www.ifixit.com/products/handle`, and then link to the origin of the other stores (without `/products/handle`). I'm not sure why random handles are being populated from glancing at the implementation. The store url data in strapi.ifixit.com/admin also seems correct.
