### ISSUE TITLE
Products are incorrectly hiding their compatibility display

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1182]
Slack Ref https://ifixit.slack.com/archives/C0252FETV2S/p1671638641526619
## Problem
From Jeff Stephens:
> I stumbled on these two products that are not displaying compatibility. They have a worksin attached in Akeneo. I went looking for other cases but I came up empty. The only thing I see in common between the two worksin is the checked variants are “default.”
> 209021-1  [Nintendo DS Lite Touchscreen](https://www.ifixit.com/products/nintendo-ds-lite-touchscreen)   No compatibility displayed on the right below the description or below the reviews. The product has [worksin 583](https://www.ifixit.com/Admin/Worksin/worksin.php?worksin=583) attached.
> 258027-2  [Nintendo 3DS XL Battery](https://www.ifixit.com/products/nintendo-3ds-xl-replacement-battery)   No compatibility displayed on the right below the description or below the reviews. The product has [worksin 2028](https://www.ifixit.com/Admin/Worksin/worksin.php?worksin=2028) attached.

Upon investigating, it looks like the issue is that we don't handle `null` as a valid case in the list of variants. We do handle empty string properly, but in our DB, the "default" variant values in topic_variants are about evenly split between null and empty string. The variant name makes it into metafields.ifixit.compatibility_json, and my hunch is that the field fails validation since we expect it to be string, not nullable string.

## Do This
The simplest fix is probably to adjust the validation to support null or string. Alternatively we could adjust the values we save to Shopify (From ProductBodyFactory) to always be empty strings instead of nulls, but then we'd have to repush a bunch of data, though the data would be more consistent in Shopify going forward.

**Comment by deltuh-vee** [comment]
I'd advocate for consistency since we're doing a code change either way.

**Comment by masonmcelvain** [comment]
@sterlinghirsh  would it be reasonable to `array_filter` out empty strings and nulls in PBF?

The frontend doesn't really look like it's expecting empty strings anyways:

https://github.com/iFixit/react-commerce/blob/26b01d5123b21df836e4ad9bfabe92096a48c098/frontend/components/common/CompatibleDevice.tsx#L46-L55

**Comment by masonmcelvain** [comment]
Hm I guess empty strings/null do carry meaning in this context, even though we're not using them. I'll update the frontend for the time being since it's a live bug, and we can later on decide if/how to handle the nulls on the backend.
