### ISSUE TITLE
Product Page: Add tests for Frequently Bought Together

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1202]
## Description

This is an ongoing effort in addressing https://github.com/iFixit/react-commerce/issues/452

### Requirements

- [ ] Only select `Current item` and click `Add to cart`.
  - [x] Ensure there's only one item in the cart.
- [ ] Select multiple items.
   - [x] Before clicking `Add to cart`, ensure the total price on the button matches up for the products you've selected.
   - [ ] Then click on the cart and ensure there are the items you selected in the cart, and the total price.

**Comment by mlahargou** [comment]
Ah, I just connected it b/c I couldn't confirm the prices in the cart drawer. I think I'm fine with the test for now as it confirms the correct products are in the cart drawer. Thoughts?

**Comment by ardelato** [comment]
It was only a matter of the discounted price not matching due to the usage of the `cart` API correct?

**Comment by mlahargou** [comment]
>  It was only a matter of the discounted price not matching due to the usage of the cart API, correct?

Yeah, so I couldn't confirm the prices. I think this is fine for now.
