### ISSUE TITLE
Product Page: Add E2E tests for Compatible Devices

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1205]
## Description

This is an ongoing effort in addressing https://github.com/iFixit/react-commerce/issues/452

### Requirements

⚠️ We already created some `Jest` tests for the compatible devices section https://github.com/iFixit/react-commerce/issues/1143 to ensure that component renders when expected. These tests are more integration tests that includes the user's devices and the product page. 

 - [ ] If the user has the **compatible** associated device/topic to the product:
   - [ ] Check if the product says it's compatible.
- [ ] If the user has an **incompatible** associated device/topic to the product:
   - [ ] Check if the product says it's incompatible.
 - [ ] If the user doesn't have any associated device/topics in their profile:
   - [ ] the compatibility section should not show up (not sure for the exact behavior)

**Comment by batbattur** [comment]
I think this has more to do with the workbench (which has the features we want to test) instead of the compatibility section. 

The workbench is not implemented yet, ref: https://github.com/iFixit/react-commerce/issues/151.

Should we close this for now?

**Comment by ardelato** [comment]
> I think this has more to do with the workbench (which has the features we want to test) instead of the compatibility section.

Ahhh okay, then yeah let's close this for now.
