### ISSUE TITLE
Featured Products on ProductDetailPage has no height limit

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1206]
Featured Products on ProductDetailPage has no height limit so the section become rather tall to accommodate the square five-across product grid.  And not all product images are sharp at this size (might be a separate issue/problem). 

![image](https://user-images.githubusercontent.com/7053450/210273174-479f429e-5415-4a1d-abe7-188fd1843640.png)

https://www.ifixit.com/products/fixmat

I'd propose we set a max height for this section and pull in more products to the section. It might make sense to convert this section to a carousel while we're at it.

**Comment by davidrans** [comment]
Let's iterate on the design here, cause my hotfix isn't ideal @mmarcon91 @dhmacs

**Comment by mmarcon91** [comment]
@jeffsnyder what resolution does your monitor have?

@davidrans  In my opinion you could solve it by have 6 products over 1536px

Base : 2x3 products
Above 768px : 3x2 products
Above at 1024px : 5 products
Above 1536px : 6 products

**Comment by jeffsnyder** [comment]
I'll have to recheck when I'm in the office later this week. The monitor I'm on now is 1920 x 1080. The feature is different now and it all looks good to me, even when I zoom out. 👍

**Comment by mmarcon91** [comment]
If we want to keep the product list inside a wrapper the design has to be rethought. Because the way it was designed it had to be (at least in most displays) all width.

**Comment by sterlinghirsh** [comment]
@mmarcon91 I think you're right that we should take another look at the design. It's definitely too big with 5 products at the screen size we're looking at. 6 products or maybe even more could work. I'm ok with putting it in a wrapper if necessary, but I did like the look of the original full-width version on narrower windows. I will sometimes have a full screen browser window at 4k, and admittedly most websites don't look good, but we should at least try to make it look good at 1920 wide and try to make it look reasonable if we go past that.

**Comment by mmarcon91** [comment]
> @mmarcon91 I think you're right that we should take another look at the design. It's definitely too big with 5 products at the screen size we're looking at. 6 products or maybe even more could work. I'm ok with putting it in a wrapper if necessary, but I did like the look of the original full-width version on narrower windows. I will sometimes have a full screen browser window at 4k, and admittedly most websites don't look good, but we should at least try to make it look good at 1920 wide and try to make it look reasonable if we go past that.

I suggest removing the wrapper and using these rules:

Base : 2x3 products
Above 768px : 3x2 products
Above at 1024px : 5 products
Above 1536px : 6 products

Wecould set a max-width to the card to prevent it from becoming very large at resolutions above 1920

**Comment by sterlinghirsh** [comment]
I'm willing to try it. The way I see it in my head, 2x3 or 3x2 products is going to be very tall if the product images scale like they do now. @dhmacs or @federicobadini feel free to try implementing it this way when you have some time, but it's not a top priority for me right now.
