### ISSUE TITLE
Consolidate Product Data APIs

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1219]
## Description

This initially came up when trying to add tests for #1216. We are currently using two different APIs to retrieve data about a product: `shopify.findProduct` and `/api/2.0/store/user/cart`. For instance, when we first visit a product page, the stock quantity is retrieved from shopify. However, after adding the product to your cart, the stock quantity is then retrieved by the `cart` API.

https://github.com/iFixit/react-commerce/blob/9d5ef55ebec5a5e7a55240624e75d64dddeee9b4/frontend/templates/product/sections/ProductSection/AddToCart/index.tsx#L288-L302

In addition, it seems that `Shopify` and our DB are not synced up, then we will also have issues when adding a discounted product as the price in the cart will not match up.

![image](https://user-images.githubusercontent.com/22064420/210671782-40e789ca-c745-4045-b018-864ac4d42980.png)

### To Do 

- [ ] Consolidate which API endpoint to use as the source of truth for the product data. 

**cc:** @danielbeardsley, @mlahargou

**Comment by danielbeardsley** [comment]
>  Consolidate which API endpoint to use as the source of truth for the product data.

I thought you effectively did this while writing that test? i.e. changed this code to always use `shopifyQuantity - quantityInCart`

**Comment by danielbeardsley** [comment]
> In addition, it seems that Shopify and our DB are not synced up, then we will also have issues when adding a discounted product as the price in the cart will not match up.

Was that screenshot on iFixit.com? That looks like a bug. On cominor, prices can more easily be out of sync because we hand-edit products in shopify sometimes, and syncing more easily fails, but even then, it should be somewhat rare.

**Comment by mlahargou** [comment]
> Was that screenshot on iFixit.com?

This is a screenshot of local react-commerce. (http://localhost:3000/products/iphone-6s-plus-replacement-battery).

**Comment by ardelato** [comment]
> I thought you effectively did this while writing that test? i.e. changed this code to always use shopifyQuantity - quantityInCart

Yes, but that was simply to fix the inventory message on the product page. We still have a conflict in data between the product page and the cart drawer.

**Comment by mlahargou** [comment]
We create a mock userid (I think it's 1) in the test. I wonder if we are passing that mocked userid to the cart api so we are getting the price for the product of that real user on the cart api side (when viewing the product in the cart drawer)?

**Comment by danielbeardsley** [comment]
> We still have a conflict in data between the product page and the cart drawer.

The cart drawer will likely always source it's data from our php app as it's in control of and stores what's in your cart.

**Comment by dhmacs** [comment]
Just a few remarks:

- Prices must be in sync, because we're using the Shopify checkout, so we can't afford to not have them synced
- For the same reason inventory must be in sync
- As we improve caching, we will soon retrieve fresh details for inventory quantities with an additional client side query

**Comment by danielbeardsley** [comment]
Given that we'll always be getting some data from our shopping cart about products in the cart, (quantities and prices) there will always be this second data source.
