### ISSUE TITLE
Price discrepancy between parts collection page and product page

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#122]
### Description
This displayed product price on the collection page doesn't match the price on the product page.

### Steps to reproduce

1. Go to https://react-commerce-ifixit.vercel.app/store/parts
2. Click on the first procuct `MacBook Pro 13" (A2251, 2020) 2.3 GHz Logic Board with Paired Touch ID Sensor`
3. Check out the price of the linked product as compared with the price on the collection page.

### Images
Collection page ⬇️ 
![image](https://user-images.githubusercontent.com/72166715/140140870-b968dad1-a6d2-434d-a9e1-3194aa6bf784.png)

ifixit.com product page ⬇️ 
![image](https://user-images.githubusercontent.com/72166715/140143641-44330234-ba2b-4125-b099-76a6701727ca.png)

Found while testing: https://github.com/iFixit/react-commerce/pull/120

CC: @sterlinghirsh @dhmacs

**Comment by dhmacs** [comment]
This is the data from Algolia. One thing to be aware of, is that we are indexing variants, but we're displaying 1 single variant for each product. The deduplication is done by Algolia when using `distinct=true`.  This is necessary, otherwise we get back from Algolia a list of variants instead of a list of products.

![image](https://user-images.githubusercontent.com/4640135/140273783-033e8d7c-2e17-4afc-ad61-ab756b785f3a.png)

**Comment by erinemay** [comment]
Was able to repo this with the new index. 
![image](https://user-images.githubusercontent.com/72166715/159053863-2d327b69-7447-4c24-a139-ce859b168ec6.png)
For this product: https://www.ifixit.com/Store/Android/Galaxy-S7-Battery/IF329-023?o=4

Neither the fix kit or the part are 39.99. They are also both in stock.

**Comment by dhmacs** [comment]
We're currently using the `price` field, but I'm also noticing a `group_max_price` and `group_min_price`. How do all these price fields relate to each other? 

<img width="849" alt="image" src="https://user-images.githubusercontent.com/4640135/159066154-d80c5649-b394-4f0d-90fa-a3e7046d4158.png">

cc @sterlinghirsh

**Comment by jeffsnyder** [comment]
The first example given is still a problem. None of the Product Variants in Akeneo (live or Cominor) have that product at $1499.98 : 

![image](https://user-images.githubusercontent.com/7053450/159058909-89b02749-e58a-4661-b6ab-86ecc9200404.png)

The second example of a price disparity is a different problem. `Galaxy S7 Battery / Fix Kit v1` is a disabled product and should not be in the index. @erinemay is working on a separate issue to address that problem.

**Comment by erinemay** [comment]
Actually, @jeffsnyder, the first example is fixed now. 

I haven't been able to find a price discrepancy that wasn't due to disabled variant information being shown on the product cards. I've found some more examples, but they're all due to disabled variant info. 

I'm going to close this issue and https://github.com/iFixit/react-commerce/issues/219 in favor of the disabled product issue since they both appear to be symptoms of it. [WILL LINK ISSUE HERE]
