### ISSUE TITLE
Implement organization of "Choose a model" section on parts page

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#123]
### Description
There is no apparent organization of the model collection buttons on the /parts page. I would expect there to be some form of organization. 

(https://github.com/iFixit/react-commerce/pull/120#issuecomment-959769205)
>Another option is to have the most recent devices displayed first. This would required to add something like a releasedAt field in the product list collection type. This is something that needs to be defined

At the very least, these should be most popular models or somehow optimized for sales.

### Steps to reproduce
Go to https://react-commerce-ifixit.vercel.app/collections/parts and look at the choice of displayed model buttons.

### Images
![image](https://user-images.githubusercontent.com/72166715/140233404-7e09f0d9-da92-4900-93ef-29458ec6996a.png)

Found while testing: https://github.com/iFixit/react-commerce/pull/120

CC: @sterlinghirsh @dhmacs 

## Update

- [ ] Add `sortPriority` integer field to Strapi `ProductList` model
- [ ] Sort children first by `sortPriority`, then by alphabetical order

**Comment by dhmacs** [comment]
Maybe we can implement this with a `hierarchyPriority` integer field in the Product List model? Then that field can be updated according to whatever metrics you want. Thoughts @sterlinghirsh ?

**Comment by sterlinghirsh** [comment]
Sounds reasonable to me. I think `sortPriority` is a slightly clearer name, but I want to verify with @jstephens-ifixit that this makes sense.

**Comment by jstephens-ifixit** [comment]
Yes, I think having the model collection buttons sorted by some measure of popularity is a good idea. I'm not sure what that measure specifically would be, but that's likely to sort more recent models to the top of any given grouping. Specifically sorting newest devices first would probably have to be done manually and for a _very_ new device that is probably counterproductive for the period when there are few or no parts to offer. @jeffsnyder might have an opinion too.

**Comment by jeffsnyder** [comment]
Like with the similar conversation around sorting facets, we want a few key items at the top of the list, followed by an alphabetical list. 

In most collections contexts, we'll want 100% of those Child Device links to be sorted alphabetically. On a page like this, we'd have probably the first two rows with a sort override, followed by an alphabetical list. On the top of the tools sort, we'd have `iFixit Exclusives` and `Toolkits` first, then alphabetical.

**Comment by dhmacs** [comment]
Ok, I've updated the task description with todos 👍
