### ISSUE TITLE
Add scripts to help resolve conflicts

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1236]
## Description

We have some scripts in `iFixit/ifixit` to automatically resolve conflicts with `main`.

## To Do

Let's add some of these `quality of life` scripts to `react-commerce`.

**Comment by federicobadini** [comment]
Can you please point me to some examples of the scripts you are referring to?

**Comment by ardelato** [comment]
They are in the `iFixit/ifixit` repo which I am not sure if you have access to:
https://github.com/iFixit/ifixit/blob/master/Exec/rush-fix-lock-conflicts

The scripts mainly help resolve `rush`'s `repo-state.json` and `pnpm-lock.yaml` conflicts. However, after creating this issue, I found it easier to resolve conflicts in `react-commerce` then in `iFixit/ifixit` because we are not using `rush`.

That said, I no longer think it will benefit us to create a script to resolve `pnpm` conflicts so I will close this issue.
