### ISSUE TITLE
Parts page: Add tests

### ISSUE THREAD

**Issue by mlahargou** [iFixit/react-commerce#124]
I chatted with Erin today about what test cases we think should be added to the Parts page. We came up with a list of desired tests.  Many of these tests can probably use jest or something similar to run tests on the individual component. Most will probably require an E2E Cypress test.

We'd also like the QA team to bring up any other test cases that they see fit when manually testing this page.

https://react-commerce-git-collection-page-seo-improvements-ifixit.vercel.app/collections/parts

1) Filters
    - Click the filter title 
      - [x] Assert that the filter options are expended
    - Click a filter option 
      - [x] Assert that the filter was added to the current filter list
      - [x] Assert that the products update according to that filter
    - Click a different filter and option 
      - [x] Assert that both filters are in the current filter list
    - Add a descending price filter
      - [x] Assert that the proper warning is displayed
    - Add an ascending price filter
      - [x] Assert that the price filter is added to the current filter list
      - [x] Assert that the products displayed conform to the specific price filter
    - Click the x to remove a single filter
      - [x] Assert that the filter is removed from the current filter list
    - Click "Clear All"
      - [x] Assert that the remaining two filters are removed
2) Search
    - Search for a common word like "watch"
      - [x] Assert that the remaining products all conform to the search specification above
    - Search for a nonexistent word like "asdfasdfasdf"
      - [x] Assert that the "No results found" component is displayed
3) Grid/List view
    - Click the grid view button
      - [x] Assert that products are displayed as a grid view
    - Click the list view button
      - [x] Assert that products are displayed as a list view
4) Results view
    - Jest tests might be the best way to test these ProductCard components
    - Body
      - [x] Assert these are truncated to the desired length
      - [ ] Do we want a "show more" button?
    - Reviews
      - [ ] Ensure the stars component accurately "fills" the correct number of stars
      - [x] Ensure the number of reviews accurately displays the data that the component is provided
    - Price
      - [x] Ensure we display the price data the component is provided
    - View button
      - [x] Ensure the button directs the user to the link that the component was provided 

cc @davidrans @erinemay

**Comment by batbattur** [comment]
Added the grid/list view test in https://github.com/iFixit/react-commerce/pull/381.

**Comment by batbattur** [comment]
Added the search test in https://github.com/iFixit/react-commerce/pull/409.

**Comment by dhmacs** [comment]
@batbattur Yes I'm not working on this. Perhaps we should keep this has an epic issue and create the sub-issues for the todos so we can better coordinate team work 👍

**Comment by davidrans** [comment]
Nice work @batbattur!
