### ISSUE TITLE
Hide Hidden Product Reviews from Page Source

### ISSUE THREAD

**Issue by c00perdanny** [iFixit/react-commerce#1265]
We have logic that hides reviews on product pages, for products that meet certain criteria. 

However, the review data is still in the page source, and appears for search engines. For all product pages with hidden reviews, we still need to hide review data from the page source, so the reviews aren't shown in search engine results.

Example of issue:

[Anti-Clamp](https://www.ifixit.com/products/anti-clamp) has reviews hidden, but the reviews are still showing on the search engine Brave:

![image (5)](https://user-images.githubusercontent.com/66840433/213010008-41d8e026-1c19-467b-93f2-5f1440d160d1.png)

cc: @sterlinghirsh

**Comment by federicobadini** [comment]
Hi @c00perdanny
The only reference on the page is inside the `__NEXT_DATA__` script tag, which is the way in which server provided props are forwarded to the client. Those attributes however are not annotated in a way that helps the crawler to retrieve them.
For example these are the values for the Anti-clamp:

```json
"rating": { "scale_min": 1, "scale_max": 5, "value": 3.8 },
"reviewsCount": 10,
```

In my opinion it is very likely that the rating value that you are seeing was crawled before the review hiding logic was in place.
I say this also for two additional reasons:

- The rating value visible in the picture is significantly different from the one inside page data
- As far as I can see Brave is not showing rating anymore for that product. 

<img width="672" alt="Screenshot 2023-01-18 at 16 59 15" src="https://user-images.githubusercontent.com/7805759/213224735-fd3823f7-1c85-43e9-bff2-c2a4e4aea101.png">
