### ISSUE TITLE
Analytics: Add Cart Drawer Cross-Sell event

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1266]
Add 225 from our [event tracking spreadsheet](https://docs.google.com/spreadsheets/d/16Xas1pHf_K7FmfOX3yX2mYgeYr2DIENr8cyQp19FZkA/edit?pli=1#gid=1839136207&fvid=1843464925).

> Add to Cart Button for the upsell feature on the Mini Cart

![image](https://user-images.githubusercontent.com/10889879/213032295-2ae8ef7e-d0da-499c-9d72-89b0d5ce54ff.png)

![image](https://user-images.githubusercontent.com/72166715/213027347-13ce89f1-26ce-4197-af9d-2708665d9190.png)

cc: @addison-grant

**Comment by addison-grant** [comment]
CC @jeffsnyder

**Comment by jeffsnyder** [comment]
Sorry to be annoying. This is the "Cart Drawer" and it's a "Cross-sell" not an "upsell". 🤓 

@addison-grant will figure out the new event code we need.

**Comment by addison-grant** [comment]
I'm contacting our consultant about updating the event to say "Add to Cart - Cart Drawer" instead of "Add to Cart - Mini Cart," and I am also asking if we can add the term "Cross-Sell" into the event schema somehow.

**Comment by danielcliu-ifixit** [comment]
@jeffsnyder do we want both `Add to Cart - Cart Drawer` and `Add to Cart` events fired when we use the button in question, or just `Add to Cart - Cart Drawer`?

**Comment by addison-grant** [comment]
Updated 
```
Category:	Add to Cart - Cart Drawer
Action:	Add to Cart - Cart Drawer - $productcode-$optionid
Name:	{{PageUrl}}
```
Let me confirm, but I don't think we need a separate `Add to Cart` event

**Comment by jeffsnyder** [comment]
@addison-grant Correct, we should not fire two Add to Cart events for a single Add to Cart action.

**Comment by danielcliu-ifixit** [comment]
yep that should be how it behaves now
