### ISSUE TITLE
Change "checkout" to "check out"

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1267]
### Details
We use `Checkout`, the noun, on the react mini-cart, but we use `Check Out`, the verb (phrase??), on our php pages. 
Let's change the react mini-cart button to read `Check Out`.

![image](https://user-images.githubusercontent.com/72166715/213028204-5f8272b7-9ac4-427e-8c7c-3fa70a17e45e.png)

PHP pages:
https://www.ifixit.com/cart
![image](https://user-images.githubusercontent.com/72166715/213028809-7595be7e-b11d-4aed-b3b5-5aebd0fa8cea.png)

PHP mini-cart
![image](https://user-images.githubusercontent.com/72166715/213028828-c2efc68b-a47f-4f56-bb36-da986bd6fad2.png)

cc: @addison-grant

**Comment by addison-grant** [comment]
@jeffsnyder, John B pointed this out.
