### ISSUE TITLE
Featured Product Badge: Lifetime Warranty --> Lifetime Guarantee 

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1292]
Our `Lifetime Warranty` badge should read `Lifetime Guarantee`. We relabelled the Akeneo code from `Lifetime Garantee` to `Lifetime Warranty` some time ago and we want the text change to apply everywhere.

Badges on Featured Products don't match text in the banner. This juxtaposition makes the needed change very clear: 

![image](https://user-images.githubusercontent.com/7053450/214430485-b539e408-ee45-42de-99ff-89b2a1fa07fb.png)

Similarly, ProductList product cards need an update: 

![image](https://user-images.githubusercontent.com/7053450/214430558-afba8602-5d2f-4fb7-9a36-e41cf2a71d8c.png)

@sterlinghirsh anything I'm missing here or is this just a text change needed somewhere?

**Comment by sterlinghirsh** [comment]
Should just be a text change.
