### ISSUE TITLE
Implement sorting into Algolia hooks

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#13]
The collection page should have manual sorting and sorting by most popular products.
We need to implement the logic to switch index accordingly

**Comment by sterlinghirsh** [comment]
We discussed switching to a new Algolia app to take advantage of new engine features currently unavailable. Is that a blocker to this? Or would that be instead of this?

**Comment by dhmacs** [comment]
@sterlinghirsh this will certainly need to rely on the new stuff.. By the way we also need an Algolia index for each different sort order
