### ISSUE TITLE
Post Mortem 2023-01-27: 2 hours of downtime for some urls

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1310]
For about two hours, a decent portion of our /Parts and /Tools pages were 500ing because of a bad graphQL request to strapi.

Here's some notes that contributed to this failure:

* Sentry
   * Too much noise so that we ended up missing something critical (13,000 errors in an hour or two)
* Breaking change
   * Why wasn't this caught in QA?
   * Why wasn't this caught by Tests?
* Downtime: we didn't know that we were getting a huge amount of 500s from vercel
* Strapi in production hadn't been deployed to after #1157 was merged

CC @iFixit/shopify

**Comment by sterlinghirsh** [comment]
Make sure we redeploy / unrevert #1158

**Comment by federicobadini** [comment]
> * Why wasn't this caught in QA?
> * Why wasn't this caught by Tests?

I think this is kind of a soft spot because QA is interacting with Govinor and tests are running against an ad-hoc Strapi instance living inside the Github action itself.

Do we have any explicit reason why we have chosen not to redeploy Strapi in production by default on merge?

**Comment by masonmcelvain** [comment]
We have a (now closed) issue for it https://github.com/iFixit/ifixit/issues/42822. I don't think there was an explicit reason, manually deploying was the easiest path forward and hadn't caused any problems so far.

**Comment by sterlinghirsh** [comment]
Thanks for mentioned that issue @masonmcelvain . I reopened it. Strapi has been updated and the corresponding frontend code has now been deployed without issue.
