### ISSUE TITLE
Add ResizeObserver polyfill

### ISSUE THREAD

**Issue by federicobadini** [iFixit/react-commerce#1311]
Even though ResizeObserver support is [over 94%](https://caniuse.com/?search=resizeObserver), we have several users accessing iFixit using ~2019 Safari 13 devices with no support for it, see [here](https://sentry.io/organizations/ifixit/issues/3866479020/?project=6469069&query=is%3Aunresolved&referrer=issue-stream)

Add a polyfill to make ResizeObserver work on those devices

**Comment by sterlinghirsh** [comment]
https://ifixit.sentry.io/issues/4162083301/?project=6469069&query=is%3Aunresolved&referrer=issue-stream&stream_index=4 Looks like we're still getting errors about ResizeObserver, despite adding the polyfill. Not sure what that's about.

**Comment by federicobadini** [comment]
The ResizeObserver polyfill is present and working.
These errors seems to have low frequency (~3 errors/day) and they also seems misaligned with effective browser support.
ResizeObserver is officially supported [since Safari 13.1 and Safari iOS 13.4](https://caniuse.com/?search=resizeobserver) but this errors seems to trigger [only on newer Safari versions](https://ifixit.sentry.io/issues/4162083301/tags/browser/?project=6469069&referrer=tag-distribution-meter).

Those versions should have the ResizeObserver constructor available without the need of any polyfill.
The only thing I can suspect is that those are bots or devices with a wrong user agent signature. 

Polyfill.io inject libraries according to the spec visible in the user agent field. It could be the case that some device is advertising itself as a modern iOS device, thus causing it not to be polyfilled, but then it lacks the necessary support for ResizeObserver.

Given the low event rate I'm going to close this now.
Feel free to reopen if it starts happening more frequently.
