### ISSUE TITLE
Make tests more resilient

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1326]
## Description

In #1317 there was a small grammatical change that caused the tests to fail. https://github.com/iFixit/react-commerce/commit/4031350862efa7ef883f2a133e2af4ebbae51aa4

### To Do:

- [ ] Make the tests more resilient to changes like grammatical changes.

_Originally posted by @dhmacs in https://github.com/iFixit/react-commerce/issues/1317#issuecomment-1414465975_

**Comment by dhmacs** [comment]
In my opinion, we should prioritize testing areas that, if broken, could affect revenue. I don't believe testing copy is valuable and can result in additional maintenance costs.
For instance, tests for the "notify back in stock" form should validate two key functionalities:

- The ability for the user to interact with the form
- The ability for the user to submit the form successfully.

**Comment by mlahargou** [comment]
I agree, comparing strings here is not the best idea. I do, however, think it is important to verify the user's workflow. We should still ensure the div is visible, but we should do that based on the selector/class of the element, rather than the text on the element.
