### ISSUE TITLE
Pro product features for collections pages

### ISSUE THREAD

**Issue by shead2** [iFixit/react-commerce#134]
Collections pages need to denote when a product is "Pro Only" as well as show the Pro price to users logged in with a Pro discountid.

https://www.ifixit.com/Store/iPhone/iPhone-6/Screens
![Screen Shot 2021-11-18 at 1 04 29 PM](https://user-images.githubusercontent.com/10145051/142496760-6ace0273-70c2-4e5b-b005-7e2497657993.png)

Pros are denoted by a `discountid` of 13, 14, 15, 17 or 18 in `ifixit_cart.customers`

`reseller_pricing_enabled` (attributeid 49) in `ifixit_cart_attributes` denotes if Pros get a tiered price or a standard %

- If `reseller_pricing_enabled=1` then customers get the corresponding tiered price. `attributeid` 50, 51, 52 and 53 are the prices for each tier. 
- If `reseller_pricing_enabled=0` then customers get a standard % off according to `ifixit_cart.customer_discount`

**Comment by dhmacs** [comment]
Hi @shead2, first of all, is this requirement needed for v1 launch?

Currently the new product list page has no knowledge of whether the user is logged in (although I think I'll see that while implementing the navigation bar). 

In the new Algolia index there's a `is_pro` attribute that should help to identify a pro product. I think we're missing all the other details though? cc @sterlinghirsh @evannoronha 

Also, do you already have a plan on how this pricing will be handled by Shopify checkout?

**Comment by lithobraking** [comment]
@dhmacs 

The `product_en` Algolia index has a `price_tiers` attribute now:
<details>
<summary>Screenshot</summary>

![Screenshot from 2021-12-30 13-29-02](https://user-images.githubusercontent.com/34843669/147790687-e1f0c966-0bba-4242-9fab-12be5e143d55.png)

</details>

Does this work for moving forward on this?

**Comment by lithobraking** [comment]
@dhmacs 

The `product_en` Algolia index has a `price_tiers` attribute now:
<details>
<summary>Screenshot</summary>

![Screenshot from 2021-12-30 13-29-02](https://user-images.githubusercontent.com/34843669/147790687-e1f0c966-0bba-4242-9fab-12be5e143d55.png)

</details>

Does this work for moving forward on this, or does the spec need to be worked out some more?

**Comment by dhmacs** [comment]
@lithobraking I'll need to take some time to dig into this, because a few things might be affected by this (e.g. price filters)

**Comment by lithobraking** [comment]
@dhmacs All good, also I noticed I somehow double posted.

**Comment by dhmacs** [comment]
@kwiens told us that we can get rid of the price filter for pro users

**Comment by sterlinghirsh** [comment]
Not sure if it's been stated elsewhere, but to answer some questions for posterity:

> How do I detect if a user is pro? And how do I know what tier applies?

We added a discount_tier field on the user api, which will either be null, "employee", or the user's pro tier.

> Does "Pro only" means that only pro user can buy them?

Yes.

Not sure if this issue can be closed, but I seemed to recall that there were other issues covering this stuff.

**Comment by dhmacs** [comment]
@sterlinghirsh I'll close this when I have handled it.. Right now we're not showing pro prices
