### ISSUE TITLE
Sentry: Differentiate between client / server

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1345]
### Problem
Sentry is easy to ignore because it's full of infrequent browser-side problems caused by all manner of old browsers, extensions, and real bugs. The server-side errors are much more actionable and affect everyone and have been missed because of the noise of frontend errors.

### Do This
* Configure sentry (on sentry.io) to increase the threshold for Slack messages for browser-side errors, maybe 10x what it is for server-side?
* Establish some book-markable urls for saved searches for frontend vs backend errors and paste them here.

CC @iFixit/shopify

**Comment by masonmcelvain** [comment]
## Alerts

<details>
<summary>Before:</summary>

![image](https://user-images.githubusercontent.com/52104630/220484942-1c6a9c3f-a6ef-4a8a-89a1-8714a01ec101.png)
![image](https://user-images.githubusercontent.com/52104630/220485500-ec92cf20-b44c-491d-b2a3-5718a03afc4b.png)

</details>

<details>

<summary>After:</summary>

![image](https://user-images.githubusercontent.com/52104630/220487118-abe50975-ac5e-404e-bee0-7a6871dbd220.png)

</details>

## Links

Client errors in the last 24h, sorted by most events: https://ifixit.sentry.io/issues/?project=6469069&query=is%3Aunresolved+next.runtime%3Aclient&referrer=issue-list&sort=freq&statsPeriod=24h

Server errors in the last 24h, sorted by most events: https://ifixit.sentry.io/issues/?project=6469069&query=is%3Aunresolved+next.runtime%3Aserver&referrer=issue-list&sort=freq&statsPeriod=24h
