### ISSUE TITLE
Sort capacity facets accordingly

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#135]
Facets that contains capacity unit (e.g. gigabyte, kilobyte, etc) should be displayed from the lowest to the highest value

**Comment by dhmacs** [comment]
Waiting for the new index to have some facet with capacity units (e.g. GB of hard disk, etc)

cc @evannoronha @sterlinghirsh

**Comment by lithobraking** [comment]
@dhmacs ifixit#42475 should resolve the blocking factor on this.

**Comment by dhmacs** [comment]
Talking with @jeffsnyder this does not seem to be necessary anymore as we won't have capacity facets for the time being.. Let's reopen this if we change our mind

cc @sterlinghirsh @lithobraking

**Comment by jeffsnyder** [comment]
Sounds good 👍 

We will need to reopen this if/when we have the ability to show facets on select Collections + all child Collections.
