### ISSUE TITLE
Missing description in product video

### ISSUE THREAD

**Issue by federicobadini** [iFixit/react-commerce#1408]
[Search console](https://search.google.com/search-console/r/videos?resource_id=https%3A%2F%2Fwww.ifixit.com%2F&hl=en) is highlighting that some videos included in product page have a missing description.

This seems related to Vimeo videos only.
The iframe includes an `ld+json` with the video metadata.
Adding a description to the video on the Vimeo platform should solve the problem

cc @sterlinghirsh 

<img width="1432" alt="video" src="https://user-images.githubusercontent.com/7805759/221200569-4bcac54a-95d7-4b6b-ba89-745e80de618a.png">

**Comment by sterlinghirsh** [comment]
Slack ref: https://ifixit.slack.com/archives/C073KMDA9/p1677697125567619

**Comment by sterlinghirsh** [comment]
These are being fixed manually, so I'll close this issue.

**Comment by sterlinghirsh** [comment]
Update: All the reported videos owned by iFixit or Dozuki have been updated to include a description. There were 2 pages with videos owned by other accounts we don't control that probably won't be updated. We can just live with it or try to find some other solution like supplying a default somehow, but I don't know how much control we have over the embed.
