### ISSUE TITLE
Grid view XL productlist has empty grid items

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1422]
Scroll to the bottom of the page:
https://www.ifixit.com/Parts
![image](https://user-images.githubusercontent.com/72166715/222235793-4c843236-a989-400a-a061-1462ab6f7881.png)

Sorry, @federicobadini, I think I missed this in https://github.com/iFixit/react-commerce/pull/1376.

**Comment by federicobadini** [comment]
Good catch!
This is because we are now fetching 18 products per page.
Since the new version have 4 columns on `xl`, 3 on `lg` and 2 on smaller screen sizes, we have two options: fetching 12 products or 24 products per page.

Do you have any preference on this?

**Comment by erinemay** [comment]
Probably 24. @jeffsnyder do you have an opinion here?

**Comment by federicobadini** [comment]
In #1421 I've set it to 24 to solve the problem fast.
@jeffsnyder if you prefer 12 just let me know, it is just a matter of changing a parameter
