### ISSUE TITLE
Finish footer

### ISSUE THREAD

**Issue by lithobraking** [iFixit/react-commerce#143]
There are a couple of items that need to be added to the footer before it's complete:

- [ ] Partner logo grid

![Screen Shot 2021-11-29 at 11 55 17 AM](https://user-images.githubusercontent.com/34843669/143934619-c086f1c1-2059-4e96-b18f-4caebf124df9.png)

<strike>Language picker next to region picker</strike> **Just kidding this part's on ice, but the line item stays for the sake of record**

![Screen Shot 2021-11-29 at 12 06 51 PM](https://user-images.githubusercontent.com/34843669/143935365-175e4e46-07c9-4a19-a2fb-fe7f0a202272.png)

CC: @dhmacs

**Comment by dhmacs** [comment]
@lithobraking I think it was decided to postpone the language selector for later, since we're only going to have english when we launch

**Comment by lithobraking** [comment]
Right, we did discuss that. The issue has now been updated to reflect this 😅

**Comment by danielbeardsley** [comment]
I presume this has been talked to death, so sorry to jump in late in the game.

Why are we listing credit card companies as our "Partners"? Is this mandated by some relationships? Do we think this will give folks confidence? I think it may make sense to show some logos on the checkout page, but in the footer?

I just checked around and couldn't find another retailer that did this. Thoughts? Do @kwiens @davidrans or @jeffsnyder have opinions here?

**Comment by jeffsnyder** [comment]
@danielbeardsley we just want the ability to add logos to the footer: accelerated checkouts, payment methods, shipping options (particularly the green options), etc. We're not stating anywhere customer-facing that these are "Partners". I think that's just what we're calling this logo grid internally.

**Comment by dhmacs** [comment]
Can confirm, these are just images with links. There's also a spreadsheet on how to set them on the various stores

https://docs.google.com/spreadsheets/d/1yoTQqIFI2Fy4W9CfMnM5F0CjZ9YLAeK56yLyajE2Sj8/edit#gid=0

**Comment by danielbeardsley** [comment]
Fair... so it doesn't publicly say "Partners" but I still question why want to show logos of all the payment providers we support at the bottom of *every page* of our store.

Do we really think someone will be wondering "huh, if they don't support paypal, I'm outta here!" but then scroll down to the footer and change their mind?

While the design is clean looking, I just don't think that needs to be there. I'm not gonna die on this hill of course and I'm not gonna claim I have authority here, it just seems quite unnecessary. Every store supports these payment providers, none that I've seen have that info in their footer, so it's not something people go looking for.
