### ISSUE TITLE
Product Page Compatibility: Limit displayed model numbers per device by default

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1436]
## Problem
On highly compatible products like https://www.ifixit.com/products/frigidaire-241798231-ice-maker-assembly#compatibility, the list of model numbers per device becomes ridiculously long (thousands of lines). We still want to have all these numbers visible to Google, but it's a bad UX to have such a long list.

## Do This
Use css or a disclosure element like `<details>` or something to limit the display to the first 10 or so variants. When the list is truncated, include a link like "Show all 4528 models..." that expands the list for a single device. Still not the best, but it's an easy step in the right direction.

**Comment by dhmacs** [comment]
cc @mmarcon91 for a quick design iteration
