### ISSUE TITLE
Product Page Compatibility: Add simple model search

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1437]
## Problem
Along the lines of #1436, the list of model numbers on highly compatible products like https://www.ifixit.com/products/frigidaire-241798231-ice-maker-assembly#compatibility becomes ridiculously long (thousands of lines). We still want to have all these numbers visible to Google, but it's a bad UX to have such a long list. #1436 hides most of the model numbers, but it's still not great to make the user dig through thousands model numbers or rely on their browser search.

## Do This
Add a search bar at the top of the compatibility section that filters the displayed devices and model numbers. The search should update as the user types. It should rely on the data from the page without having to use Algolia or any external service.

Example:
Suppose we show a part compatible with 2 devices, each with 3 variants:
- Frigidaire Refrigerator
  - ABC123
  - ABC124
  - ABC245
- Electrolux Refrigerator
  - EFG345
  - EFG346
  - EABC123

Search terms should be matched in both the device and model. Searching "Frigidaire" should return the Frigidaire Refrigerator with all its variants, hiding the Electrolux Refrigerator. Searching "ABC" returns the Frigidaire with all its variants and the Electrolux with variant EABC123. Any hidden variants (hidden by the changes in #1436) should be shown, but we'll still want to limit to the first 10 matching variants per device unless the user decides to select the full list.

**Comment by dhmacs** [comment]
cc @mmarcon91 for a quick design iteration

**Comment by mmarcon91** [comment]
Mockup: https://www.figma.com/file/BolmFORO6ZfHXePOSyEGSS/iFixit---Page-sections?node-id=159%3A5560&t=KROIC6QB3HS4Rytj-4
