### ISSUE TITLE
Use new custom Algolia index

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#144]
Replace `shopify_ifixit_test_products` algolia index with the new `product_en` index

**Comment by dhmacs** [comment]
Hey @sterlinghirsh, how do I get the products that belong to a certain collection (e.g. "parts") ? I'm currently using the `collections` facet, but the new index doesn't seem to have one

**Comment by sterlinghirsh** [comment]
My intention was to use the `device` facet.

![image](https://user-images.githubusercontent.com/589425/144149091-b5c68c25-5ca1-493b-a415-30771e90785a.png)

Right now it only contains leaf-level devices, but we're working on changing it to include the higher level devices too. That corresponds to the deviceTitle field in Strapi. Our intention is to use the same device formatting as our device pages like https://www.ifixit.com/Device/iMac_Pro. Replace underscores in the url slug with spaces and `iMac_Pro` => `iMac Pro` and then search for that. Let me know if that works for you.

**Comment by dhmacs** [comment]
@sterlinghirsh that would work, but only for collections linked to a specific device or category... What if marketing team wants to create a "Blackfriday deals" product list? Or a "featured tools" product list? Product lists are a versatile concept, that can be used for many purposes, such as  grouping all products that belong to a promotion.. It's also useful that they are matched with a Shopify collections, so that it's easy to apply discount codes

**Comment by dhmacs** [comment]
It seems that `price_range` facet is also missing

**Comment by lithobraking** [comment]
@dhmacs @sterlinghirsh 

Does switching over to the `product_en` index break site functionality in a way that prevents us from using it and addressing these issues as we go along from there? Or is `product_en` currently still too incomplete to replace `shopify_ifixit_test_products`?

**Comment by dhmacs** [comment]
For what concern the product list page there a few things that might be affected, like the price range filter.. There's some work to be done to make it work with the new index

**Comment by lithobraking** [comment]
@dhmacs 

What's everything that's still missing before you'll be able to add it in? I'd like to compile a list so I can make a more detailed spec surrounding this.

**Comment by dhmacs** [comment]
@lithobraking 

Here's a few assumptions based on previous discussions:

1. We'll group products by product lists using the `Device` facet according to this [comment](https://github.com/iFixit/react-commerce/issues/144#issuecomment-983162320)
2. Custom product lists (e.g. "black friday deals") we'll be created by providing custom Algolia filters in the Strapi product list (currently this works with raw Algolia syntax, might not be the best editing experience for marketing staff)

## Things missing / to be clarified

- How do we create `parts` and `tools` root product lists? I can't find a facet that would help me make the distinction
- `price_range` facet is missing, it should be set like this:
  ![image](https://user-images.githubusercontent.com/4640135/148593997-c199130c-69a6-476c-9cd6-8fa092b857c5.png)
- Product list `handle` in **Strapi** are like this `imac-pro-emc-3144` but if we need to use a sluggified version according to assumption (1) then they need to be updated to something like `iMac_Pro`
- `inventory_quantity` is missing

**Comment by sterlinghirsh** [comment]
Looks like we need to make some updates to our algolia index to fix a couple issues.
* We will have a facet that indicates part or tool. Right now this is in search_tags but we'll move it to facet_tags soon. It will be `facet_tags.Main Category` and will be either Parts or Tools. I didn't realize having it in search_tags would prevent us from specifically filtering on it.
* We will add price_range too. I imagine we'll have to also add price ranges for each pro tier too.
* Yes we will get the Device / slug thing worked out.
* We will add inventory_quantity. We haven't included this in algolia in the past, so we might need to spend a while tweaking it to get it to update regularly enough but we can get something included.

**Comment by dhmacs** [comment]
@sterlinghirsh 

> * I imagine we'll have to also add price ranges for each pro tier too.

According to our last meeting Kyle told us that we can hide `price_range` for pro users

**Comment by sterlinghirsh** [comment]
Oh yeah, true.

**Comment by dhmacs** [comment]
@sterlinghirsh I checked the `product_en` index, and these 3 points are missing:

> * `price_range` facet is missing, it should be set like this:
>   ![image](https://user-images.githubusercontent.com/4640135/148593997-c199130c-69a6-476c-9cd6-8fa092b857c5.png)
> * Product list `handle` in **Strapi** are like this `imac-pro-emc-3144` but if we need to use a sluggified version according to assumption (1) then they need to be updated to something like `iMac_Pro`
> * `inventory_quantity` is missing

**Comment by dhmacs** [comment]
@sterlinghirsh @lithobraking it seems that `price_range` and `quantity_available` are there, but neither of these are set as facets, so I can't use them as filters. It's useful also for `quantity_available` to be a facet, so that we can filter out sold out products if we want (there is a use case where I need this)
