### ISSUE TITLE
Improve __NEXT_DATA__ for product pages

### ISSUE THREAD

**Issue by federicobadini** [iFixit/react-commerce#1443]
This is an analysis of html node sizes for a page with just one product variant.

<img width="1488" alt="Screenshot 2023-03-07 at 09 29 59" src="https://user-images.githubusercontent.com/7805759/223376460-39541adb-7ef1-40f3-8d89-b551a6c2d515.png">

As the number of variant increases the `__NEXT_DATA__` json becomes the predominant element of the page

<img width="1513" alt="Screenshot 2023-03-07 at 09 30 20" src="https://user-images.githubusercontent.com/7805759/223376515-bb18d658-6050-4e58-8aae-70a6aee33d28.png">

We can note two things here: 

1. We are almost duplicating data to provide `variants` and `allVariants` as well as `images` and `allImages`
2. By looking inside either `variants` or `allVariants` we can notice that each element contains its related crossSellVariants with all their details. This means that when a high number of variants shares the same cross sell recommendation we are repeating the same data over and over.

<img width="762" alt="Screenshot 2023-03-07 at 10 13 42" src="https://user-images.githubusercontent.com/7805759/223377024-82b21880-a5c2-44a8-b2b8-8f9977889936.png">

The need to have both the `variants` and the associated `allVariants` property may be substituted via a flag that defines which variant are active and which ones are not.
The relation between a variant and its associated crossSell recommendations could be done via id, allowing to keep the list of cross sell products in a separate place without any duplicate

connects https://github.com/iFixit/react-commerce/pull/1092#issuecomment-1455270179

**Comment by danielbeardsley** [comment]
I'm excited about this! I'm glad it's measurable and that we have some TODOs.
