### ISSUE TITLE
Descender in g cut off

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1493]
![image](https://user-images.githubusercontent.com/589425/226724903-ae755269-b52d-4612-a32f-975653cb41e4.png)

Example page: https://www.ifixit.com/Parts/Android_Phone

The descender in the lowercase `g` goes below the baseline and is cut off. Removing `overflow: hidden` fixes it:
![image](https://user-images.githubusercontent.com/589425/226725757-f21b4288-41a3-4f57-9231-55993e74f709.png)
However, this may cause problems with long text. I'm not sure if that's a real issue.

Alternatively, removing the line-height on the containing element also fixes it, but makes the badge taller:
![image](https://user-images.githubusercontent.com/589425/226726475-f0bbafd5-d6f5-4c1c-8242-73313cef09e1.png)

I think I prefer keeping the badge the same height if possible. @mmarcon91

**Comment by mmarcon91** [comment]
I think we could remove the `line-height` property and leave it as the default. Change the `padding-y` from `4px` to `2px`, so that should solve it.
