### ISSUE TITLE
Make Product Reviews Editable on Product Pages

### ISSUE THREAD

**Issue by c00perdanny** [iFixit/react-commerce#1500]
**Problem:**

Product Pages used to have a feature where iFixit staff could edit product reviews, but it is missing on the new react pages.

Mako example: https://www.ifixit.com/products/mako-driver-kit-64-precision-bits

![Mako Driver Kit_ Precision Screwdriver Bit Set for Phone, Computer](https://user-images.githubusercontent.com/66840433/227389508-e5e5555b-e539-4a6a-b49f-36a944e4e117.png)

**Do this:**

Make reviews editable on React product pages. This involves adding an edit link to each review when the logged in user is an admin. The link should follow the same pattern as on the PTT page, i.e. to `https://www.ifixit.com/User/Reviews/IF145-307-4?userid=<userid of reviewer>`

As a reference for how the react pages should look, the special Pro Tech Toolkit and Manta Driver Kit pages still have editable reviews:

Pro Tech Toolkit example: https://www.ifixit.com/Store/Tools/Pro-Tech-Toolkit/IF145-307

![Pro Tech Toolkit_ Precision Tools for Phone, Computer Repair (1)](https://user-images.githubusercontent.com/66840433/227389526-948c1491-2d2a-4ceb-803e-30fce1a25dca.png)

cc: @jeffsnyder @sterlinghirsh

**Comment by c00perdanny** [comment]
@danielbeardsley This feature is not working properly. The "Edit" button should link to the variant that the reviewer bought, not link to the variant that is selected on the page by a prospective customer. 

Click edit on reviews [here ](https://www.ifixit.com/products/repair-business-toolkit)as an example

**Comment by danielbeardsley** [comment]
@sumukhipandey --- Looks like we'll need to add the sku to the API here: https://github.com/iFixit/ifixit/blob/master/Guide/Libs/GuideAPILib_2_0.php#L484-L502

And then use it in reac-commerce.

**Comment by c00perdanny** [comment]
@deltuh-vee This got closed, but the issue is still ongoing. The "Edit" link does not take me to the specific review.

**Comment by danielbeardsley** [comment]
Can confirm, this doesn't work in the way I'd expect..

Clicking "Edit" on a review takes you to a url like:
https://www.ifixit.com/User/Reviews/1450021?userid=36905

Which looks like this:
![image](https://github.com/iFixit/react-commerce/assets/26855/34fabcf4-648e-4090-ab93-e95d848bb6f6)

Honestly.. I have no idea what's going on with that page. It seems like it's just showing a random collection of products. Maybe it's products that haven't been reviewed by *that* person?

**Comment by danielcliu-ifixit** [comment]
@danielbeardsley @c00perdanny it sounds like github webhooks are busted rn and it didn't deploy my code change. My code change fixes the bug
