### ISSUE TITLE
Implement workbench

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#151]

**Comment by dhmacs** [comment]
This is being worked on by @hcutrone and the work is being tracked in the iFixit repo, so I'm gonna close this

**Comment by hcutrone** [comment]
I could be wrong, but I thought this issue was adding the Workbench dropdown to the react-commerce header? If that's the case, I have not been working on that.

**Comment by dhmacs** [comment]
Tracking this on https://github.com/iFixit/ifixit/issues/50482
