### ISSUE TITLE
Caching api optimizations

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1523]
We might be able to make some slight optimizations to the caching system. Right now, we have a baseline 50ms delay on any page that triggers a recache. This is because we make an http request to https://www.ifixit.com/api/nextjs/cache/product, but if the serverless function completes before the request is made, the cache is never refreshed.

50ms isn't too bad, but we might still be able to do better. There might be a library for this, but if not, we could replace our use of `fetch` with a lower level `http` call. https://nodejs.org/api/http.html#httprequesturl-options-callback

```js
new Promise((resolve, reject) => {
   http.request(...).end(resolve).on('error', reject);
})
```

I haven't tried it, but I think this should be able to make the request and finish posting without waiting for a response, though we'll have to try it to be sure. Might have to put a call to destroy() in there somewhere.

The second idea was instead of requesting from https://www.ifixit.com which will go through CloudFront, we might be able to request from the actual vercel domain to avoid the extra round-trips to CloudFront. It's probably a small improvement, but since it will be on so many pages, it might be good to do anyway.

**Comment by sterlinghirsh** [comment]
Yes sorry I wasn't more clear. I understand the point of the 50ms. What I'm proposing is that by using the http api instead of fetch, we can send a request without waiting for a response. I might be reading the docs on `http.request(...).end(callback)` wrong, but it looked like it would complete flushing the request without waiting for a response, then call the callback. If that's the case, then that would probably let us wait no longer than necessary to fire and forget a post. I'm sure it's still a few ms, but probably less than 50.

**Comment by sterlinghirsh** [comment]
The second part was that if we are no longer limited to a minimum of 50ms, then we could shave off the extra roundtrip time from vercel to cloudfront and back by not going to www.ifixit.com anymore.

**Comment by dhmacs** [comment]
> without waiting for a response

This is the part I'm not understanding. What do you mean by "waiting for a response" ?
The current implementation is not waiting for a response either:

```ts
   const requestRevalidation = async (variables: z.infer<VariablesSchema>) => {
      fetch(`${APP_ORIGIN}/${endpoint}`, {
         method: 'POST',
         body: JSON.stringify(variables),
      }).catch((error) => {
         logger.error(
            `${endpoint}.error: failed to trigger revalidation\n${printError(
               error
            )}`
         );
      });
      // We add a small delay to ensure the revalidation is triggered
      await sleep(50);
   };
```

The `fetch` has no `await` so the function keeps going on and does not wait a fetch response. Also, the response from that endpoint would take quite a while to come back if it was actually awaited ( > 1s ) because it performs the revalidation before sending back a response.

**Comment by sterlinghirsh** [comment]
I realize we don't wait for a response now, but we do wait for 50ms. That 50ms is just "an amount of time in which the request will almost certainly be sent". I'm wondering if instead of picking a flat 50ms, maybe we can let the http module tell us when the request is finished. I'll try to put together an example since I don't think it'll be that complicated and it should be obvious right away if it works or not.

**Comment by dhmacs** [comment]
Oh now I see, I didn't realize that `.end(resolve)` might actually just give you a hook for when the request has been sent. Great idea! I'm curious to see if it works 👍 

We might still want to retain the 50ms cutoff if the request takes longer than that to be sent (to make sure we're not making the current request waiting too much on revalidation)
