### ISSUE TITLE
Filter bar doesn't scroll to newly shown facet details

### ISSUE THREAD

**Issue by JFleischhauer** [iFixit/react-commerce#155]
## Problem
Open the bottom filter “Watt hours (wh)” here: 
https://react-commerce-git-add-header-navigation-ifixit.vercel.app/collections/parts
It’s not visible that the filter was extended until you scroll down.

**Comment by erinemay** [comment]
Referring to this behavior:

https://user-images.githubusercontent.com/72166715/183777646-b0798710-8f75-408e-90f5-1c77cc353340.mp4
