### ISSUE TITLE
Strapi image auto-resize or use next

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#1560]
We are serving full-size images from strapi. We should figure out whether we want to keep doing that, auto-resize images on strapi upload, or route through next. We had some gigantic images on the repair business toolkit.

**Comment by sterlinghirsh** [comment]
IIRC we had some performance concerns about using next's image processing without a system to retain the resultant images long-term.

**Comment by danielbeardsley** [comment]
I think you're right. But given that there are just far fewer images in strapi and we have cloudfront caching in front if it, I'm less worried.
