### ISSUE TITLE
Setup page template to be used for multiple pages

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#1594]
Currently page template is tied to the `/store` path. We'd like to make the path configurable through Strapi.

**Comment by dhmacs** [comment]
In order to be able to use the page template beyond the store home page, we need to create a [catch all route](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes) (e.g. `[...slug].js`) which based on the slug will grab the page data from Strapi. 
This will break Next links for paths served by PHP pages, because with a catch all route, every route can be served by Next.js so Next Link can't tell if it needs a full page reload or not.

By looking at our production Strapi, I came up with an idea. I saw that we're using relative paths for internal Next.js links, and absolute paths for php pages. I'm proposing to create a custom link component that uses a Next.js link for relative paths, and a normal link for absolute paths. This way we can have catch all routes, and still link to php pages without issues.
This new link component will also come handy when we migrate to Next.js 13, since the link component will have some breaking changes that we'll need to address.
Thoughts?

cc @sterlinghirsh

**Comment by sterlinghirsh** [comment]
I think this will work, though I'm concerned that it's a very subtle difference. We're going to depend on the CloudFront routing heavily here since we'll have a catchall route in both nextjs and php. I don't have a better suggestion though.

**Comment by dhmacs** [comment]
I agree, I think for the time being we're going to keep whitelisting paths on Cloudfront as we add more stuff to Next.js, but at least this paves the way for creating pages without requiring dev work on the Next.js part. I'll work on opening a PR to refactor links
