### ISSUE TITLE
Store home page design review

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#1616]
Review and polish the store home page to be ready to ship

**Comment by jeffsnyder** [comment]
As discussed: 

Let's manage this text in a new field. One line that gets broken. No rich text. Let's manage it on the Page > Browse > Categories.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/7053450/234917722-6523b155-3b06-4c47-95bd-55c97c8c2b72.png">
