### ISSUE TITLE
Product List URL spec

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#163]
**Store Home**
/Store

**Parts and Tools pages**
/Store/Parts
/Store/Tools

**Tool Category**
https://www.ifixit.com/Store/Tools/Cutting

**Parts for Device**
 * Device: https://www.ifixit.com/Device/MacBook_Pro_15%22_Unibody_Late_2011
 * New Product List: https://www.ifixit.com/Store/Parts/MacBook_Pro_15%22_Unibody_Late_2011
   * Note the device slug matches across /Device and /Store/Parts. This will come from Strapi's deviceTitle field.
 * Old Product List: https://www.ifixit.com/Store/Mac/MacBook-Pro-15%22-Unibody-Late-2011
   * Note that this uses /Store/Mac instead of /Store/Parts
 
**Product URL**
https://www.ifixit.com/Store/Mac/MacBook-Pro-15-Inch-Unibody-Early-2011-Mid-2012-Battery/IF161-107?o=3
Note that this uses /Store/Mac but it would work just as well with /Store/Parts. The important pieces is the final slug `IF161-107` which is what we actually use to decide which part to display. This won't conflict with a product list since it has 4 slugs instead of 3.

**Comment by dhmacs** [comment]
@sterlinghirsh I'll look up at what needs to change, but probably should be an easy change.
Do we still want to keep capitalized path segments ?

**Comment by sterlinghirsh** [comment]
Yeah I think capitalized path segments make sense since they match the rest of the site.
