### ISSUE TITLE
Playwright Fix Flaky Tests

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1639]
## Description

This was pointed out in https://github.com/iFixit/react-commerce/pull/1634#issuecomment-1531669780. Overall the Playwright CI check did not pass because it exceeded the allowed runtime of `15 minutes`. After re-running the CI check passed.

The reason why it exceeded the time limit on the first run seems to be a result of retrying multiple failed tests. As a result, we can potentially run 50+ tests instead of about 39 tests because of the retries.

### To Do

- [ ] Find and deflake the Playwright tests

**Comment by mlahargou** [comment]
Let's try to figure out how often we hit the 15 minute timeout. If it happens a couple times per week, I'm not worried. If it happens more than that, let's dig into it.
