### ISSUE TITLE
Post Mortem: Blank page on all react commerce after user api change

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1653]
After pull #1340 was merged and before a fix was deployed (#1652) return visitors that were logged in would end up seeing a nearly blank page with a message about a client side exception preventing rendering. After refreshing the page, the error went away.

This has prompted several questions:

* [x] #1654
* [x] #1655
  * Can we made an error limited to just one component?
* [x] #1656
  * mimicing how we do this for redis caching on the server-side

CC @iFixit/shopify

**Comment by mlahargou** [comment]
We might be able to catch these types of things with the DataDog Lighthouse tool: https://github.com/iFixit/ifixit/issues/47474

**Comment by danielbeardsley** [comment]
> We might be able to catch these types of things with the DataDog Lighthouse tool

Not *this* particular error as it happened because in-browser `localStorage` caching, which I doubt they preserve between runs. Also, it was only happening with logged in users.
