### ISSUE TITLE
Ensure client side errors in components show up in sentry

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1654]
From Post-Mortem: #1653

A client side exception was causing blank pages for some users and yet the errors did not show up in sentry. We didn't find out about it until members of our dev team saw it and let us know.

Specfically, `user.data.teams` was undefined and thus calling `.length` threw an exception:
https://github.com/iFixit/react-commerce/blob/11d654df11d30da2f537704e1e322c3bc0e7217c/frontend/layouts/default/index.tsx#L405-L409

**Comment by danielbeardsley** [comment]
We think we've found when the problem (not reporting errors) was introduced:
https://github.com/iFixit/react-commerce/pull/1336/files#diff-e064de65d4610383e665a32e7e32ee1f520c466a6a63ecea8925ff8337f08215L57

**Comment by dhmacs** [comment]
> We think we've found when the problem (not reporting errors) was introduced

@danielbeardsley what about this PR broke error reporting?

**Comment by dhmacs** [comment]
Oh wow I saw it, it was the fact that I should have refactored `SENTRY_DSN` to `NEXT_PUBLIC_SENTRY_DSN` for it to keep working the same way 😬
