### ISSUE TITLE
localStorage: Can we do zod schema validation on value when they come out of cache?

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1656]
From Post-Mortem: #1653

### Problem
We cached user data in local storage. The schema changed, the cached values didn't match the new schema, but we don't do validation, so the result was an exception when our components used the data. The exception caused a blank page until you refreshed

### Do This
It's a good idea to make a similar schema-validating cache layer for localStorage so that changing the schema will invalidate the cache and we won't have to remember to bump a cache key.

Definitely add validation. Maybe implement a custom solution instead of zod if the bundle size increase is significant.

**Comment by dhmacs** [comment]
I think using Zod is a great idea, the only cons that I can think of is that this way we'll commit ourselves to keep zod in the client side JS bundle.

**Comment by danielbeardsley** [comment]
> keep zod in the client side JS bundle.

Good point :-(

13KB is not trivial: but it may be worth it:

https://bundlephobia.com/package/zod@3.21.4

Maybe treeshaking will mean it actually ends up as less JS :shrug:
