### ISSUE TITLE
Package.json allows Node 14+ which conflicts with Strapi dependencies

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#166]
## Description

While testing #164 I noticed the following warnings being outputted. I am currently using `node 16` by default.

![Strapi node version 14](https://user-images.githubusercontent.com/22064420/152213757-4de1ab51-4887-42dc-bc73-5adff0f13592.png)

It seems in our root `package.json` we are restricting the node version to **v14+**  
https://github.com/iFixit/react-commerce/blob/03c804c1d71f40af6820daa45092522dece007c6/package.json#L6-L8

However, `strapi` is restricting their node version to **v10-14**

![Strapi Node Version](https://user-images.githubusercontent.com/22064420/152214628-91f2cdd9-3439-49f2-9385-7c40bd7faed5.png)

----

<br/> 

We actually do align our node version restrictions with `strapi` in the `backend` package.json https://github.com/iFixit/react-commerce/blob/2a0b6f178103be91c3bbc3343d0912bb2866f13a/backend/package.json#L36-L38

I would assume that we should also restrict our node version to just **v14** in the root package.json as well. However, I am not sure if that is best solution.

**Comment by dhmacs** [comment]
@ardelato if you use nvm you can just do `nvm use` in the project root directory and it will automatically pick the v14 as specified in the [`.nvmrc`](https://github.com/iFixit/react-commerce/blob/main/.nvmrc).
I should probably mention that in the readme

**Comment by ardelato** [comment]
Ahh gotcha! We should definitely mention the use of `node version 14` or `nvm use` in the README, since that information is currently siloed in Pulls.

**Comment by sterlinghirsh** [comment]
I don't think this is still an issue, but feel free to reopen this if I'm wrong.
