### ISSUE TITLE
Replace `useLayoutEffect` with `useIsomorphicLayoutEffect` in breadcrumbs package

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#1678]
#1586 introduced a React warning:

![Screenshot 2023-05-12 at 11 11 57](https://github.com/iFixit/react-commerce/assets/4640135/8eb95d69-d586-45d4-84a0-51cb01ba41ee)

## Do this

Replace `useLayoutEffect` with `useIsomorphicLayoutEffect` from `@ifixit/ui`

cc @andyg0808 It's an easy change, but I don't know if importing from `@ifixit/ui` would impact the usage of breadcrumbs in php

**Comment by andyg0808** [comment]
Here's the component @dhmacs is sugggesting:
https://github.com/iFixit/react-commerce/blob/6cc2e08bd6591226595e807819457f3bb4a51a82/packages/ui/hooks/index.ts#L64-L65

It looks like it's about the same code as https://usehooks-ts.com/react-hook/use-isomorphic-layout-effect.

**Comment by ianrohde** [comment]
cc @rickisXP to bring in the loop

**Comment by danielbeardsley** [comment]
I fixed this in a recent pull:  9e7f43ee7d5d341f741a56220823eb0d7d674c96
