### ISSUE TITLE
Implement store home page

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#169]
- [ ] Add support for Valkyrie banners
- [x] #272

**Comment by jeffsnyder** [comment]
@dhmacs when we merge Store Home, we'll be replacing the ProductList banner feature with the Store Home banner features, right? (I think we discussed this in person but I don't see anything in GitHub.)

**Comment by dhmacs** [comment]
@jeffsnyder you mean enabling the capability of using the same banner across multiple product lists?

**Comment by dhmacs** [comment]
@jeffsnyder work on the home page has been de-prioritized to work on the product page. When I'll get back to it I'll update also the logic for product lists 👍
