### ISSUE TITLE
Item type categories 404ing on custom pages

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1696]
## Description
https://www.ifixit.com/Shop/Spring_Yard_Sale works 
https://www.ifixit.com/Shop/Spring_Yard_Sale/Batteries flashes results briefly, then 404s

Alternate ux from @ianrohde: See brief flash of 404 then the page loads. Click on another item type and see the 404 persist. 

Issue is not happening for regular collections in the hierarchy https://www.ifixit.com/Parts/Tablet/Buttons.

**Comment by masonmcelvain** [comment]
Slack convo for posterity: https://ifixit.slack.com/archives/C01GMQXJC95/p1684778072873099
