### ISSUE TITLE
Create Tests for `/Shop` page

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#1701]
## Description

https://ifixit.slack.com/archives/C01GMQXJC95/p1684783230019769?thread_ts=1684778072.873099&cid=C01GMQXJC95

We'd like a smoke test for marketing pages (i.e. urls like `/Shop/*`). We want to make sure this kind of page can render when it exists in Strapi, and that users can navigate its products.

### Specs:

- Should behave like the `/Parts` and `/Tools` pages
- Item type facets should be buttons, not links. Item types should end up as query parameters, not as the url slug (e.g. `/Shop/Spring_Yard_Sale/Batteries` is wrong)

**Comment by mlahargou** [comment]
https://www.ifixit.com/Shop/Spring_Yard_Sale
