### ISSUE TITLE
CI: Figure out how much we should be spending on Actions

### ISSUE THREAD

**Issue by mlahargou** [iFixit/react-commerce#1710]
We will be moving react-commerce into the ifixit monorepo. We don't know
yet if we will be self-hosting the tests or running them on github hosted
runners. 

Let's figure out how much it would cost if we decided to run these
tests on github hosted runners. Datadog might be helpful here.

cc @ardelato

**Comment by ardelato** [comment]
https://app.datadoghq.com/notebook/5656966/react-commerce-times?range=2678400000&start=1682963766060&live=true

Based on the prior month we are looking at around $70/month for extra minutes.

![image](https://github.com/iFixit/react-commerce/assets/22064420/093149cb-3630-44e2-9f6c-0a439db5bb53)
