### ISSUE TITLE
Add mini cart

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#172]
Implement new mini cart drawer according to the [mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit-Shopify-Working-Files?node-id=3156%3A23831)

## Resources

- [Reference implementation currently being used](https://github.com/iFixit/ifixit/blob/master/carpenter-frontend/Shared/shopify_checkout.js)

**Comment by dhmacs** [comment]
@sterlinghirsh I have a few questions about some details of the pro checkout:

1. How can I obtain `App.shopifyCheckout.ssoRoute`? https://github.com/iFixit/ifixit/blob/master/carpenter-frontend/Shared/shopify_checkout.js#L135
2. Do we have to do [this validation](https://github.com/iFixit/ifixit/blob/master/carpenter-frontend/Shared/shopify_checkout.js#L155-L168)? What’s the scenario that this is trying to cover? 
3. I’d like to precompute the checkout url ahead of time so that checkout is faster. I’d use `react-query` for this, and that means that every time the tab of the browser refocus, it’ll make a request to that endpoint to get fresh data. If the `cart/order/draftOrder` API is called multiple times, is it an issue?

**Comment by sterlinghirsh** [comment]
1. ssoRoute be "https://www.ifixit.com/User/sso/shopify/ifixit-us?checkout=1" on the live site and "https://www.cominor.com/User/sso/shopify/ifixit-test?checkout=1"
2. This was set up to cover the case when we had items for sale in our store that hadn't been pushed to Shopify. It shouldn't come up in practice. It was causing an error response from the Shopify api that was opaque to users. We can probably skip it at this point.
3. Right now, we only hit the draftOrder api when we initiate checkout. It would definitely be faster for the customer if we created a draft order ahead of time, maybe when something is added to the cart. Ideally, we shouldn't create a new draft order every time, though. We could cache the draft order with the cart and only update it when necessary, but it will take some rework on our side to make that work. I'd say for now keep it as-is (only hit draftOrder api when initiating checkout) and we can leave that as a future optimization.

**Comment by dhmacs** [comment]
@sterlinghirsh there's a conflict that we need to resolve about which API we want to use in our staging preview links (`ifixit.com` or `cominor.com`).

Right now we're using `ifixit.com`, and the reason we're doing this is that we need to fetch device images server side, thus if we do it with cominor we're blocked by cominor auth system (Vercel has dynamic IPs, so we can't whitelist based on that). 
On the other hand, this causes issues with fetching user details and checkout, since `ifixit.com` is far less permissive than cominor.

Ideally I'd like to use cominor for staging previews, but the auth system prevents us from doing that. Any idea how we can overcome this?

**Comment by sterlinghirsh** [comment]
Yeah, we should be able to whitelist based on the path of the api.
