### ISSUE TITLE
Renovate: Get it working in react-commerce

### ISSUE THREAD

**Issue by batbattur** [iFixit/react-commerce#1727]
## Description
Once we move `react-commerce` to the monorepo, renovate might stop working if it runs into any dependency issues from react-commerce. Thus, let's get renovate working in `react-commerce` and resolve any errors or issues if they exist.

## Do this
- Use the renovate config from `iFixit/ifixit`, and then modify it to work in `react-commerce`.
- Fix any outstanding issues.  

## Background
We've run into a couple of issues when trying to setup renovate in `ifixit/iFixit`, for example: https://github.com/iFixit/ifixit/issues/47428, https://github.com/iFixit/ifixit/pull/47558.

**Comment by mlahargou** [comment]
I think we are working along on pulling react-commerce into the monorepo. I worry that any work here might just not work once we pull it into the monorepo.

**Comment by batbattur** [comment]
Yeah, I can see that happening. Maybe we should close this and address the potential issues once we merge them to not duplicate work.

**Comment by batbattur** [comment]
Going to close this for now then.
