### ISSUE TITLE
Facet UX: hiding facets when result-count = 1 seems like a bug

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#1728]
### Problem:
1. Visit https://www.ifixit.com/Parts/Android_Tablet
2. Click "Accessories"
3. You get this:
![image](https://github.com/iFixit/react-commerce/assets/26855/2e1169db-cf74-4080-bec1-4d20bec7d176)
4. Click "Adhesives"
5. Expectation broken, the facet panel disappears:
![image](https://github.com/iFixit/react-commerce/assets/26855/c21f48bc-334d-41fc-b0b4-940e85491a00)

We did this on purpose... but it sure feels like a bug because the other facets allow you to unselect them, or choose a different facet after clicking. If it has only one result, you can't change them because the facets disappear.

**Comment by masonmcelvain** [comment]
Slack thread: https://ifixit.slack.com/archives/C0252FETV2S/p1685470430354089

My 2 cents: we should keep showing a component to deselect refinements if there are active refinements.
