### ISSUE TITLE
Store Home Page: search store facet

### ISSUE THREAD

**Issue by davidrans** [iFixit/react-commerce#1741]
Searching via the search bar on the new Store Home should probably search only parts/tools (i.e. Store tab):
![image](https://github.com/iFixit/react-commerce/assets/806152/073328e5-009b-4410-b526-d0c20199c902)

Currently, it goes to: https://www.ifixit.com/Search?query=pro+tech but should instead go to https://www.ifixit.com/Search?doctype=product&query=pro%20tech

**Comment by masonmcelvain** [comment]
This behavior was present on the legacy store homepage

[Screencast from 2023-06-07 13-52-21.webm](https://github.com/iFixit/react-commerce/assets/52104630/2b6b1909-242a-423b-a52c-967f999517a5)
