### ISSUE TITLE
Store Home: Don't drop text from ProductList section on Mobile

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1747]
This category description on Store Home:

![image](https://github.com/iFixit/react-commerce/assets/7053450/e9ad48ba-0f72-45f4-b354-273b8d841071)

Shows up if the window is wide enough: 
![image](https://github.com/iFixit/react-commerce/assets/7053450/702b9a30-ddf7-4409-97c4-1067bfe6552b)

But is dropped on narrow widths: 
![image](https://github.com/iFixit/react-commerce/assets/7053450/db803b12-0a99-402a-b4d1-6ce61d3cfd64)

As discussed with @mmarcon91 , do not hide text on narrow widths. (@mmarcon91 I'm not sure how you were planning on implementing this—if text is supposed to get smaller, if you're increasing the height of the section, or if we want to have multiple versions of the descriptions) 

CC @dhmacs @ifixitmaxb

**Comment by mmarcon91** [comment]
If the description is larger than the container the container should enlarge keeping the photo aligned at the top
