### ISSUE TITLE
Vulcan: Fix mobile table overflow

### ISSUE THREAD

**Issue by ianrohde** [iFixit/react-commerce#1750]
https://react-commerce.vercel.app/Vulcan/Washing_Machine_Has_No_Water#water-supply-is-off

Screenshot from mobile Chrome 

![Image](https://user-images.githubusercontent.com/72166715/243786666-e45a02fa-bdce-4458-b80d-173a73b34225.png)

Another example: https://react-commerce.vercel.app/Vulcan/Whirlpool_Refrigerator_Door_Not_Closing

![Image](https://user-images.githubusercontent.com/72166715/243792134-403270e4-c9f7-44fc-ab7e-2d90e1a2cdf5.png)

https://react-commerce.vercel.app/Vulcan/iPhone_Black_Screen

![Image](https://user-images.githubusercontent.com/72166715/243859499-eb354334-3bcf-4635-aaf3-42c3ca3fef1c.png)

**Comment by ianrohde** [comment]
I feel this is a good opportunity to modernize this image layout. We should be using flex/grid here so we can adjust the orientation to row or column on desktop/mobile.

**Comment by ianrohde** [comment]
Seems we're stuck with tables, so I'm going to make them scroll ([Slack ref](https://ifixit.slack.com/archives/CDFNZ4N4A/p1686685252032149))

**Comment by ianrohde** [comment]
@sctice-ifixit I found a way to convert the table rows to columns, but there was hesitation since we don't always know the content type. Would you prefer I proceed with scrolling the tables on the x axis?

**Comment by sctice-ifixit** [comment]
> Would you prefer I proceed with scrolling the tables on the x axis?

Yes, I think so. I'd rather invest in more targeted solutions for images and treat arbitrary tables as just tables.

**Comment by ianrohde** [comment]
I thought I commented this yesterday, but I'm running into a layout issue where the `<table>` is on the same DOM level as the `<ul>` and `<p>` tags above it. In order to scroll just the table, we'll need a wrapper div around it to set overflow, otherwise all 3 are scrolled. I'm looking at viable options.

**Comment by sctice-ifixit** [comment]
> In order to scroll just the table, we'll need a wrapper div around it to set overflow, otherwise all 3 are scrolled. I'm looking at viable options.

We can add the wrapping div to [the table renderer](https://github.com/iFixit/ifixit/blob/7965a055cc038838e59d141946a35385b422fe36/Objects/Text/Wiki/Render/Xhtml/Ifixit/Table.php#L28). I think the likelihood of a regression is low.

**Comment by ianrohde** [comment]
https://github.com/iFixit/ifixit/pull/48424 is the first phase that updates the shared template
