### ISSUE TITLE
Replace "Image Not Available" placeholder

### ISSUE THREAD

**Issue by lithobraking** [iFixit/react-commerce#176]
For product list items on the collection pages with no available thumbnail [we just show "not available" over a grey background](https://react-commerce.vercel.app/store/parts?q=htc+vive+controller). Let's replace that with No Image Fixie:

<details>
<summary><b>No Image Fixie</b></summary>

![NoImageFixie_592x592](https://user-images.githubusercontent.com/34843669/154734693-32ddb064-5440-44bd-b67d-2f3d6cbcea4b.jpg)

</details>

**↑↑↑** This 592x592 image is the highest resolution version that I know of, but that should be fine for its purpose. For production, is this fine to just host in Strapi, or should No Image Fixie be part of the ongoing considerations about how we're handling image hosting?

**Comment by dhmacs** [comment]
@lithobraking I think this belongs to Next.js assets 👍
