### ISSUE TITLE
Product list: Filter facets not cleared out when moving to child collection

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1766]
## Details
I noticed that this isn't happening consistently after the first try. Maybe caching issue?
Steps:
1. Go to a collection page
2. Add an item type facet
3. Click on a child page
4. See the item type is still applied to the page

https://github.com/iFixit/react-commerce/assets/72166715/a204ceeb-75c1-4e44-b45a-4657560c7fd9

## Additional details
Found while testing https://github.com/iFixit/react-commerce/pull/1763#issuecomment-1599349142

**Comment by sterlinghirsh** [comment]
I think we've gone back and forth on this, but if possible, it's best for child devices to retain the filters (especially item type) as long as any results exist.
