### ISSUE TITLE
Vulcan: Pre-launch style pass

### ISSUE THREAD

**Issue by ianrohde** [iFixit/react-commerce#1786]
Issue was originally for Format mobile image/text wrapping, but I'm looking to address these specific layout issues in a broader style pass, per https://github.com/iFixit/react-commerce/issues/1786#issuecomment-1615108625

https://react-commerce.vercel.app/Vulcan/MacBook_Fan_Loud
https://www.cominor.com/Wiki/MacBook_Fan_Loud
|Vulcan|Wiki|
| - | - |
|![Image](https://user-images.githubusercontent.com/72166715/243790287-3e4447b0-f135-469b-9585-812c44a8b43a.png)|![Image](https://user-images.githubusercontent.com/72166715/243790186-f196f2b7-355d-481d-82ba-f00a62ae1ab3.png)|

The above is what it looks like on my physical device. Here's an even narrower screen width:

![Image](https://user-images.githubusercontent.com/72166715/243790862-2fe65266-4ba6-4d41-b988-6d7bc70c6ac4.png)

**Comment by ianrohde** [comment]
@sctice-ifixit these layout issues are starting to add up. Right now our Vulcan CSS is basically a port of the old Wiki. I'd like to refactor it to modernize and lay a foundation so it adapts to whatever we drop in. We would be looking at a 3 point estimate.

**Comment by ianrohde** [comment]
Apologies, I don't mean to be vague. I'm primarily looking to re-write the styles that control the page layout so we don't have to keep putting in fixes for individual issues.

**Comment by jarstelfox** [comment]
![image](https://github.com/iFixit/react-commerce/assets/857362/998f52b0-0906-4476-9190-fbe1ebbed112)
Weird spacing

**Comment by ianrohde** [comment]
> https://www.ifixit.com/Vulcan/Ice%20Maker%20Leaking#Section_Additional_Resources
> looks weird; lots of space

<details>
<summary>Better?</summary>

<img width="1720" alt="Screenshot 2023-07-10 at 2 15 08 PM" src="https://github.com/iFixit/react-commerce/assets/1634505/4e6f4e12-2c6f-4f76-8ddd-c3399a081e4c">

</details>

The alert now has a top margin of 16px (per design) and the `Answers Forum: Leaking Ice Maker` paragraph has no margin, because last-child. LMK if that still looks unbalanced.

**Comment by ianrohde** [comment]
> ![image](https://user-images.githubusercontent.com/857362/252477116-998f52b0-0906-4476-9190-fbe1ebbed112.png) Weird spacing

<details>
<summary>Better?</summary>

<img width="1720" alt="Screenshot 2023-07-10 at 2 25 35 PM" src="https://github.com/iFixit/react-commerce/assets/1634505/1cacbf51-6756-4c53-895d-0a2b760bf550">

</details>

I've tightened up a fair amount in mobile view, but this was a stray inline padding.
