### ISSUE TITLE
Vulcan: Fix Vimeo video container sizes on mobile

### ISSUE THREAD

**Issue by ianrohde** [iFixit/react-commerce#1787]
In a solution card: https://react-commerce.vercel.app/Vulcan/iPhone_Bluetooth_Not_Working#logic-board-fault
![Image](https://user-images.githubusercontent.com/72166715/243856635-e6810e50-948a-4afa-adb8-c92a8a7e1ab7.png)

In the intro, cropped, but not resized: https://react-commerce.vercel.app/Vulcan/iPhone_Bluetooth_Not_Working
![Image](https://user-images.githubusercontent.com/72166715/243856659-367c3df4-6d91-4137-b8ce-9ae8b6127f21.png)

**Comment by ianrohde** [comment]
@erinemay I am not able to replicate this issue. It looks like the video has been removed from the example. In one screenshot I saw some overflow issues on the Repair blocks with badges, but I think they were resolved in https://github.com/iFixit/react-commerce/pull/1769. What would you like to do?

**Comment by erinemay** [comment]
It looks partially fixed. It looks like the vimeo frame doesn't extend past the edge of the solution card, but the video is still cut off as if it's still that size.

I added vimeo and youtube videos to that vulcan page (https://react-commerce.vercel.app/Vulcan/iPhone_Bluetooth_Not_Working)

We get just the corner of the video and don't see the controls. 

vimeo on top, youtube under it
![image](https://github.com/iFixit/react-commerce/assets/72166715/864da0ed-1a49-4d1d-bf69-be3a77056a9b)

**Comment by ianrohde** [comment]
Thanks, I'll take care of it 👍
