### ISSUE TITLE
Vulcan: Linking a private guide 500s the entire page

### ISSUE THREAD

**Issue by jarstelfox** [iFixit/react-commerce#1795]
Repro steps:
1. Create a new guide which isn't published
2. Link it from a problem wiki as part of a solution
3. Load the Vulcan view and see the error:
   ![Image](https://user-images.githubusercontent.com/1283490/249251982-1c7ff838-601b-46ff-8528-c5d6da13f0e6.png)
   The logs should show that the guide fetches are returning 403: 
   ![Image](https://user-images.githubusercontent.com/1283490/249252144-66bac7a7-8c1f-43ae-886b-2ed090e6ebc9.png)

**Comment by sctice-ifixit** [comment]
I suspect this isn't worth taking on before we tackle https://github.com/orgs/iFixit/projects/20/views/1?pane=issue&itemId=29183629, which will shift to getting guide data from the Troubleshooting API. I think doing that will cease to make this a problem.

**Comment by jarstelfox** [comment]
Understood. 

For reference, I haven't been able to repro:

Private guide: https://jstelfox.cominor.com/Guide/JBL+Boombox+Battery+Replacement/162342
Vulcan page loads with link: https://jstelfox.cominor.com/Vulcan/Roomba%20Sweeper%20Not%20Spinning

**Comment by sctice-ifixit** [comment]
Closing on the assumption that we'll indirectly fix it by changing how we fetch guide data. Reopen if we run into it again.
