### ISSUE TITLE
New window icon mis-styling

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#1832]
### Issue:

The new window link icon following hyperlinks is massive and missing styling in some store items.

https://www.ifixit.com/products/anti-clamp

This doesn't appear on [Cominor](https://me.cominor.com/products/anti-clamp)

![Screenshot 2023-07-19 at 3 31 48 PM - Spencer Day](https://github.com/iFixit/react-commerce/assets/95656772/22e5da5f-ecab-4246-bef4-9776a465a38c)

![Screenshot 2023-07-19 at 3 31 04 PM - Spencer Day](https://github.com/iFixit/react-commerce/assets/95656772/7413859e-a948-41b4-8f88-1be3fd9dc842)

**Comment by ianrohde** [comment]
Reverting https://github.com/iFixit/ifixit/pull/48819 to resolve

**Comment by jordycosta** [comment]
Closing via https://github.com/iFixit/ifixit/pull/48819
