### ISSUE TITLE
Fix footer top margin

### ISSUE THREAD

**Issue by federicobadini** [iFixit/react-commerce#1835]
In this [commit](https://github.com/iFixit/react-commerce/pull/1816/commits/dca5eeca396b863bd2b17475bba0dd39ef6d6936) which is part of #1816 a top margin on the footer has been introduced.

I'm struggling to find this in mockups.
All the examples I've found appear to bind the footer strictly to the preceding component shown in the following picture. 
If any mockup showed that margin, I'd consider it an inconsistency, since the majority of them do not show it.

<img width="404" alt="Screenshot 2023-07-20 at 08 16 58" src="https://github.com/iFixit/react-commerce/assets/7805759/3ea9f85d-7320-4d14-9bc1-dd0044f963a5">

**Comment by ianrohde** [comment]
https://github.com/iFixit/react-commerce/assets/1634505/666a2a57-6f84-4ef6-aa57-3ad84335c876

**Comment by federicobadini** [comment]
@ianrohde that's `problem 1.0`
the mockup visible on the right side of it is `problem 1.1` which is aligned with the no-top-margin approach that is common to the rest of the mockups.

**Comment by ianrohde** [comment]
@federicobadini good to know on the no-top-margin. Out of curiosity, was that a standardization decision?

I'll switch Problem to bottom margin when we take on 1.1.

**Comment by federicobadini** [comment]
> Out of curiosity, was that a standardization decision?
I think so. Or it was a typo in the 1.0 mockup

Product page shows no spacing for the footer.
In collection pages the margin is zero too, since the only spacing is granted by main content padding.

So yes I think the 1.1 was among the other things also standardising that.
