### ISSUE TITLE
Unify on one component for displaying prerendered wikitext

### ISSUE THREAD

**Issue by andyg0808** [iFixit/react-commerce#1842]
In the process of building Vulcan, I implemented the [`Prerendered`](https://github.com/iFixit/react-commerce/blob/main/frontend/templates/troubleshooting/prerendered.tsx) component to handle displaying and styling HTML rendered by the PHP backend. I see that there are a [bunch of places](https://github.com/search?q=repo%3AiFixit%2Freact-commerce%20dangerouslySetInnerHTML&type=code) where we use `dangerouslySetInnerHTML` to display HTML, and the recent [problem](https://ifixit.slack.com/archives/C04TFU3QFD5/p1689816851561529?thread_ts=1689809910.699289&cid=C04TFU3QFD5) with https://github.com/iFixit/ifixit/pull/48569, which was missing styling when rendered wikis were pushed to store pages (but for which https://github.com/iFixit/react-commerce/pull/1783 was implemented, to ensure that `Prerendered` at least supported the new icons. Still my fault for not verifying that Vulcan was the only consumer of prerendered wikitext in react-commerce, but it would at least have been less serious if all wikitext was displayed via `Prerendered`. This would also simplify testing, as we wouldn't need to try to update a product in order to validate that wikitext renders reasonably.

**Comment by dhmacs** [comment]
@andyg0808 it seems that this work has been done in #1946. Do you think we can close this or is there anything else left to do?

**Comment by andyg0808** [comment]
@dhmacs I think that seems reasonable to me.
