### ISSUE TITLE
Added GET params 404ing Strapi Edit links

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#1862]
>A recent change on react-commerce seems to have started adding GET params to links that are sometimes breaking things. For example, https://www.ifixit.com/Parts/Samsung_Galaxy_S21_Plus has an edit link for Strapi that now points at https://strapi.ifixit.com/admin/content-manager/collectionType/api::product-list.product-list/1965?_gl=1*1d49xwc*_ga*MTMwNTQzMjYuMTYyMzg2NDgwMA..*_ga_5ZXNWJ73GK*MTY5MDQwNDQyMi41NS4xLjE2OTA0MDUyNDkuMzMuMC4w  which fails to load. Taking off the ?_gl=... parts makes the link work. Not sure if this is related to ga4 or something, but does anyone recognize this? 

https://ifixit.slack.com/archives/C90126AN4/p1690418622620769

cc: @sterlinghirsh @jeffsnyder

**Comment by erinemay** [comment]
Some additional info from @addison-grant 
>Looks like you're right to suspect GA https://www.google.com/search?q=_gl+_ga&rlz=1CDGOYI_enUS995US995&oq=_gl+_ga&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIKCAEQABgKGBYYHjIKCAIQABgKGBYYHjIICAMQABgWGB4yCAgEEAAYFhgeMggIBRAAGBYYHjIICAYQABgWGB4yCggHEAAYChgWGB4yCAgIEAAYFhgeMggICRAAGBYYHtIBCDY3OThqMGo3qAIAsAIA&hl=en-US&sourceid=chrome-mobile&ie=UTF-8

>I think we could turn the feature off potentially, but that looks like it could mess up the way GA tracks users across our different domains

>I have a feeling it's all or nothing with that "feature"

**Comment by erinemay** [comment]
It appears to be intermittent? When I try to edit https://www.ifixit.com/Parts/Samsung_Galaxy_S21_Plus, I'm getting the correct Strapi page.

**Comment by danielcliu-ifixit** [comment]
I think this has been addressed by changing the configuration for tracking cross-domain movements. We had a rule that said if a domain contained `.ifixit.com` then we would track, but we actually didnt' want to track for traveling cross-domain to strapi.ifixit.com as the cross domain url parameters necessary for GA to track broke the strapi link. We will likely also have to do this for the rule for cominor that is analagous to the ifixit rule previously mentioned.

**Comment by danielcliu-ifixit** [comment]
This has been addressed by changes in GA4 by configuring tag domains in https://analytics.google.com/analytics/web/#/a30506p383872824/admin/streams/table/5414639814
