### ISSUE TITLE
Bundle Quantity filter is confusing

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/react-commerce#187]
On pages that have "Bundle Quantity" as a filter option, such as https://react-commerce-ifixit.vercel.app/store/parts, the choices and products associated with those choices are confusing.

As a user, I would expect that if I select "Individual," it will show me all products that are sold individually whether they are also sold in a bundle or not. Instead, it only shows me products that can be bought individually or as other quantities. When I have seen this on other sites I was visiting as a regular customer, I assumed the site was meant for B2B sales only and left immediately as I don't need ten batteries for my phone. I only need one.

Reproduction:
1. Go to https://react-commerce-ifixit.vercel.app/store/parts.
2. Click the dropdown for the "Bundle Quantity" filter.
3. Select "5".
4. Deselect "5" and select "Individual" instead.
5. Note that in both cases "Lightning to USB Changing Cable" is the only available product.

Windows browsers

**Comment by dhmacs** [comment]
@k0rvusk0r4x same answer as this one https://github.com/iFixit/react-commerce/issues/191#issuecomment-1061655105

**Comment by k0rvusk0r4x** [comment]
@dhmacs Makes sense to me to hold off if that's the case and make sure this is fixed up when Algolia is being used.

**Comment by dhmacs** [comment]
@k0rvusk0r4x I don't see bundle quantity listed as a facet on the new index, I'm closing this since it seems like it's not applicable anymore. Feel free to re-open if you have new feedback
