### ISSUE TITLE
The "x" on filter dropdowns is not intuitive

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/react-commerce#188]
Depending on what online store you visit, the button in the upper right corner of the filter dropdown could be to collapse it, to clear the choices, or both. The standard for the majority of sites is:

- If the dropdown expand button is a down arrow, the collapse button is an up arrow or a minimize icon (not a hyphen).
- If the dropdown expand button is a plus sign, the collapse button is a minus sign/hyphen.
- If a "clear all filters in this category" button is present, it is either the word "clear" or an "x."

Here we have an "x" that is a collapse button instead. Because it goes against the majority of sites, it feels unintuitive to customers and can be confusing.

Windows browsers

**Comment by dhmacs** [comment]
Filters have been redesigned, here's a preview

<img width="227" alt="Screenshot 2022-03-08 at 14 43 37" src="https://user-images.githubusercontent.com/4640135/157249856-ba58cad1-aca7-491f-80b5-6505f46007db.png">

Kyle told us that it's better if we polish everything else before we spend more time working on this
