### ISSUE TITLE
Tests: Unskip flaky tests

### ISSUE THREAD

**Issue by batbattur** [iFixit/react-commerce#1890]
## Summary 
Tests are flakey due to shopify / ifixit product mismatches. See https://github.com/iFixit/react-commerce/pull/1889 for the full conversation.
> We run stock the products used in those tests using cron job on iFixit/ifixit  side, background https://github.com/iFixit/ifixit/pull/48707.
>> The products seem to stocked properly on iFixit side but not on shopify. For example, for IF171-005-3:
>>> - 3 available on iFixit admin : https://www.cominor.com/Admin/Inventory/inventory_report.php?searchTerm=171005&displayCount=50&page=1
>>> - 9 available on shopify admin: https://admin.shopify.com/store/ifixit-test/products/6561403928666

From https://ifixit.slack.com/archives/C01GVQAAGDU/p1691194981380079?thread_ts=1691183129.864269&cid=C01GVQAAGDU:
> Oh looks like someone changed the label from New to New-TEST for condition and now it's out of sync between Shopify and cominor.

## Do this
Unskip the skipped tests from https://github.com/iFixit/react-commerce/pull/1889, and https://github.com/iFixit/react-commerce/pull/1886/commits/b75af48c2505d5bb4307decb8c449b36e5e6bcfb.

**Comment by mlahargou** [comment]
I wonder if we can create a test product instead of using real products that are more prone to having their attributes changed in akeneo.

That test product would have to stay around so we couldn't use the same products that our phpunit tests use.
