### ISSUE TITLE
The footer is odd

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/react-commerce#190]
It feels odd and visually uncomfortable that the main part of the page is primarily centered but the footer leans hard to the left. It is also the same blue as the header. See [here](https://github.com/iFixit/react-commerce/issues/189).

Windows browsers

**Comment by dhmacs** [comment]
@k0rvusk0r4x 
The only reason why the footer is like that, is because partners logos haven't been uploaded to Strapi (those occupies the empty space on the right).. I can upload a bunch of logos so you can see how it looks like

**Comment by k0rvusk0r4x** [comment]
This makes sense to me. It will be on QA to make sure it does, in fact, look good once things are in place.

**Comment by dhmacs** [comment]
@k0rvusk0r4x this is the PR if you want to take a look

https://github.com/iFixit/react-commerce/pull/204
