### ISSUE TITLE
Header login and search don't work

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/react-commerce#192]
1. While logged out, click login.
2. Once it loads, note you are looking at code, not the login modal or page.
![image](https://user-images.githubusercontent.com/33426643/157138073-e913696e-c2c5-4a8a-b694-ffd66a44c96c.png)
3. Attempt to use the search bar and note the same happens.

Windows browsers

**Comment by dhmacs** [comment]
@k0rvusk0r4x I'm trying to guess by the error what this is, I guess you've bumped into some cominor site issue? Login is just a link to https://www.cominor.com/login, so I'm not really sure what to do about it

**Comment by erinemay** [comment]
I was able to try this once cominor came back up. It's working as expected (expected = link to https://www.cominor.com/login).
