### ISSUE TITLE
Malformed data from `store/product/${productHandle}` in dev and preview

### ISSUE THREAD

**Issue by federicobadini** [iFixit/react-commerce#1928]
The iFixit product-data endpoint located at `store/product/${productHandle}` has been returning improper data, which subsequently leads to the condition label being incorrectly displayed in both the development and preview environments.

The above service produces a list of variant options that are used to filter the Shopify product variants (see [here](https://github.com/iFixit/react-commerce/blob/40f042f94b594d032081082a5b0691109a633307/frontend/models/product/components/product-option.ts#L19-L21)). However, the aforementioned endpoint is currently returning the value `New-TEsstss`, instead of the expected value `New`. This discrepancy results in condition being shown as a select with no option instead of a label.

<img width="585" alt="Screenshot 2023-08-22 at 09 38 28" src="https://github.com/iFixit/react-commerce/assets/7805759/6855c87f-446b-452b-ac0c-3b1c8bb578f6">

**Comment by masonmcelvain** [comment]
I changed the text back to `New` in [Akeneo](https://akeneo.cominor.com/#/configuration/attribute/condition_code/edit). I checked a few pages on the preview and the problem seems resolved.
