### ISSUE TITLE
Checkout section is missing sometimes

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#1930]
### Preview:

https://github.com/iFixit/react-commerce/assets/95656772/5a449350-7488-4ce0-9d48-dd98d02cd504

**Comment by masonmcelvain** [comment]
Slack thread: https://ifixit.slack.com/archives/C0252FETV2S/p1692732728706279

Repro steps:

> every time I empty my cart in Incognito/not logged in and add an item to cart I get this problem. I checked a couple browsers.

**Comment by dhmacs** [comment]
I think we're having this issue https://github.com/chakra-ui/chakra-ui/issues/7935

I'll find something to fix it
