### ISSUE TITLE
Lighthouse Accessibility regressions on /parts

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/react-commerce#194]
Running lighthouse on https://react-commerce-ifixit.vercel.app/store/parts and https://me.cominor.com/Store/Parts shows there has been some regression on accessibility.

This accessibility issue  does not exist  on the current page: 
![image](https://user-images.githubusercontent.com/33426643/157326070-2644d2be-688c-4a66-98c9-ef00120e2eee.png)

Note: other pages have higher accessibility scores than their current counterparts.

**Comment by dhmacs** [comment]
Seems like cominor is down right now, will check again later

<img width="1721" alt="Screenshot 2022-03-08 at 23 22 37" src="https://user-images.githubusercontent.com/4640135/157335812-142413da-f7ca-4a7f-a47f-e5e668123f3a.png">
