### ISSUE TITLE
On Sale items have the same regular price  

### ISSUE THREAD

**Issue by deltuh-vee** [iFixit/react-commerce#195]
The regular price for on sale items is the same as their sale price. I would expect the regular price to be higher.
![CleanShot 2022-03-08 at 13 15 39](https://user-images.githubusercontent.com/5289715/157326454-c475afd1-238a-4247-94d7-632c0f76c56d.png)

**Comment by dhmacs** [comment]
@deltuh-vee can you tell me how to reproduce this? How did you get to this product?

**Comment by deltuh-vee** [comment]
@dhmacs 
I found it in the grid view with this search:
https://react-commerce-ifixit.vercel.app/store/tools?q=shirt

**Comment by dhmacs** [comment]
@deltuh-vee got it, thanks 👍
