### ISSUE TITLE
Strapi: Send email

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1952]
We haven't set up Strapi email. So account invites and password reset emails are not being sent. 

Strapi thinks we send the email: 

![image](https://github.com/iFixit/react-commerce/assets/7053450/2778afb9-7d7a-4a40-a67c-24edc4afae06)

But no email is received. Please set up Strapi email. Link from Danny in [Slack thread. ](https://ifixit.slack.com/archives/C02KMFEHX62/p1693517314619949):

> Here's example strapi email configs: https://github.com/strapi/strapi/tree/main/packages/providers

CC @danielbeardsley @sterlinghirsh  @dhmacs

**Comment by jarstelfox** [comment]
Done: @danielbeardsley tested this in prod. You can test it yourself by going to https://strapi.ifixit.com/admin/settings/email and sending a test email to yourself.
