### ISSUE TITLE
Value propositions: add back shipping proposition for Encompass parts

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#1969]
We removed value proposition "Same day shipping if ordered by 1PM Pacific." on all dropshipped parts (when `shopify_fulfillment_us` is not null) in https://github.com/iFixit/react-commerce/pull/993

We were manually placing BTI orders so didn't want to make commitments. Now we're automatically placing orders through Encompass—and Encompass can commit to shipping orders same day if placed by 2PM Pacific. 

Two parts: 

1) Please add back in the shipping value proposition when `shopify_fulfillment_us` = `encompass`
2) If it's not too much extra work, please make the note `2PM` instead of `1PM` when `shopify_fulfillment_us` = `encompass`. It's likely that we'll need to do this sort of show/hide + deadline customization by fulfillment partner moving forward. 

CC @dhmacs @sterlinghirsh

**Comment by sterlinghirsh** [comment]
If they order at 1:55p the order won't come out of limbo by the 2p cutoff, so it won't ship. I might leave the message as 1p just in case.

**Comment by dhmacs** [comment]
I need some clarification to get this done.

- @jeffsnyder Is it possible that a product might be fulfilled by multiple services? If so, should we show the value proposition anyway?
- @sterlinghirsh Obtaining the fulfilment service requires the admin api (which is not really suitable for frontend usage). Is there a metafield or something that I could use instead to know when a variant is shipped via `encompass`? Does `shippingRestrictions` metafield contain that as a possible value?

**Comment by sterlinghirsh** [comment]
It's in shippingRestrictions as fulfilled_via_dropshipping, and we shouldn't have to worry about multiple fulfillment services.
