### ISSUE TITLE
GA4: no admin traffic and debug_mode for development

### ISSUE THREAD

**Issue by addison-grant** [iFixit/react-commerce#1975]
Please implement the following rules for GA4 events:

Updated spec (Sep 25)

- In **prod**: only enable `debug_view` with a URL query parameter.
- In **dev**: turn on tracking and toggle to `debug_mode = true` with a site setting (do this for any user type)
- In **GA4**: add a Data Filter to not log `debug_mode=true` traffic

@sterlinghirsh @danielcliu-ifixit

**Comment by danielcliu-ifixit** [comment]
The goals of this issue have changed. After talking with @addison-grant about it

1.) Have production have ga4 on with debug_mode off by default
2.) Have development have ga4 off by default
3.) Add a URI parameter `ga4_debug` where if its set to true it will turn debug_mode on for that page (assuming ga4 is enabled for that site already)

**Comment by sterlinghirsh** [comment]
Is this done now?

**Comment by danielcliu-ifixit** [comment]
https://github.com/iFixit/ifixit/pull/50122
https://github.com/iFixit/shopify-v2/pull/1117
