### ISSUE TITLE
Vulcan: Figure out if/how to handle width of content container in viewports not included in the design

### ISSUE THREAD

**Issue by ianrohde** [iFixit/react-commerce#1992]
https://github.com/iFixit/react-commerce/pull/1944#issuecomment-1708825398

> The main content has more space to fill because the TOC was moved out of what was a shared container.
>
> We have been discussing how to handle this, but we'll need to discuss with Mattia to get clarity on how to handle the viewports that are not included in the design.

**Comment by sctice-ifixit** [comment]
Mattia did lay out some guidance in this [Figma thread](https://www.figma.com/file/QVLUEpDVoyiMM4MXEGq1L9?node-id=201:64773&mode=dev#548517895)

**Comment by ianrohde** [comment]
Carrying details over:

```
I made a small prototype to make it clear how the elements should be handled:
https://kdh9rt.csb.app/

min 1920
- side summary 
- content centered with respect to the window

min 1536
- side summary 
- content centered with respect to the window - width summary

min 1280
- lateral summary
- Full content - summary width

min 1024
- secondary content moves below primary content

Base
- summary included in primary content 
- side summary hidden
```

**Comment by ianrohde** [comment]
Mattia:

> I don't think it's a problem, I took stripe as a reference 
> 
> Do you think it's something to invest time in?

Me: 

> I'm not sure. This was raised by QA as a potential issue, but people with huge 4k screens are likely not running their browsers full-width. I never do.
> 
> Knowing that Stripe uses this pattern gives me more confidence on leaving it. We can easily pin it to the main content with 1 line of CSS if needed.

Given how easy it is to correct the issue, I think we should proceed and address this only if it is relayed as a problem.

**Comment by sctice-ifixit** [comment]
> Given how easy it is to correct the issue, I think we should proceed and address this only if it is relayed as a problem.

Works for me.
