### ISSUE TITLE
TOC: Section highlight issues

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#1993]
### Issue Overview:

https://me.cominor.com/Troubleshooting/iPhone/Won't+Turn+On/405189#Section_Questions_other_people_have_asked_about_this

When selecting a non-solution card section in the TOC, the sidebar seems to highlight the section below the one that I clicked on

![firefox_v7IxzrBKfv](https://github.com/iFixit/react-commerce/assets/95656772/1533d018-815f-4994-a855-a34be3a07931)

Here I am attempting to click on a sidebar section, it is highlighting the correct section in the main UI but not updating the sidebar

![ShareX_qr27Ok5PbX](https://github.com/iFixit/react-commerce/assets/95656772/6cfd762a-ea5f-4c9a-9074-84fc67a8a381)

**Comment by sctice-ifixit** [comment]
I think this is low priority. We use a heuristic to choose which item in the TOC is highlighted, and it's going to be wrong sometimes, especially when items correspond to sections that are very short, and even more so when there are several short sections right next to one another.
