### ISSUE TITLE
Webpack: Verify Tree-shaking

### ISSUE THREAD

**Issue by ianrohde** [iFixit/react-commerce#2011]
## Issue

There has been concern raised about if tree-shaking is working correctly ([slack thread](https://ifixit.slack.com/archives/C01GVQAAGDU/p1696355880443269?thread_ts=1696355226.255419&cid=C01GVQAAGDU)). Let's take a detailed look and make sure we are doing what we can to deliver small JS payloads to our users, especially in our larger packages.

## TODO

Verify that tree-shaking is working as intended in large packages such as:

[@chakra-ui/react](https://github.com/iFixit/react-commerce/blob/main/frontend/package.json#L28)
[@fortawesome/free-solid-svg-icons](https://github.com/iFixit/react-commerce/blob/main/frontend/package.json#L33)

**Comment by federicobadini** [comment]
Could you please provide more info on the reason that pushed for this investigation? 
I've already spent quite some time in inspecting the bundle so I think I could help here.

If you want to investigate on your own, remember that NextJS Bundle analyzer wraps Webpack bundle analyzer without offering too many config options.
If you want to extract a little bit more information on how modules are resolved, you can directly inject one additional parameter in the node modules dependency to make the build process output the webpack `stats.json` file too.
This file describes the webpack resolution chain, highlighting why a module was included or not.

<img width="702" alt="Screenshot 2023-10-04 at 19 30 45" src="https://github.com/iFixit/react-commerce/assets/7805759/ccfcfec5-4f77-4ce3-a23a-f82a05faeead">

I've re-checked the built output and apparently I didn't find anything wrong with how either fontawesome or chakra are included in react-commerce. 
If you noticed anything that made you suspect that something was not working correctly in the tree-shaking procedure, I'd really like to investigate on it.

**Comment by sctice-ifixit** [comment]
> If you noticed anything that made you suspect that something was not working correctly in the tree-shaking procedure, I'd really like to investigate on it.

Nothing specific, recently. In the past, we've run into issues with importing a single FA icon  increasing the bundle size as though all icons had been imported, and we just wanted to do an audit. But doing a little searching I ran into https://github.com/iFixit/react-commerce/pull/1257, which seems to indicate that things are working as expected. If you checked the built output just now and nothing looked out of place to you, I think we can call this audited. Thanks!
