### ISSUE TITLE
Add Strapi product list redirect field

### ISSUE THREAD

**Issue by masonmcelvain** [iFixit/react-commerce#2067]
## Problem

From time to time we get requests to redirect one product list to another. Let's add a field in Strapi for us to do that.

Edit: We need research/decide if we'd like to add these redirects at build time or at request time (see https://github.com/iFixit/react-commerce/issues/2067#issuecomment-1786809974)

Example requests:
https://github.com/iFixit/react-commerce/issues/2065
https://github.com/iFixit/ifixit/issues/45749

**Comment by dhmacs** [comment]
@masonmcelvain should this be a field on the product list to redirect to another product list? Is this something that we want to use at build time to compile `next.config.js` redirects or should this happen dynamically at request time?

**Comment by masonmcelvain** [comment]
Good question, I hadn't considered that we could fetch them at build time. That sounds like a more performant solution, though if I understand correctly, new redirects in Strapi would not go live until the next build.

I think users will be hitting these redirects far more often than we will be editing them, so I'd vote for fetching them all at build time and injecting them into `next.config.js`.

**Comment by dhmacs** [comment]
> if I understand correctly, new redirects in Strapi would not go live until the next build.

Correct 👍 

> That sounds like a more performant solution

I'm not 100% sure it's more performant. Need to check this, but maybe there's a way to cache redirect at the CDN level? 🤔

**Comment by sterlinghirsh** [comment]
I'm nervous about making it rely on a rebuild before the redirects go into effect. Seems like if we load the product list and then detect a redirect, we should follow it.

**Comment by masonmcelvain** [comment]
> I'm nervous about making it rely on a rebuild before the redirects go into effect. Seems like if we load the product list and then detect a redirect, we should follow it.

I'm going to implement it at request time, like we did for products in https://github.com/iFixit/ifixit/issues/50841. So we won't need to rebuild.

**Comment by ifixitmaxb** [comment]
Do these redirects have to be 308s? Is it possible to make them 301s? Also, would it be possible to have the option between 301 and 302? For example, the Black Friday, Holiday Gift Guide, and Cyber Monday pages should ideally be "temporary" (~10 month) redirects until we want to resurrect them every year around late October.

**Comment by masonmcelvain** [comment]
Our framework (Next.js) does not make it easy to use 301/2 instead of 307/8. AFAIK using one or the other does not affect SEO. The reasoning is described [here for 308](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308#see_also) and [here for 307](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307#see_also). Both reasons don't really apply to us since users typically visit our site via GET, but I think several organizations are trying to make 307/8 the new convention.

> the equivalent of this status code, but that may change the method used when it is not a [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET)

---

> Also, would it be possible to have the option between 301 and 302?

Yes, we can definitely make this an option. I made a stub issue: https://github.com/iFixit/ifixit/issues/51356

**Comment by masonmcelvain** [comment]
Ah it looks like there is an escape hatch that I overlooked:

>  In some rare cases, you might need to assign a custom status code for older HTTP clients to properly redirect. In these cases, you can use the statusCode property instead of the permanent property, but not both.

So yes, we could easily use 301/302 instead of 307/8. I will add that detail to the issue.
