### ISSUE TITLE
Piwik PRO missing order and revenue reporting

### ISSUE THREAD

**Issue by addison-grant** [iFixit/react-commerce#2071]
## Description

We aren't reporting revenue from the US store right now (we are also reporting revenue incorrectly for other stores, but I will be writing up separate issues for those.

I put the data in the parent issue: https://github.com/iFixit/ifixit/issues/50524

## Do this

Please check our purchase events, that they're firing, and that they fire with the right data:

Each event should report 
- Tax
- Shipping
- Subtotal (item revenue + tax + shipping)
- Discount
- Revenue (subtotal - discount)

CC: 
@davidrans @sterlinghirsh @danielcliu-ifixit

**Comment by dhmacs** [comment]
Hey @addison-grant, we're slowly moving every issue into the main repo now, so feel free to consolidate this as part of https://github.com/iFixit/ifixit/issues/50524
