### ISSUE TITLE
Product titles are displaying `internal_variant_notes`

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#212]
### What makes sense:

<details><summary>Fix Kit</summary>
Clear indication that there is a kit available and not just a part.

![image](https://user-images.githubusercontent.com/72166715/158865384-9ac1320e-1f0d-49c2-9840-2d51c1fcd297.png)

</details>

### What doesn't make sense:

<details><summary>"New" shows up on some product cards and not on others implying that those without aren't new</summary>

![image](https://user-images.githubusercontent.com/72166715/158865597-297097d1-f725-437f-89ab-f636929911b2.png)

</details>

<details><summary>Title Duplication when options are the same as the title</summary>

![image](https://user-images.githubusercontent.com/72166715/158865827-a59c6066-07fd-4c32-b7a2-929f86243198.png)

</details>

<details><summary>Who made it or where it was made</summary>
Probably won't inspire more clicks and doesn't help us with SEO.

![image](https://user-images.githubusercontent.com/72166715/158866048-a5af1568-82af-4b60-9030-77b3b0173f91.png)
![image](https://user-images.githubusercontent.com/72166715/158866094-f5b19f68-43ad-45a8-b7e3-b9d3717eb31a.png)

</details>

<details><summary>Variants with different quantities</summary>
We already have the quantity included in product titles where there aren't different quantity options:

![image](https://user-images.githubusercontent.com/72166715/158866242-d1b4df39-f6f5-4ee4-a3ae-ba10dc75a921.png)

I think that having a variant's quantity displayed on product cards could be a deterrent to anyone who doesn't want the quantity of that default variant. I say, If they want it, they want it, and let them choose the quantity when they get to the product page.

![image](https://user-images.githubusercontent.com/72166715/158866287-99a749d6-ebe7-4daf-bdbf-7fe57f8762fc.png)

</details>

<details><summary>Color</summary>
I'd prefer some indication that there are multiple colors available or no indication of color at all. 
This is another potential click deterrent to anyone who wants this product, but not in black.

![image](https://user-images.githubusercontent.com/72166715/158867343-9489c54d-734e-4444-a6cc-2fdde7da617f.png)

</details>

<details><summary>Packaging</summary>
Shouldn't say "Retail Packaged"

![image](https://user-images.githubusercontent.com/72166715/158870085-4eacc80b-891e-4377-a700-dd6a149eaf66.png)

</details>

<details><summary>Anything with version number (V1) in it</summary>

![image](https://user-images.githubusercontent.com/72166715/159055625-719fdfa9-dd12-4344-ad2d-66aced9e74ee.png)

</details>

**Comment by dhmacs** [comment]
cc @sterlinghirsh

**Comment by ifixitmaxb** [comment]
I would like to request that instead of displaying "Fix Kit" we say "Replacement Kit". There is good search volume and SEM data showing 3-4x conversion rate when someone is searching for a "[device] [part] replacement kit" whereas there is 0 search volume for "[device] [part] fix kit".

**Comment by jeffsnyder** [comment]
> What doesn't make sense:

@erinemay These titles are using `internal_variant_notes`. We don't use this attribute anywhere public facing and should not use the attribute here. I don't have a strong opinion about showing Product Variant information in the Product Title on Collections. And we currently don't show it in Search. But it seems (see below) that there's SEO value so we probably need to include it. If this is what we want ( @kwiens ? @ifixitmaxb ? ) I'll write up an implementation issue. 

> I would like to request that instead of displaying "Fix Kit" we say "Replacement Kit".

@ifixitmaxb this is a change that needs to take place in Akeneo. Not a change with anything in Collections.

**Comment by sterlinghirsh** [comment]
Let's use Algolia's `group_title` field instead of `title`.
