### ISSUE TITLE
Remove page number from page title/browser tab

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#213]
### Description
After the first page, the page number is included with the page title and browser tab (https://react-commerce.vercel.app/store/tools?p=2)

![image](https://user-images.githubusercontent.com/72166715/158904201-95fb32de-7ff5-4daf-92a9-046aaf1fa994.png)

### Do this
Remove it from the page titles and browser tab.

**Comment by dhmacs** [comment]
@erinemay There are a couple of reasons why this has been done this way. The first one is that the user has more context about the page he's visiting. The second one is more of a SEO aspect. 
We tracked the discussion about this here if you want to check it out 👉  https://github.com/iFixit/react-commerce/issues/89

Are there particular concerns that makes you want to get rid of the page number?

**Comment by erinemay** [comment]
I'm ok closing this after reading through the discussion. I don't think I've ever seen the page number in the page title. It looks odd to me as a design choice, but as long as it's been considered and was intentional, it's all good.
