### ISSUE TITLE
Strapi deploy: Move to github actions

### ISSUE THREAD

**Issue by mlahargou** [iFixit/react-commerce#2175]
This is the last thing we use cimpler for. Let's switch it to actions.

Currently, cimpler runs `backend/strapi-deploy`. That builds and pushes
the docker image to the ECR registry. It also does a `cap prod strapi:deploy`.
It also tags the deploy. 

We already have a workflow that does some of this: https://github.com/iFixit/react-commerce/blob/1303b0def289d79355d0357dc3193057cebcadba/.github/workflows/deploy-strapi.yml

Let's finish the job and get it on actions. We may have to use a self-hosted runner
as we use a cap task to deploy strapi.

cc @masonmcelvain @danielbeardsley @djmetzle

**Comment by danielbeardsley** [comment]
> Let's finish the job and get it on actions. We may have to use a self-hosted runner
as we use a cap task to deploy strapi.

There's a bit of nuance here that this repo doesn't contain the capistrano task (those are in the monorepo). So, we have this deploy process actually invoke code from another repo. This is unusual but when the repos are merged it won't be a big deal.

Maybe we should wait for project [Vestibule](https://github.com/iFixit/ifixit/issues/47724) and then this change will be relatively straight forward. Thoughts?

**Comment by mlahargou** [comment]
I think we could go with either approach. I think we may be able to add a self-hosted runner and then we can still use the capistrano tasks to deploy.
