### ISSUE TITLE
Hide out of stock alerts from product cards

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#218]
### Context:
Having "Sold out" on the product cards is a deterrent to getting users to visit the product page and have access to the "Notify Me" button. 

### To do:
Remove the `Sold Out` flare and "Out of Stock" note from product cards where the product is out of stock.
![image](https://user-images.githubusercontent.com/72166715/159054537-39c7cd22-aded-45dc-8f0c-48bae223efb6.png)

CC: @jeffsnyder

**Comment by sterlinghirsh** [comment]
It's pretty annoying to click a product result just to realize it's out of stock. Maybe if we put the notify button on this card I'd be okay with that, but I think it should still show out of stock until that.

**Comment by jeffsnyder** [comment]
@sterlinghirsh I much prefer annoying the customer to losing customers. Here's why we need to drop the `Out of Stock` flair for now: 

We allow variant-level filtering. Filtering by Part Only (or Fix Kit) or filtering by price can/will result in showing Out of Stock results where we still have a viable repair solution for the customer. This is the same line of thinking that makes me want to keep Condition our of the Facets. It results in potentially misleading results. I'd much rather have customers get to the Product Detail Page where they might 1) choose an in-stock variant, 2) sign up for Notify, 3) get angry at iFixit for making them do a "worthless" click. 

When we do solve this in Collections/Product Card, we need to address items 1 and 2 above by adding a Notify button and some sort of "Other Product Options Available" flair when relevant.

For now, our Notify feature is too valuable to our Purchasing Team and for recouping Out of Stock lost sales. So we need to maintain the status quo.

**Comment by jeffsnyder** [comment]
Continuing the tangent, this is an example of "Other Product Options Available" :

![image](https://user-images.githubusercontent.com/7053450/159979388-e9ea14a1-c351-429c-b950-8ab2cef1c6e0.png)
