### ISSUE TITLE
Products incorrectly shown as sold out

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#219]
This product is shown as out of stock. 
![image](https://user-images.githubusercontent.com/72166715/159054314-44fadd65-9720-4b59-984e-37a82eb178b3.png)

https://www.ifixit.com/Store/Android/Galaxy-S7-Battery/IF329-023?o=4

Neither the part nor the fix kit are out of stock. 

[We'd like to hide out of stock alerts from the product cards](https://github.com/iFixit/react-commerce/issues/218), so that might just solve this. However, this could indicate the collection pages are getting improper stock counts in general.

**Comment by erinemay** [comment]
Here's another product showing as Sold Out
![image](https://user-images.githubusercontent.com/72166715/159055392-d9f1fec9-1fb7-4684-b946-6d7fa2d7ea04.png)
https://www.ifixit.com/Store/Mac/iMac-Intel-21-5-Inch-Late-2012-2019-SSD-Upgrade-Bundle/IF173-042?o=12
It's showing 3 left.
![image](https://user-images.githubusercontent.com/72166715/159055468-2d651a98-e70d-45cc-8302-e63199a386ba.png)

**Comment by dhmacs** [comment]
It's an index issue:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/4640135/159064946-cef4c8cd-66fc-4d51-9231-b42e4ea27a77.png">

cc @sterlinghirsh

**Comment by erinemay** [comment]
Closing in favor of the main issue. This is just a symptom of it. https://github.com/iFixit/react-commerce/issues/220
