### ISSUE TITLE
Test metrics: Fix them

### ISSUE THREAD

**Issue by mlahargou** [iFixit/react-commerce#2196]
We stopped getting react-commerce test metrics on our dashboards. 
Let's fix that!

https://dashboards.cominor.com/d/IAl9Y4Knz/quality-assurance?orgId=1

![image](https://github.com/iFixit/react-commerce/assets/29667789/5c27e489-bbe8-4e18-9f2d-4cc4eb2acce2)

**Comment by mlahargou** [comment]
We probably need to create a new runner group and add a `metrics-runner` or something that can ingest the data and add the metrics to the ci RDS. 

We can probably just `cd /home/ifixit/Code` and run the `TestRecordKeeper.php` script directly.

**Comment by batbattur** [comment]
Let's start working on this after we merge the repos, [ref](https://github.com/iFixit/ifixit/issues/47724). For now, it's a security risk to allow public repo to access ubreakit. See more from https://github.com/iFixit/server-templates/pull/4460#issuecomment-1889942439.
