### ISSUE TITLE
Redo “Ship today if ordered by 5PM” flair on product cards

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#221]
![image](https://user-images.githubusercontent.com/72166715/159304886-97e5b80f-4094-40da-8ab3-5ce3c239ab16.png)

Our cutoff is 1PM Pacific Time

Potential solutions:
- Remove the flair entirely (moves the urgency to the product page).
- Include the correct time hard-coded (1PM Pacific time).
- Detect user's time zone and cater the alert to that zone.

cc: @jeffsnyder

**Comment by jeffsnyder** [comment]
> Remove the flair entirely (moves the urgency to the product page).

I prefer this. We will need to build a more robust plan with lots of input from Customer Service.
