### ISSUE TITLE
Add `Model History` section from mockups

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#222]
### To Do
Add `Model History` section from the mockups. 
Example: Current Macbook Pro page doesn't have the section: https://react-commerce-ifixit.vercel.app/store/macbook-pro

<details><summary>Screenshot from mockup</summary>

![image](https://user-images.githubusercontent.com/72166715/159337344-2fb1013d-2350-45ec-aa53-cc2197d45906.png)

</details>

### Additional details
The data doesn't appear to be in Strapi yet. 

cc: @jeffsnyder

**Comment by lithobraking** [comment]
@ifixitmaxb and @sterlinghirsh and I had a chat about this last week about the implementation of this and I believe we agreed that we can afford to abstain from doing this for now. We can reopen this if that ends up not being the case!
