### ISSUE TITLE
`View` button on list-view product cards is unnecessary

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#223]
![image](https://user-images.githubusercontent.com/72166715/159338869-60959e98-c288-475d-8e42-ff11380ca22a.png)

Rationale: 
- It's intuitive on e-commerce sites that the image and text, or the entire card itself is a link to the product page.  
- Our cards are links themselves, and the mouse icon changes for the user to indicate such. 
- I did a quick check on some other e-commerce sites. The closest I've come to seeing a similar button is a direct "Add to Cart" button on search results.

cc: @jeffsnyder

**Comment by erinemay** [comment]
> This button will probably be converted to an "add to cart" button once we implement that.

That makes sense. @jeffsnyder, how strongly do you feel about the `view` button?

**Comment by jeffsnyder** [comment]
I don't have a strong opinion. I can see value in having a less functional placeholder design element and iterating from there. 👍

**Comment by dhmacs** [comment]
Closing this while we wait to implement add to cart functionality
