### ISSUE TITLE
Low contrast in device breadcrumbs

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#224]
The contrast between the non-focused (light-gray) text and the white background is a little low. 
Subjectively, the text looks too light to me. Let's make sure that the contrast adheres to [WCAG standards](https://www.w3.org/WAI/WCAG21/Techniques/general/G18.html) (AA is ok). 

![image](https://user-images.githubusercontent.com/72166715/159343550-b54cc9aa-f4e7-4750-82cd-fd93e9aeced1.png)

(referring to `All Parts`, `Guides`, and `Answers` link text ⬆️ )

**Comment by dhmacs** [comment]
Seems like "Guides" and "Answers" are already `Aa`, I'm going to fix "All parts" to have the same contrast:

<img width="1076" alt="Screenshot 2022-03-22 at 16 15 41" src="https://user-images.githubusercontent.com/4640135/159515771-0164b98d-47df-438e-a629-33fee47a5165.png">

Would you increase it even further? (this is using core primitive `gray.500` which is the shade used for text)

**Comment by erinemay** [comment]
>Seems like "Guides" and "Answers" are already Aa, I'm going to fix "All parts" to have the same contrast:

Thank you for checking! ❤️  We can close this when that breadcrumb fix is out.
