### ISSUE TITLE
ProductList: Default to Gallery on Mobile

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#2240]
## Problem

List View on ProductList Pages is the default browsing experience. 

List View takes up considerable real estate on Mobile: 

<img width="373" alt="image" src="https://github.com/user-attachments/assets/c3b0d4cd-6e61-4ee4-9ab8-bd0285bb0ffa">

## Do This

Default to Gallery View on Mobile

<img width="373" alt="image" src="https://github.com/user-attachments/assets/f7dc86b1-830c-488d-9569-0fa132298934">

If we need to wait on AB testing, that's fine. 

CC @sterlinghirsh @ifixitmaxb

**Comment by dhmacs** [comment]
@jeffsnyder I think we're creating all issue in the monorepo now, this repo will be archived I think

**Comment by jeffsnyder** [comment]
Closed because this repo is not used for new issues anymore.
