### ISSUE TITLE
Too much empty space in filter container and search results field

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#225]
The container for product the filters is longer than necessary when the filters are all condensed. This leads to a state during scrolling when the user is looking at an empty container on the left. 

<details><summary>Tons of whitespace with empty search results</summary>

![image](https://user-images.githubusercontent.com/7053450/159359413-861852c1-adb1-4b2f-810f-8660d9f857e1.png)

</details>

<details><summary>Some whitespace in the filter box</summary>

![image](https://user-images.githubusercontent.com/72166715/159355406-e333cfe2-f1af-450e-9a7c-6fad12d114f3.png)

</details>

**To do with the space in the filter box:**
Not entirely sure what to do here, but I did a quick check on some other sites. I didn't find much inspiration since they see any blank space as ad territory....

Amazon, Ebay, and Carparts all leave the excess space empty (not an empty container, but just empty background). None of their filter containers are sticky, though. Best Buy's filter container is sticky, and they just fill the remaining space with ads. 

cc: @jeffsnyder

**Comment by jeffsnyder** [comment]
I think the bigger problem is the space below the products when few products are in the Collection/filtered results. Here's a good example: 

![image](https://user-images.githubusercontent.com/7053450/159359413-861852c1-adb1-4b2f-810f-8660d9f857e1.png)

**Comment by erinemay** [comment]
Yeah! I like the filter container expanding and contracting as needed. @lithobraking any thoughts?

<details><summary>One whitespace bug in the implementation above, but I assume this is just to demonstrate the filter box behavior</summary>

![image](https://user-images.githubusercontent.com/72166715/159755165-95c1f972-5254-454a-a035-db68f9240755.png)

</details>

**Comment by lithobraking** [comment]
@dhmacs I'm not experiencing that same bug, but aside from that yeah I this works for me.
