### ISSUE TITLE
Add space between page navigation and parent element

### ISSUE THREAD

**Issue by lithobraking** [iFixit/react-commerce#228]
The leftmost button of the page navigation element at the bottom of the pages touches the edge of the parent div.

Behold

![Screenshot from 2022-03-22 10-00-57](https://user-images.githubusercontent.com/34843669/159535824-bf0b7d9c-7ac8-4287-aad2-3e1c205cec89.png)

## Do This
Maybe we should add some padding to the navigation element to give those edges a little bit of separation?

**Comment by dhmacs** [comment]
@lithobraking this is a regression, I'm fixing this now 👍
