### ISSUE TITLE
Use a different American Express logo for footer

### ISSUE THREAD

**Issue by lithobraking** [iFixit/react-commerce#229]
The payment options grid in the footer currently uses this logo for American Express:

![Screenshot from 2022-03-22 13-56-45](https://user-images.githubusercontent.com/34843669/159575014-38f17f1b-0941-4ba6-aa33-bc1cb169b7e6.png)
![Screenshot from 2022-03-22 13-56-28](https://user-images.githubusercontent.com/34843669/159575007-03b0560b-2c68-423b-a586-da37d2ee48a2.png)

We talked it over and reached a consensus that we're not exactly in love with this logo, and were thinking we should use something like this one instead:

![amex cropped](https://user-images.githubusercontent.com/34843669/159575775-d7481885-7972-4841-b777-38be4303f653.png)

Let's see how it looks if we isolate the text from the background in the above image and use that.

**Comment by dhmacs** [comment]
@lithobraking where did you get this logo? I can't find it in the Amex brand guidelines:

https://about.americanexpress.com/newsroom/media-library/brand-imagery/brand-imagery/default.aspx

Seems like these are the logos they provide:

<img width="1161" alt="Screenshot 2022-03-23 at 10 17 32" src="https://user-images.githubusercontent.com/4640135/159665026-aba39a8e-7adc-406b-bd21-8d27f0b683c8.png">

**Comment by lithobraking** [comment]
@dhmacs I think the one I had probably came from google images? Let's go with the full version of the blue box logo from the brand guide instead, actually.

**Comment by dhmacs** [comment]
@lithobraking just fyi partners logo can be changed from Strapi in case you want to test it. Do you want to do it on your side or should I ask Mattia to prepare the image?

**Comment by lithobraking** [comment]
@dhmacs Sorry, thought I answered this already. I'm willing to let Mattia handle it.

**Comment by dhmacs** [comment]
@lithobraking changed! https://react-commerce.vercel.app/Store/Parts

Let me know if this is how you want it

**Comment by lithobraking** [comment]
@dhmacs looks good to me! I know I already told you a while ago, but I'm just putting it on the record here.
