### ISSUE TITLE
Enhance product list subcategories section heading

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#232]
## The problem

Auto generated heading for product lists doesn't always sound right, depending on product list title: 

| Parts product list subcategories section  | iPhone parts product list subcategories section |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/4640135/160148224-176087b5-e762-4979-9239-846d0789cf2d.png)  | ![image](https://user-images.githubusercontent.com/4640135/160148563-1ba76d91-7587-44b0-b7c1-3fcd9c5d9469.png) |

## Proposals

1. Generic “Choose a subcategory”
2. Default + ovverride field
    - Default: e.g. “Choose a model of `PRODUCT_LIST_TITLE`”
    - Override: Strapi product list field that let’s you override with a custom text 

What would you do?

cc @erinemay @jeffsnyder

**Comment by jeffsnyder** [comment]
Option 2 is ideal.

**Comment by sterlinghirsh** [comment]
I like the default + override but I might have the default be "Choose a model of [device title]" since saying "Choose a model of iPhone Parts" is goofy.

**Comment by dhmacs** [comment]
@sterlinghirsh can you provide me with a better copy for that?

**Comment by sterlinghirsh** [comment]
Better than "Choose a model of [device title]" ? Not sure what you mean by a better copy.

**Comment by dhmacs** [comment]
@sterlinghirsh My fault, I misread your previous message 😅 Anyway, that would work as a default message for product lists that have a `deviceTitle` set. What about tools product lists? Should I use the product list title there?

**Comment by sterlinghirsh** [comment]
I think that's a good default for now, though it may not matter much in practice. I think right now the plan is that only the top level Tools list will have sublists. i.e.

- Tools
   - Gripping
   - Screwdrivers
   - Cutting
   - ...

So only that one Tools page would have that section at all.
