### ISSUE TITLE
Add redirects for lowercase URLs

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#242]
### Description:
In https://github.com/iFixit/react-commerce/issues/163, we changed the capitalization rules in the URL scheme to match the rest of the site.
Now, lowercase urls 404. 
Example: [`/store/parts`](https://react-commerce.vercel.app/store/parts) 404s, but [`/Store/Parts`](https://react-commerce.vercel.app/Store/Parts) is all good.

### To do:
Add redirects for the lowercase URLs so they don't 404.
I believe we should be using 301 redirects for SEO.  @ifixitmaxb, please correct me if I'm wrong.

**Comment by ifixitmaxb** [comment]
Yes, we should use 301s. We should almost never use 302s unless it's something temporary, like taking a landing page down for a month and redirecting it somewhere else but knowing we'll bring it back after a holiday or campaign.

**Comment by dhmacs** [comment]
@erinemay `/store/parts` lowercase paths aren't used anywhere in production, aren't they? I'd recommend to avoid maintaining both uppercase and lowercase url if possible, since we'll have to maintain rewrite maps for that

**Comment by erinemay** [comment]
Closing this issue as we don't need to support case-insensitive URLs.

Common practice from https://www.w3.org/TR/WD-html40-970708/htmlweb.html:
> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive.

Our own Shopify stores already do not currently support case-insensitive URLs either. https://eustore.ifixit.com/Collections/parts
