### ISSUE TITLE
Products with single lined product descriptions are justified differently

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#25]
# Description:

While QAing https://github.com/iFixit/react-commerce/pull/24 I noticed a product for the `/collections/nintendo-switch` had a considerable amount of spacing between the product image and product text. 

After inspecting it, it seems that because the product description does not wrap, the flex property `justify-content: space-between` adds spacing between the two DOM elements. This causes it to look misaligned as compared to the other products in the list.

|Current Structure	|
|:---:|
|![Justify Content broken if product description does not wrap](https://user-images.githubusercontent.com/22064420/122985260-d0469e00-d352-11eb-8dbc-615516431dbc.png)	|

|Without `justify-content: space-between`	|
|:---:|
|![With out space between justification](https://user-images.githubusercontent.com/22064420/122985266-d2106180-d352-11eb-87e1-76d0f4b1e38d.png)|

|With More text added to product description	|
|:---:|
|![With loreum added](https://user-images.githubusercontent.com/22064420/122985461-13a10c80-d353-11eb-8949-ffba416b4f2d.png)|

# Repo Steps:
1. Go to `/collections/nintendo-switch` 
2. Scroll down to find **Nintendo Switch Digitizer Front Panel**
3. Notice there is more spacing between the text and image for the product
4. Inspect the product description and add more text
5. Now notice the spacing is reduced
6. Alternatively, uncheck the `justify-content: space-between` property for the product to see the spacing also get removed

**Comment by dhmacs** [comment]
@ardelato nice catch, I'll fix it 👍
