### ISSUE TITLE
Add "Manage" and "My Team" links to user dropdown menu

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#256]
Add the user drop down menu and these links:

![image](https://user-images.githubusercontent.com/26855/163837458-48175b47-471c-4a23-aca9-7ce818c14d8d.png)

Several of the links (team, manage) will be added to the user API:
https://github.com/iFixit/ifixit/issues/42716

### "My Team" link
If the `teams` array is present and not-empty include a "My Team" link to the first team in the list like `/Team/{id}`.

![image](https://user-images.githubusercontent.com/26855/163881731-a08a8114-6cb6-4ace-8a12-638ba8ce0f53.png)

**Comment by danielbeardsley** [comment]
> This comment suggest that links is an object, but I'm getting an array instead:

That's an unfortunate result of php's json stringifying. In php, objects and arrays are the same data structure. Converting to json examines the content, integer keys encodes as an array, while string keys ends up as an object. Empty arrays apparently end up as arrays and we can change that, but it would affect all empty arrays. I'd vote for just indexing into it anyway `[].manage` will just result as undefined.

> Also, can I get a test account with "Manage" capabilities?

I'll look into it.

**Comment by sterlinghirsh** [comment]
@dhmacs I made your account on Cominor an admin.

Do we still need to make any changes to the api? @danielbeardsley I imagine that even though [].manage will be undefined, it's kind of a weird thing to do in typescript. If we don't end up wanting to keep the object/empty array approach, I wonder if it's more useful to list permissions more directly. Then the app can know the manage url and the title of the manage link, and the api just indicates whether it should be displayed. `if (userHasAdminPrivilege) { <a href="/Manage">Manage</a> }`. It feels kind of roundabout to make the app know the title of the link but not the url, leading to logic like `if (user.links.manage != null) { <a href="user.links.manage">Manage</a> }`. Imagining a non-web client for the api like an app, it probably wouldn't care about the value of `/Manage`, it just wants to know the permission. If the link doesn't vary and it's either a constant string or null, it seems better to either have a boolean like `user.adminPrivilege = true`, or an enum like `user.privilegeLevel = 'admin'` or if we have to support multiple privileges, `user.privileges = ['admin']`.

If we do need to support customized links whose values vary per user, or if we want to use the api to inject header links without changing the template for some reason, we could instead have an array of links like `links: [{title: 'manage', url: '/Manage'}]`. That keeps the control of the title and url together within our api. Though I'm not sure what other links we'd put in this list. I don't think it makes sense to keep header logic like "what links are shown in the user menu" directly in this api response.

**Comment by danielbeardsley** [comment]
> even though [].manage will be undefined, it's kind of a weird thing to do in typescript

That's not true. Typescript only knows what you tell it about the shape of responses. typescript isn't a runtime thing, it's only a compile-time type checker. Just tell it the shape is `links: {manage: string|null}` and it'll work cause for this purpose they are equivalent. No part of the system will know or care if it's an empty array or an empty object. This is not an actual problem.

>  It feels kind of roundabout to make the app know the title of the link but not the url, leading to logic like if (user.links.manage != null) { <a href="user.links.manage">Manage</a> }. Imagining a non-web client for the api like an app, it probably wouldn't care about the value of /Manage, it just wants to know the permission. If the link doesn't vary and it's either a constant string or null, it seems better to either have a boolean like user.adminPrivilege = true, or an enum like user.privilegeLevel = 'admin' or if we have to support multiple privileges, user.privileges = ['admin'].

I wholly disagree with this paragraph.

* Freezing non-public urls and including them hard-coded in other apps has obvious negatives with no positives
  * It makes them hard to change
  * It makes them impossible to translate
* Having to duplicate logic outside our app about what users with the admin permission has drawbacks 
  * We already think its a bad idea to use `if (isAdmin)` everywhere inside our apps, preferring `if (canAccessManage())` 
  * Distributing this logic even farther than it already is makes it hard to reason about what admins are allowed to do
  * It increases the chance of bugs where we've got two sets of logic in different apps that need to kept in sync

**Comment by sterlinghirsh** [comment]
I think you're probably right that most of the time, it will work as long as we're checking user.links.manage and comparing to undefined. I still think it's sloppy to have an empty array vs an empty object here. Looks like it's not actually that hard to make it work as we'd expect, though, if we use an `ArrayObject` instead of an array for `links`. An empty `ArrayObject` encodes as `{}`, but otherwise behaves basically identically to an array.

If you're worried about using "isAdmin", we can put "canAccessManage" as one of the permissions if we want to get that granular with it.

> Freezing non-public urls and including them hard-coded in other apps

Realistically, though, this isn't another app. This is (or will be) the frontend of our main web app, so I don't feel bad about "freezing" the url. In fact, the nextjs frontend is the part that will dictate urls as we migrate more. I don't think we've even touched translatable urls in this app yet, and I don't think we even use one for /Manage.

I think we will have lots of urls in this app. If you're trying to argue that we should have a url generator system akin to GuideURI functions for the purpose of easily changing urls later, that's a reasonable proposal, but I don't think static links like this have to come from the api. Thinking about this another way, what else are you going to put in this "links" field on the user api?

**Comment by dhmacs** [comment]
> Realistically, though, this isn't another app. This is (or will be) the frontend of our main web app, so I don't feel bad about "freezing" the url. In fact, the nextjs frontend is the part that will dictate urls as we migrate more. I don't think we've even touched translatable urls in this app yet, and I don't think we even use one for /Manage.

I agree. I see the advantage of centralizing links management, but I would do it at the source code level, not via API. We could do something similar to what [Rails](https://guides.rubyonrails.org/routing.html) does.

**Comment by danielbeardsley** [comment]
> If you're worried about using "isAdmin", we can put "canAccessManage" as one of the permissions if we want to get that granular with it.

Using `isAdmin` all over our app has lead to us not knowing what being an admin really means cause that information is distributed in many places, same with `isLive()` and `isiFixit()`. This is a pattern we've been actively avoiding as a team for years.

> Realistically, though, this isn't another app. This is (or will be) the frontend of our main web app, so I don't feel bad about "freezing" the url. In fact, the nextjs frontend is the part that will dictate urls as we migrate more. I don't think we've even touched translatable urls in this app yet, and I don't think we even use one for /Manage.

Fair. Good point.

That said, It's still an anti-pattern to sprinkle and repeat hard-coded urls within one app. We don't do this with the JS within carpenter, we pass all urls to JS from the backend (treating the backend as the authoritative source of urls).

>  I would do it at the source code level, not via API. 

But our app doesn't currently share source with react-commerce. We could *move* that direction and have some static `urls.json` that we export. This is actually what we do with the JS in our main app, but it's not a published package and just a generated json-like file.

In the end, I don't care that much about one url, but I want us to be headed in the same direction and have the same code quality motivations.

**Comment by dhmacs** [comment]
> But our app doesn't currently share source with react-commerce. 

`react-commerce` is accessible via the monorepo, that's how we're sharing header and footer.. so we should be able to share code

>We could _move_ that direction and have some static `urls.json` that we export. This is actually what we do with the JS in our main app, but it's not a published package and just a generated json-like file.

I was thinking more about dynamic utilities, rather than static json.. With utilities you can do parametric paths.

```ts
// Passing a product list object
productListPath(productList)

// Or passing a product list id
productListPath(productList.id)
```

Again this is just an idea stolen from Rails best practices

**Comment by danielbeardsley** [comment]
> I was thinking more about dynamic utilities, rather than static json

Yes, that sounds good. This is what we do in php, nearly 100% of our urls are generated by small utility functions like this. Copying some of that logic to JS would tend to increase the chances of bugs and increases maintenance having two parallel sets of logic, but it still may be the best way.

**Comment by masonmcelvain** [comment]
The `user.links` field is now `{}` when empty instead of `[]`.
