### ISSUE TITLE
Add product sorting options to collection page

### ISSUE THREAD

**Issue by lithobraking** [iFixit/react-commerce#260]
In the collection page [figma mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit-Shopify-Working-Files?node-id=1494%3A6796) that we have, there is a select component which allows users to choose how displayed products in the collection list are sorted.

![Screenshot from 2022-04-20 17-09-33](https://user-images.githubusercontent.com/34843669/164507322-5039444c-e849-4bd3-8581-09fb5401da44.png)

## Do This
Add product sort select to the page. The options that I can immediately think to include are:
- Most Popular
- Price (Low to High)
- Price (High to Low)
- Highest Rated

@dhmacs We have some work to do on our end to make `score_product` updated and accurate, but I don't think that'll be a blocker.

CC: @sterlinghirsh @jeffsnyder

**Comment by dhmacs** [comment]
@lithobraking This is after v1 launch right? Anyway sorting with Algolia requires replica indexes, can I add these myself? Keep in mind that every sort option that we add requires a standard replica, which will increase the number of records in Algolia (hence the cost)

**Comment by jeffsnyder** [comment]
I _think_ y'all explained that we have a score and can sort by popular by default now. But getting an updated score and adding the ui/ux elements is work that needs to be done and will be done post-launch. 

For v1, I just need to make sure that the default sort order is reasonably good.

**Comment by lithobraking** [comment]
> For v1, I just need to make sure that the default sort order is reasonably good.

With that in mind, this issue can be saved for later.
