### ISSUE TITLE
Fix Strapi filtering issue

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#264]
@jeffsnyder pointed out that sometimes Strapi populate field search does not work correctly. We need to investigate this, probably it's a bug that we can fix by updating Strapi to the latest version.

![image](https://user-images.githubusercontent.com/4640135/164556615-0ee6be6c-fe11-4bb8-820b-5c7b44f36e08.png)

**Comment by jeffsnyder** [comment]
@dhmacs I don't remember. When I showed you the problem that I have, did your computer/browser have the same problem? Or is this something that is happening on my computer only?

**Comment by dhmacs** [comment]
@jeffsnyder after a while I was able to replicate it too, even though it was not clear how

**Comment by jeffsnyder** [comment]
@dhmacs I haven't had this problem since launch (or maybe since shortly after launch?). I think it's good to close. And if it comes up again I'll check the console and give you something better to work from. (I can't "Comment and Close" I can only "Comment".)
