### ISSUE TITLE
Enable bulk assignment of banners to product list pages

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#265]
During promotions the marketing team needs to add banners to several product lists. 

Examples:
- Add a banner to every product list
- Add a banner to "iphone" product lists

Currently Strapi does not have a native interface for bulk updates.

## To do

Research what's the best option we have here. Probably we need to build a custom plugin that enables that.

cc @jeffsnyder

**Comment by jeffsnyder** [comment]
I'd like to use the same assignment method for banners as we build for FAQs. We will encounter this same category of problem with many other content types. I'd like to develop a single method applicable to multiple content/page types. There is a brief mention of the plan Sterling and I came up with in the FAQ Epic: https://github.com/iFixit/react-commerce/issues/772
