### ISSUE TITLE
Enable bulk update of product list attributes

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#266]
The marketing team needs to bulk update product list fields.

An example of that would we replacing "parts" with "replacement parts" in every product list metadescription
Strapi currently doesn't have a native interface for bulk updates.

## To do

Research a solution to enable bulk updates. Probably this would have to be done via a custom plugin

cc @jeffsnyder

**Comment by ifixitmaxb** [comment]
Other potential examples: 

1. Updating the tagline across dozens (maybe hundreds) of the same device tier (like all Acer Aspire Collection pages)
2. Inserting the same 3 FAQs (which I realize doesn't exist yet) across dozens or hundreds (potentially thousands) of the same device tier, like all PC Laptop Collection pages
3. Updating the title tag (aka meta title) across hundreds or thousands of similar category pages (like all Apple Collection pages)
4. *This one might not be applicable: bulk creating more indexable/canonical Collections pages like /Store/Tools/Drivers_and_Wrenches, /Store/Tools/Prying_and_Opening, /Store/Tools/Microsoldering, /Store/Tools/ESD_Safe, /Store/Mac/MacBook-Pro/Keyboards, /Store/Mac/MacBook-Pro/Logic_Boards, /Store/iPhone/iPhone-12-Pro-Max/Lenses, /Store/Mac/MacBook-Pro/Speakers (and all the Parts specific ones I've listed [here](https://docs.google.com/spreadsheets/d/1BDgAGe1D-aNMc940WfXzMpDi8pXMJONdtehpLxXpmTM/edit#gid=1408792000))
5. Updating the meta description template across all Collection pages

**Comment by jeffsnyder** [comment]
This topic is coming up again as we work through our dropshipping product expansion plans. We will likely start start selling products before they have Devices/Compatibility. So we'll need to build ProductLists that rely on Filters. And, over time as Device Pages are built, we'll switch ProductList configuration to rely on Device instead of Filter. This will most likely happen in large bulk actions.

@sterlinghirsh can we take this out of the icebox?

**Comment by dhmacs** [comment]
@jeffsnyder I took the time to see what we can do about this, and Strapi doesn't have bulk edit actions. There is a plugin that we can test:

https://market.strapi.io/plugins/strapi-bulk-operator

The other option is to build a custom edit UI in our addons plugins. 

Based on your feedback, here is a list of bulk edit actions that may be needed:

1. Bulk update of ProductList configuration:
   - Switch from Filter-based ProductLists to Device-based ProductLists as Device Pages are created.

2. Bulk update of taglines:
   - Update the tagline across multiple device tiers (e.g., all Acer Aspire Collection pages).

3. ~~Bulk insertion of FAQs~~:
   - ~~Insert the same set of FAQs across multiple device tiers (e.g., all PC Laptop Collection pages).~~
 **FAQ are going to be structured in a way that we will probably not need bulk operations**

4. Bulk update of title tags (meta titles):
   - Update the title tag across multiple similar category pages (e.g., all Apple Collection pages).

5. Bulk update of meta description templates:
   - Update the meta description template across all Collection pages.

Is this list exhaustive or are there other use cases that come to mind?

**Comment by jeffsnyder** [comment]
@dhmacs if I need to come up with an exact spec, I'm going to need some time. We also need to be able to _create_ ProductLists, bulk enable/disable ProductLists, assign parentage.. I understand this is a big ask. @ifixitmaxb and I will work on this together.

**Comment by jeffsnyder** [comment]
@dhmacs I worked through the ProductList manage UI with @ifixitmaxb . We need most of what's editable in the UI to be editable by a bulk upload. I don't think we'll need `LegacyPageID` or `LegacyDescription` or the ability to add, edit, and rearrange components/sections. And we don't need Locales to work until we have our storefront localized. 

So I'm not really sure how to approach an MVP spec. The MVP would include creating the pages, publish/unpublish, and setting parentage. I have a feeling those will be the hardest things to configure, whereas having five vs 20 of the actual ProductList attributes won't do much to the complexity.

**Comment by sterlinghirsh** [comment]
LegacyPageId and LegacyDescription were added to ease the transition to the new ProductListPage system. Are we good to drop those fields entirely now?

**Comment by dhmacs** [comment]
@jeffsnyder this is now merged in prod. If you'd like to play with it without affecting production, try to use it in https://main.govinor.com
