### ISSUE TITLE
Bug: Strapi admin dashboards not loading

### ISSUE THREAD

**Issue by lithobraking** [iFixit/react-commerce#268]
The admin dashboards for Strapi instances running on [branch-name].govinor.com aren't working for some reason. To recreate:
1. visit main.govinor.com
2. receive error message "Warning: An error occured while requesting the API" and an infinite loading screen

Despite the admin dash being inaccessible, the Next.js frontend still consumes the Strapi instance without any problems.

[The references to this problem](https://forum.strapi.io/t/warning-an-error-occurred-while-requesting-the-api/14313) I've found so far seem to focus on running Strapi in dev, but the common suggestion is to build Strapi with yarn instead of npm before running it. It could easily be something else, but this is a starting point!

**Comment by dhmacs** [comment]
Hey @lithobraking thank you for taking the time investigating this. I was already working on it last friday, and as you found out it's related to Strapi using `localhost:1337` even in production... I've read a long chat on their Discord channel and there wasn't any answers yet. I'll find a way to fix it asap 👍

**Comment by lithobraking** [comment]
It's such a weird and annoying bug! Has anyone in the discord server come up with an adequate temporary workaround, or will we have to figure something out on our own?

**Comment by dhmacs** [comment]
@lithobraking I've read through all the conversation and still no answer.. The weird part is that many people are experiencing it in, but no solution has been posted.. I'm experimenting with Strapi params, updating a few things to see if I can fix it

**Comment by andyg0808** [comment]
It seems unexpected, but if Yarn is often the solution, I wonder if this is related to the zillions of peer dependency errors we get with Strapi. Maybe there are some configurations which break things?
