### ISSUE TITLE
CSRF support on API requests

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#270]
## Problem
We need to handle CSRF. In order to make authenticated requests to our API (including add to cart) we need to provide a CSRF token along with each non-get request.

## Do This
When making a non-get request to our API, generate a CSRF token (A random string at least 10 characters long) and set it in a cookie named `csrf` (settings below). Also send that string in an `X-CSRF` header with the request. Our server validates that the cookie and the header's value match and rejects any request where they don't.

It's probably best to create a thin wrapper for fetch to handle to avoid duplicating this for every future request.

Cookie settings:
* sameSite = 'none'
* secure = true
* expires: 30m (doesn't matter that much)
* path: '/'.

Domain will probably have to be ifixit.com rather than www.ifixit.com so it works on next.ifixit.com before we go live.

**Comment by sterlinghirsh** [comment]
I think this should be working now. Are you still running into trouble with this?

**Comment by dhmacs** [comment]
@sterlinghirsh still looks like we have the same error we had last week:

<img width="1014" alt="Screenshot 2022-06-08 at 18 38 41" src="https://user-images.githubusercontent.com/4640135/172670580-09409be7-cc81-43ec-b6cb-daef80969b87.png">

To reproduce it, visit this [link](https://react-commerce-git-add-mini-cart-ifixit.cominor.com/Store/Parts) logged as a pro user, and try to checkout.

**Comment by dhmacs** [comment]
Hey @danielbeardsley, @masonmcelvain I didn't realize you had taken ownership over this task. I had already implemented the mini cart with csrf tokens (I've just opened #336).
I see you're trying to go with a different approach (not using CSRF) so I'm wondering, how do we move on with the mini cart PR?

**Comment by dhmacs** [comment]
@sterlinghirsh told me that origin validation should not affect the mini cart PR, eventually we'll drop the code related to CSRF 👍

**Comment by masonmcelvain** [comment]
Sorry for not communicating with you @dhmacs. Yes, we are dropping CSRF tokens eventually, but the mini cart code should be able to make POSTs to our PHP app just fine with what you implemented. I think the plan is to check the Origin header instead of using CSRF tokens, and provide any necessary exemptions for the Next.js app.
