### ISSUE TITLE
`FeaturedProductLists` improvement on `Browse` component

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#272]
I'm building out the New Store Homepage. Two major limitations found while working with `FeaturedProductLists` in the `Browse` component. 

1) Do not limit `FeaturedProductLists` to 10 items. 

 I want three rows of three items in the `Browse` component. I added 12 items to `FeaturedProductLists`:

![image](https://user-images.githubusercontent.com/7053450/166342760-cd0c6c90-0072-4c49-a00d-b53c1228ed3c.png)

I only get 10 items: 

![image](https://user-images.githubusercontent.com/7053450/166342793-4d161147-2c10-490e-901e-37a57bf91a8d.png)

After much troubleshooting I realized that only the first 10 items (sorted by ProductList ID) are showing up. Removing an item allows the next available item (sorted by ID) to show up: 

![image](https://user-images.githubusercontent.com/7053450/166342975-e72cbc0b-d3ea-4ffa-ba08-9f190dd4cb6e.png)

![image](https://user-images.githubusercontent.com/7053450/166343020-4812f04e-1a1f-46c7-816b-035d8df1f19c.png)

2) Allow sorting in `FeaturedProductLists`. 

Right now, items that show up in the `Browse` component are sorted by ProductList ID. So any new list page I want to link from FeaturedProductLists will always and only show up last. For purposes of having a pretty demo, I made heavy edits to random list pages to get items showing in the way I want. 

CC @dhmacs @sterlinghirsh

**Comment by sterlinghirsh** [comment]
@jeffsnyder is this still an issue? Looks like we have 3 rows now. Do we just need sorting or what?

**Comment by sterlinghirsh** [comment]
Looks like sorting is covered by the sortPriority field in strapi, so I'm going to close this and if you think there's more that needs work, we can reopen it.

**Comment by dhmacs** [comment]
@sterlinghirsh this task is related to the store home page, and has not yet been fixed. I think you might have confused it with the product lists categories on product list pages
