### ISSUE TITLE
Strapi API tokens break on deploy

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#275]
## Problem
We create strapi api tokens so our app can communicate with strapi, but these seem to break after strapi deploys. The key is still visible in strapi's list of api keys, but it doesn't work when our code tries to auth. It seems like this might be related to regenerating JWT_SECRET or API_TOKEN_SALT when we deploy. We've observed this on main.govinor.com and strapi.ifixit.com

## Do This
Make sure JWT_SECRET and API_TOKEN_SALT are maintained across deploys. Make sure api access continues to work after deploying.

**Comment by dhmacs** [comment]
@sterlinghirsh It seems like (at least recently) the `API_TOKEN_SALT` is correctly persisted across deploys. How often does the token cease to work? When was the last time that is was invalid? Can you share with me what's the server response when the token doesn't work?

**Comment by sterlinghirsh** [comment]
I don't know how often it's happening, but @masonmcelvain hit a non-functioning token on main.govinor.com last week and I regenerated the key on 2022-05-04. IIRC it gave a 401 when the token didn't work. It's possible the bug was fixed before that and this is the last time we'll have to regenerate the key. I'll keep an eye out for if this happens again.

**Comment by danielbeardsley** [comment]
This has been fixed. I included the JWT token and the api token salt in the env file and it's stored in AWS secrets.

See pull: https://github.com/iFixit/server-templates/pull/3398

So they should have broken for the last time... tonight.
