### ISSUE TITLE
Add "Documents" section into collection page

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#28]
The collection page should have a "Documents" section that looks like this:

![Screen Shot 2021-06-23 at 14 28 27](https://user-images.githubusercontent.com/4640135/123096336-47e9fb00-d42f-11eb-895e-021faf326640.png)

## ❓Questions 
- [ ] What API should be used?
- [ ] Do this section apply to every collection? If not, how do we know if we have to display it or not?

**Comment by kwiens** [comment]
Let's not do this for v1.
