### ISSUE TITLE
Bug: Fix "Fix Kits" link in header

### ISSUE THREAD

**Issue by lithobraking** [iFixit/react-commerce#280]
The "Fix Kits" option in the header menu links to `next.ifixit.com/Store/Kits` when it should actually lead to `www.ifixit.com/Kits`. The current link 404s because the page doesn't exist.

https://user-images.githubusercontent.com/34843669/167173124-01f3889e-9489-4f50-b433-409016d2d69f.mp4

## Do This
Update the Fix Kits link to direct to https://www.ifixit.com/Kits. 

<details><summary>This is the correct page</summary>

![Screenshot 2022-05-06 092843](https://user-images.githubusercontent.com/34843669/167173988-080bc221-4e57-4065-b942-bd74ec226ec1.jpg)

</details>

**Comment by dhmacs** [comment]
@lithobraking I've updated the link on strapi.ifixit.com 🚀  These kind of things are usually data related, not code related
