### ISSUE TITLE
Strapi: The docker image is 3GB, this is very big

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#296]
Do This
===
Find a way to trim down the docker image while it's being built

**Comment by djmetzle** [comment]
Interesting. There's a tool we can use to figure out whats going on...

**Comment by djmetzle** [comment]
Im peeking at this with [`dive`](https://github.com/wagoodman/dive), and the image looks like its around 1.2GB, not 3GB. Not sure where we're seeing that?

**Comment by djmetzle** [comment]
I figured out how to shave a significant amount of bytes off of the image

**Comment by danielbeardsley** [comment]
> Not sure where we're seeing that?

That's good to hear!

Docker spit it out after building the image. Something like:

"Finished building and pushing, size: 2834" (which I assumed was MB).

Maybe AWS squashed some of the layers or compressed it or something. Or that size wasn't what I thought it was.
