### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#300]
We need to setup Analytics so that we're not losing insights when we launch the new product list page. It seems that currently iFixit is on a migration from Google Analytics to [Matomo](https://matomo.org/).

What's the current setup? Should we only use Matomo? What do we want to track?

cc @sterlinghirsh @ifixitmaxb

**Comment by sterlinghirsh** [comment]
Let's try to get both GA and Matomo
