### ISSUE TITLE
Report next.js errors to Sentry

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#302]
[`sentry--setup-in-react-commerce`](https://github.com/iFixit/react-commerce/compare/sentry--setup-in-react-commerce)

I hit a 500 on next.ifixit.com the other day, and Metz had to go into AWS logs to figure out why it was failing. Let's report errors to Sentry. It might be nice to report dev errors too, as long as they're in a separate project.

**Comment by dhmacs** [comment]
@sterlinghirsh can I have access to your Sentry account to set this up?

**Comment by sterlinghirsh** [comment]
Sent invite
