### ISSUE TITLE
Images from Strapi not loading

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#303]
On https://next.ifixit.com/Store/Parts, we have manually set images in Strapi for sub categories like Mac. It appears that the response from Strapi is only giving the path as `/uploads/imac_d8ebc98f54.png`. We pass that to next.js, which results in `https://next.ifixit.com/_next/image?url=%2Fuploads%2Fimac_d8ebc98f54.png&w=384&q=75` which gives a 500 response with the message `"url" parameter is valid but upstream response is invalid`.

I tried adding https://strapi.ifixit.com to the front of the url. Visiting it directly works https://strapi.ifixit.com/uploads/imac_d8ebc98f54.png but next.js refuses to render it. https://next.ifixit.com/_next/image?url=https%3A%2F%2Fstrapi.ifixit.com%2Fuploads%2Fimac_d8ebc98f54.png&w=384&q=75 gives a 400 error with the message `"url" parameter is not allowed`

**Comment by dhmacs** [comment]
@sterlinghirsh I think this might be due to some miss configuration in Amplify (When using Vercel I see image correctly). One reason might be that Amplify does not set [rewrites](https://github.com/iFixit/react-commerce/blob/1d56748748178b0094b18066bc4dc07fa18c9bd7/frontend/next.config.js#L16-L23) correctly? It would be good to have more logs from AWS to understand where it's breaking.

**Comment by sterlinghirsh** [comment]
@djmetzle @andyg0808 do you have any ideas here?

**Comment by djmetzle** [comment]
I'm not familiar with any of that.

**Comment by danielbeardsley** [comment]
Firstly, I'm going to look into if we have permanent storage of strapi images set up correctly.

**Comment by dhmacs** [comment]
@danielbeardsley we need to setup a provider for AWS S3 I think ([see here](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#using-a-provider))

**Comment by danielbeardsley** [comment]
> need to setup a provider for AWS S3 I think

Yes, been working on it (See #308)
