### ISSUE TITLE
Get images for ProductList children that aren't children of the device

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#304]
## Problem
We have some instances where we set up ProductList children in a way that skips steps of the Device tree. For example, on Lenovo IdeaPad Parts https://next.ifixit.com/Store/Parts/Lenovo_IdeaPad we have a child IdeaPad 110-14AST. However, on the Lenovo IdeaPad Device page https://www.ifixit.com/Device/Lenovo_IdeaPad the immediate child is Lenovo IdeaPad 100 Series, and the grandchild is Lenovo IdeaPad 110-14AST. This difference is on purpose, since a we have guides for many IdeaPad 100 Series devices, but the only one we sell parts for is Lenovo IdeaPad 110-14AST, and we want to minimize extra steps in the navigation.

The way image loading is performed, we can't load the images except for the device's immediate children.

## Do This
After checking strapi and the current device's children, use the multiple-device lookup api defined in https://github.com/iFixit/ifixit/issues/43064 to fetch devices. If there are a very high number if devices to check, this may still have to be split up if we hit a length limit on urls or something.

**Comment by danielbeardsley** [comment]
Can you expand the Do This a bit?  I understand the problem (two separate hierarchies cause different sets of children for a given node). But I don't understand what we have already from Strapi and our existing api. This sentence uses "devices" three times and refers to I-don't-know-how-many different things:

> After checking strapi and the current device's children, use the multiple-device lookup api defined in iFixit/ifixit#43064 to fetch devices

Having the same terms "device" and "children" apply to two different hierarchies means it's hard to interpret statements.

I can make some guesses though:

Do This
===
The list of child-nodes we show on a given product list page sometimes don't match up with the list of device children in our ifixit.com hierarchy. For those nodes without pictures, query their information (in bulk) via the new API so we can get  images for them.

Have I interpreted that correctlty?

**Comment by danielbeardsley** [comment]
I'm going to effectively implement it like this:
![image](https://user-images.githubusercontent.com/26855/171814437-5faa20c3-88bd-464a-a22f-c1b143d688e7.png)

Is a change like this going to conflict with your current refactoring?

**Comment by dhmacs** [comment]
@danielbeardsley this should be fine 👍 The refactoring only involves filters and the product list (basically things that depends on Algolia)
