### ISSUE TITLE
Use product_group_en Algolia index

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#305]
## Problem
We can't get accurate counts on facet values because of the way algolia faceting works with combining product variant records into product group records with the algolia's `distinct` feature. This results in extraneous facet options showing up.

## Do This
Change the algolia index to the new product_group_en. This should avoid having to use `distinct` and fix facet value counts.

**Comment by masonmcelvain** [comment]
blocking on https://github.com/iFixit/react-commerce/compare/main...use-new-algolia-hooks

**Comment by sterlinghirsh** [comment]
I don't think this should be blocked by #13 . @masonmcelvain was that on purpose?

**Comment by masonmcelvain** [comment]
I intended to block it on the work @dhmacs was doing in https://github.com/iFixit/react-commerce/compare/main...use-new-algolia-hooks. If #13 is the wrong issue for that, feel free to change it

**Comment by dhmacs** [comment]
@masonmcelvain @sterlinghirsh #13 issue in the icebox, we weren't planning to ship that for v1 unless plans have changed. The work I'm doing on https://github.com/iFixit/react-commerce/compare/main...use-new-algolia-hooks, while it impacts #13, it's not aimed at closing it.
