### ISSUE TITLE
Images: Decide how to use next/image and on which images

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#314]
## Background
We will be using images from at least three different sources and they each provide images in a different way:

* Device images provided by the ifixit.com api
   * Urls are cloudfront backed by S3
   * Jpegs
   * Sizes and quality are specified by our code
* Product List images provided by strapi
   * Urls are S3 (we could add cloudfront)
   * Several Sizes are auto-generated by Strapi, this is configurable
* Product images provided by the algolia index
   * Urls are cloudfront backed by S3
   * Jpegs
   * Sizes and quality are specified by our code

## Problem
We have to decide when, where, and how to display these images (i.e. to use `react/image` or, some wrapper around it, or use it in simple `<img>` tag mode with no re-compression).

### ifixit.com Images

If we use `next/image` to auto-recompress and cache and store ifixit.com images, the request flow will look like this for ifixit.com images:

Browser -> Cloudfront -> Lambda -> Next (recompress) -> Cloudfront -> S3

This seems like unnecessary complexity and a potential loss in quality (double compression, double resampling) unless we use original size images, but that has even more performance concerns.

### Strapi images
Strapi generates a small handful of sizes by default, and that's configurable. It seems we have somewhat less control over strapi's image pipeline, so I'm more inclined to use `next/image` here with quality and size props.

![image](https://user-images.githubusercontent.com/26855/171485917-59ee5c8d-1d97-4e21-9a20-02177bfaf984.png)

## A Way Forward
Make an `<iFixitImage>` component and a `<StrapiImage>` component that can wrap whatever tech choice we make for each of these image types into a re-usable component. These components could also know about the standard sizes of our images and generate new urls given a GUID or base-url.

CC @sterlinghirsh

**Comment by sterlinghirsh** [comment]
https://aws.amazon.com/blogs/networking-and-content-delivery/resizing-images-with-amazon-cloudfront-lambdaedge-aws-cdn-blog/ Found this explanation of a way to do image resizing efficiently with s3.

**Comment by danielbeardsley** [comment]
Here's the next.js image component:
https://github.com/vercel/next.js/blob/4cbc61c740b6f8451cb024f44edc6b5c5ab4aa8a/packages/next/client/image.tsx

Here's a plugin that allows us to switch out the default image loader for one that can choose when to use next's image pipeline vs the source image url:
https://www.npmjs.com/package/next-image-loader
