### ISSUE TITLE
Collections: Add OEM Partnership Flare

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#316]
We need to advertise our OEM partnerships more prominently at all stages of the shopping experience. Let's add flare to the product card on Collections pages. 

1) Add Akeneo attribute `oem_partnership` to the Algolia index. We need to use the localized option labels of the attribute, not the option code. We need to this to be Variant-level data. 
2) Whenever `oem_partnership` is on a Variant, show flare similar to the Lifetime Warranty flare with the localized option label as the text of the flare. `oem_partnership` flare should be first in order. I don't have an opinion about the color of the tag (er, I don't know if we're styling tags differently .. in any case I don't have a strong opinion). 

![image](https://user-images.githubusercontent.com/7053450/171547650-c48bdf74-f137-4e2a-b639-89216c6ae8f8.png)

CC @dhmacs @sterlinghirsh @kwiens

**Comment by dhmacs** [comment]
Move into blocked on iFixit as this requires some work on the index

cc @sterlinghirsh

**Comment by masonmcelvain** [comment]
This might also be blocked by https://github.com/iFixit/react-commerce/compare/main...use-new-algolia-hooks, I see that there is a new [ProductList.tsx](https://github.com/iFixit/react-commerce/compare/main...use-new-algolia-hooks#diff-4bf3d5456fbb4f8b322ea96e4eeefdd73e1c42844fb930ca579c2e1c4888731a) file

**Comment by dhmacs** [comment]
That's right @masonmcelvain 👍
