### ISSUE TITLE
Intermediate collection page content

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#32]
Currently many intermediate collection pages have no products. Initially we discussed about alternative ways to display these collections due to difficulties in populating them. It seems now that @evannoronha was able to overcome those issues and we can have products on all collections.

So the questions are:

- Can we confirm that all collections will be populated?
- If so, what's the ETA for that?
- If we're not populating all collections, what are we going to show? Just the subcategory collections?

**Comment by dhmacs** [comment]
Hey @evannoronha, what's the progress on this? 
For testing purposes I'd like to have at least the "parts" collection populated

**Comment by kwiens** [comment]
@evannoronha Will intermediate collections with no products ex: https://react-commerce-ifixit.vercel.app/collections/mac-mini be solved with the new import?

**Comment by evannoronha** [comment]
This is resolved.
