### ISSUE TITLE
Make strapi respond tool pages case-insensitively

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#327]
Like /Tools/gripping vs /Tools/Gripping

The canonical should be what's set in Strapi (ideally /Tools/Gripping) and we should redirect to the canonical. We'll have to be sure to preserve any url params.

**Comment by dhmacs** [comment]
@sterlinghirsh We might incur into duplicate content penalty since path are case sensitive. What do you about redirecting from the lowercase to the uppercase?

**Comment by sterlinghirsh** [comment]
Yes, redirecting to the canonical is the right thing to do here.
