### ISSUE TITLE
Build product page MVP

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#329]
Build a production-ready product page with all the required features to go live

## Questions on data

1. Where do we source breadcrumb data?
    <img width="707" alt="Screenshot 2022-06-23 at 15 39 16" src="https://user-images.githubusercontent.com/4640135/175312924-e3e774da-4c06-474a-9ccc-75f8aa401bda.png">

2. How do we source kit content?
    <img width="606" alt="Screenshot 2022-06-23 at 15 38 25" src="https://user-images.githubusercontent.com/4640135/175312733-de713711-e67e-4491-ab27-5dfd7855099d.png">

3. How do we source compatible devices?
    <img width="507" alt="Screenshot 2022-06-23 at 15 39 43" src="https://user-images.githubusercontent.com/4640135/175313042-73f0069b-fcf3-40f7-ae9d-41577830a16b.png">

4. How do we source product specs? 
    <img width="597" alt="Screenshot 2022-06-23 at 15 42 11" src="https://user-images.githubusercontent.com/4640135/175313567-1f2d12a7-564d-4de4-873c-276b272a8a7b.png">

5. How do we source the warranty type?
    <img width="510" alt="Screenshot 2022-06-23 at 15 43 51" src="https://user-images.githubusercontent.com/4640135/175313955-79b15ada-81c5-45c1-9a8e-b1af103ecaa8.png">

6. How do we source these product details?
    <img width="590" alt="Screenshot 2022-06-23 at 15 44 08" src="https://user-images.githubusercontent.com/4640135/175314021-9c3c083b-003f-4129-abfe-30f22448c31d.png">

7. How do we retrieve devices from the workbench and verify if they're compatible with the product?
    <img width="802" alt="Screenshot 2022-06-23 at 15 48 04" src="https://user-images.githubusercontent.com/4640135/175314899-2ad6a053-65b3-427f-851f-367a2d8a49f6.png">

Probably a viable solution for most of this things is to create a metafield and sync these details via metafields. Obvious exceptions to this might be the device compatibility list which potentially might be to big to be stored in a metafield

**Comment by sctice-ifixit** [comment]
@sterlinghirsh and I are working through these. We agree that most of this will probably be in metafields (some of it already is). We'll start working on getting the data in place this next sprint, starting Wednesday.

**Comment by dhmacs** [comment]
@sctice-ifixit awesome! Sterling showed to me that some of this data is on variant metafield, so I'm gonna wire those up 👍

**Comment by sctice-ifixit** [comment]
Here's what @sterlinghirsh and I came up with. We're going to be working on the ones marked TODO over the next two weeks. Depending on how things go, we'll get to the value proposition components soon after, but there are more unknowns there in how we want to build the data. We need to work things our more concretely with Jeff Snyder.

- __TODO__: Breadcrumb data
  - Start from current product page behavior
  - Probably a product group metafield with type `json` and contents: `[{url, title}, ...]`
- Kit contents
  - HTML rendered from wiki text, already in a variant metafield (`kit_contents`)
  - We can't really make it look exactly like the mock-up
- __TODO__: Compatible devices
  - Ideally a product group metafield, but we need to experiment to see if we run into the 65535 "character" limit (unclear if it's bytes or characters)
    - Contents `{table: [{image_url, device_title, device_url, variants: [variant, ...]}, ...]}`
      - `device_title` should be the display title
      - `device_url` could be collection page or device page
  - Right now, compatibility is a variant metafield (`compatibility`) that comes from `worksinid` in the DB.
    - Doesn't need to be at the variant level; it's always set at the group level in Akeneo
- Product specs
  - Already a variant metafield with HTML from the raw data: `specifications`
  - Might need to teak the HTML
- Warranty
  - Already a variant metafield: `warranty`
  - We set a translated UI string right now. Medium term, we should probably set an enum value and translate in the component
- Product details
  - Prop 65 stuff comes from existing product group metafields: `prop_65_warning_type`, `prop_65_chemicals`
  - Product videos come from another product group metafield: `product_videos`
- Workbench compatibility
  - iFixit API request

Other components:

- __TODO__: Replacement Guides
  - Currently from `/api/2.0/cart/product/infoForStore`
  - Probably should be a product group metafield
- __TODO__: Value propositions (e.g., same day shipping)
  - Probably should be a product group metafield with contents like `[{icon, title, desc}, ...]`
    - Maybe get a base set from Strapi, customize from Akeneo attributes
- Notes after product description
  - Currently variant metafields containing HTML: `warning`, `disclaimer`, `note`

Next sprint:

- Breadcrumbs
- Compatible devices

**Comment by dhmacs** [comment]
I'm looking into how to add the prop 65 warning, which on the current site looks like this:

<img width="424" alt="Screenshot 2022-07-11 at 16 36 48" src="https://user-images.githubusercontent.com/4640135/178289584-8d8fa90e-7400-49c8-b214-9aa67a9d272d.png">

These are the details that I can grab from the metafield:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/4640135/178289861-5c7df37e-a92e-4b4b-9740-8c0f02b90f3e.png">

Should I hard code a message that is parameterized with these details?


cc @sctice-ifixit @sterlinghirsh

**Comment by dhmacs** [comment]
Other question, there's a metafield `product_videos`, which is plural. Does it mean that there can be more than 1?

**Comment by dhmacs** [comment]
@sterlinghirsh @sctice-ifixit 

What is this markdown-like syntax? What I'm supposed to do with it? Should I parse the text for these and replace them with something else?

![image](https://user-images.githubusercontent.com/4640135/178436583-8985af9c-f40b-496c-ab06-2792fad88e8e.png)

**Comment by dhmacs** [comment]
> Yes, the logic supports setting 2+ in the metafield. They should be comma-separated. [Here's an example of a product with 2 videos](https://www.ifixit.com/Store/iPhone/iPhone-5-and-5c-Home-Button/IF118-051?o=5).

Ok, we've added a definition for this metafield that accounted for just one video (in the test store). How hard is it to create a new metafield to and sync product videos with it?

> Hm, that looks like a bug or an artifact in the dev environment. The only place in code I'm seeing that kind of syntax is in a test mock, where we generate that text instead of actually going and looking up the product name. 

We discussed this yestarday during our call, and they said it's a bug, and is there for testing purposes

**Comment by sterlinghirsh** [comment]
Good find on the product with two videos. Interesting to note that on the canada store, that product only shows one video though: https://canada.ifixit.com/products/iphone-5-and-5c-home-button . Looks like we do in fact send both videos concatenated in the metafield `https://www.youtube-nocookie.com/embed/lu6sjxZN_vI?wmode=opaque,https://www.youtube-nocookie.com/embed/BwU_R1stbIE?wmode=opaque` but I'm not sure a single URL metafield will handle that. If we have thousands of products and <1% have two videos, I don't really want to put much time into supporting that case.

> How hard is it to create a new metafield to and sync product videos with it?

Not hard at all

**Comment by sterlinghirsh** [comment]
We're going to change it to only send a single video instead of two urls. There was only one product with two videos anyway.

**Comment by dhmacs** [comment]
This can be considered done
