### ISSUE TITLE
Bifurcate responses based on logged-in status

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#337]
## Problem
When a user is logged in, they may get customized search results from Algolia. For example, a pro user is able to see pro products, while a logged out user or normal-privilege user is not. We need to take the logged-in status into account when generating and caching server-rendering pages. We want to be able to cache the logged out / normal user case, but still be able to support a good UX for pro users.

## Do This
Set up the cache so that logged out users are served a cached fully rendered page. Logged in users can either get a skeleton page to be filled in client-side or a rendered page that isn't cached.

**Comment by dhmacs** [comment]
@sterlinghirsh can you clarify what you mean by "cache" ? If you're referring to the CDN cache than this means that we would have to write custom code on the edge to detect whether or not the user is logged in an and send back a response accordingly.

The approach that we've taken so far is to always serve the "public" version of the page that can be easily cached by the CDN, and change it client side for a pro user

**Comment by danielbeardsley** [comment]
I think we're going to try swapping out the API key on the front-end first, so hold off on this.

**Comment by sterlinghirsh** [comment]
Not going to do this for now.
