### ISSUE TITLE
Collection descriptions don't match the collection

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#34]
Most collection descriptions are not related to the collection, for example:

![image](https://user-images.githubusercontent.com/4640135/123405832-848e3180-d5aa-11eb-9239-460fc7830e76.png)

- https://react-commerce.vercel.app/collections/iphone
- [iPhone collection on Shopify](https://ifixit-test.myshopify.com/admin/collections/261650284634)

**Comment by dhmacs** [comment]
I'm posting here as an update the answer I got from @evannoronha on Slack

> This is actually not a bug. We just have poor data on the ifixit side of things. That content is generally in a pretty low-priority spot on the page and so-far has been forgotten.

**Comment by kwiens** [comment]
@evannoronha What do you mean? Is this because there isn't a product list page for 'iPhone'? Can you provide some links?

**Comment by kwiens** [comment]
Assuming this is solved / will be solved in the new import.
