### ISSUE TITLE
Refactor cart sdk sso route generation

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#346]
From https://github.com/iFixit/react-commerce/pull/336#discussion_r899178351

Currently the sso route to redirect to checkout is hard coded to:

```ts
const ssoRoute = `${appContext.ifixitOrigin}/User/sso/shopify/ifixit-test?checkout=1`;
```

This needs to be parametric based on the store where we checkout. In Strapi we're storing the store domain, which for `ifixit-test` is `store.cominor.com`.
The first solution that comes to mind is that we need to store the shop name alongside the store domain, but before doing that I want to make sure that we could not use the store domain instead (i.e. `store.cominor.com`).

Thoughts @sterlinghirsh ?

**Comment by sterlinghirsh** [comment]
I opened a pull to allow specifying the store by store.cominor.com instead of ifixit-test. https://github.com/iFixit/ifixit/pull/43509
