### ISSUE TITLE
Auto-Generate Filtered Parts Lists

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#354]
When a user visits `/Parts/MacBook_Pro` they see all MacBook Pro parts. When they visit `/Parts/MacBook_Pro/Batteries` they should see just batteries compatible with MacBook Pros. Whatever value is in the third URL path element should be interpreted as an item type. The text on the page should be the same, but the title should become `{$deviceTitle} {$itemType}`. More specifically, this should probably just replace "Parts" with `$itemType` to preserve any title customizations. The item type filter should be shown in the list of active filters as if it were any other.

Clicking the item type search refinement should change the path but maintain the other filters. Clearing the filter should return you to `/Parts/MacBook_Pro` but maintain any other filters.

**Comment by dhmacs** [comment]
@sterlinghirsh As defined in our previous call, item type facet will be displayed like a menu:

![Screenshot 2022-06-29 at 16 14 17](https://user-images.githubusercontent.com/4640135/176458613-419bd9cd-762f-45b9-b9a3-fcb34b9ab6e0.png)

This behaviour applies for device product lists (e.g. `/Parts/iPhone/Batteries`). Now, how should we handle `Item Type` facet for all other product lists (such as Parts root product list, or tools product lists)? Do we hide it, or display it like all other facets (i.e. list of checkboxes)?
