### ISSUE TITLE
Images: Choose best size for Guide / Cart images

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#361]
We now have an `IfixitImage` (#350) component. We want that component to be smarter about when to use *which* size of image. The component is provided with a width (and maybe height?)

### Do This
Augment the component to use a [*loader*](https://nextjs.org/docs/api-reference/next/image#loader) for each type. Have the loader choose the smallest size image that's bigger than the required size. It'll need to strip the extension off the image url so it can add an extension of its own.

We'll want to hard-code the list of image sizes for both [GuideImages](https://github.com/iFixit/ifixit/blob/1f6503c27b20c6edb1f76817f88daa0b1a676993/Guide/Libs/GuideImageLib.php#L34-L44) snd [CartImages](https://github.com/iFixit/ifixit/blob/1f6503c27b20c6edb1f76817f88daa0b1a676993/Cart/Libs/CartImageLib.php#L25-L38).

CC @sterlinghirsh

**Comment by jarstelfox** [comment]
[One can dream](https://ishadeed.com/article/say-hello-to-css-container-queries/)

**Comment by sterlinghirsh** [comment]
Using a large image and shrinking it in the browser is causing us to have jagged edges in some photos.

**Comment by sterlinghirsh** [comment]
Also, I noticed we're resizing jpgs, but it wasn't clear if we were resizing pngs too.

**Comment by danielbeardsley** [comment]
> Using a large image and shrinking it in the browser is causing us to have jagged edges in some photos.

Can you give an example link?  Are you saying that the downsampling done by the browser (when there are more image pixels than screen pixels) is poorer than you'd expect from a library run on the backend?

**Comment by sterlinghirsh** [comment]
On this page https://es.ifixit.com/Tools the image for "Drivers and Wrenches" (a toolkit with some diagonal lines) has some jaggies especially visible at 1080p@100% but still visible at 4k@200%. Switching the image for the thumbnail size results in much better antialiasing.

medium (current)
![image](https://user-images.githubusercontent.com/589425/177860571-c2935065-a861-4de3-85af-132af002f352.png)

thumbnail (proposed)
![image](https://user-images.githubusercontent.com/589425/177860771-cd37aaef-9dfd-4f61-9f10-096483774584.png)

**Comment by danielbeardsley** [comment]
Here it is at normal-screen size (not 200% zoom):

Original (300px):
![image](https://user-images.githubusercontent.com/26855/177887391-80abfc2f-4628-4c76-a873-b2446d3437e9.png)

Strapi's thumbnail size:
![image](https://user-images.githubusercontent.com/26855/177887503-c696bfc4-c17a-4974-be37-1e238ba78a93.png)

Next's Image Resizing service (at 96w)
![image](https://user-images.githubusercontent.com/26855/177888872-d7f82eb8-d8f0-4218-827a-5462ee2e7904.png)

Next's Image Resizing service (at 128w)
![image](https://user-images.githubusercontent.com/26855/177889152-f4fab77b-8af3-44c5-9a4b-c7dff470056b.png)

The diff is a lot closer, but I still think I prefer the original as it looks sharper and less blurry. That said, we should still be choosing an appropriate size here (I think we're opting for `large` here) so I'd for just using the default loader for strapi images.

**Comment by jyee27** [comment]
I'm running into a bit of a weird issue here on my branch: https://github.com/iFixit/react-commerce/tree/images--choose-best-size-guide-cart
Everything works and we're generating a `srcset` for Guide and Cart images, but I'm getting a flood of warnings in the console:
```
[dev:frontend] [Next] Image with src "https://ravenm.cominor.com/cart-products/mpGGoXnHrCDUVmYp.standard" has a "loader" property that does not implement width. Please implement it or use the "unoptimized" property instead.
[dev:frontend] [Next] Read more: https://nextjs.org/docs/messages/next-image-missing-loader-width
[dev:frontend] [Next] Image with src "https://ravenm.cominor.com/cart-products/tCyxR4RI61WuHKDF.standard" has a "loader" property that does not implement width. Please implement it or use the "unoptimized" property instead.
[dev:frontend] [Next] Read more: https://nextjs.org/docs/messages/next-image-missing-loader-width
...
```
Looking into the source, it looks like Next is being overly helpful and warning because of cases where the loader isn't changing the `src` because we were already giving `standard` size as the `src` before the loader:
https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx#L594-L602

There doesn't seem to be a way to suppress this warning.
