### ISSUE TITLE
Analyze performance bottlenecks

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#379]
We want to understand why the navigation from a page to another one sometimes takes much longer than expected

**Comment by federicobadini** [comment]
We focused on the `/Parts` subtree.

The `/Parts/index.tsx` and the `/Parts/[handle].tsx` pages execute `getServerSideProps`. 
For first loads the function executes during the page generation. For successive client side navigations the client stucks waiting for the function to complete making the issue more evident.
We disabled vercel cache headers and executed some time profiling activities.

For multiple page loads in a short time window [results](https://docs.google.com/spreadsheets/d/1mIWEz76MAUPAzQ-yxoOaIU99nItdPZ3aWdJd0QKlJdo/edit?usp=sharing) were pretty uniform. 
However we noticed that if not pinged for a few minutes, queries to the `fetchDeviceWiki` api seems to take longer - **sometimes much longer** - than usual:

```
getStoreList: 1.612ms
getStoreByCode: 1.67ms
getGlobalSettings: 2.33ms
getProductList: 281.607ms
fetchDeviceWiki: 7.949s
createPublicAlgoliaKey: 0.898ms
fillMissingImagesFromApi: 0.012ms
findProductList: 8.232s
Promise.all: 8.233s
getServerState: 1.067s
getServerSideProps: 9.301s
```

That should be the first thing to investigate upon.
Then we should also investigate on the reason why `getServerState` is taking almost always ~1s.

**Comment by federicobadini** [comment]
As discussed in the weekly alignment, @sterlinghirsh is going to perform some testing on the fetchDeviceWiki API to check these findings

**Comment by sterlinghirsh** [comment]
I looked into it a little and created a new issue to dig deeper and try to find some low-hanging fruit. https://github.com/iFixit/ifixit/issues/43776

**Comment by danielbeardsley** [comment]
I have an open pull to both illuminate this #457 and address some of it: #472

**Comment by sterlinghirsh** [comment]
Is anything still happening here? I'm going to close this, and if there's any remaining work, we can spin it off into new issues.
