### ISSUE TITLE
Differentiate between search bars

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#386]
### Problem
We have two search bars on the page that behave differently, but we don't have any clear indication that they will show different results (as opposed to two search bars on the homepage that do behave the same). IMO, the product search is a way better experience if you want to find a product. It's unclear that the header bar will redirect a user to results from the entire site. Also, the product search bar is well below the fold on mobile. 

<details><summary>The product search is responsive and immediately returns a direct link to the product page.</summary>

![image](https://user-images.githubusercontent.com/72166715/177390045-be586450-ab86-426d-9d01-e44c4d3d4bb5.png)

</details>

<details><summary>The header search redirects to https://www.ifixit.com/Search?query=querydetails, and store results aren't always the first results listed.</summary>

![image](https://user-images.githubusercontent.com/72166715/177390807-fed2cf4a-8278-4e8e-9739-2d0ef40f1900.png)

</details>

Without differentiation, customers could use the header search bar and miss the easy, effective search that we made for them.

### Do this
Feature the product search more. Somehow differentiate between the two in the UI. Maybe different placeholder text for one or both of the search bars? Both search bars have placeholder text = `Search`.

**Comment by sterlinghirsh** [comment]
Let's make the product search bar's placeholder say "Search {title}" as in "Search iPhone 7 Parts"

**Comment by erinemay** [comment]
> Let's make the product search bar's placeholder say "Search {title}" as in "Search iPhone 7 Parts"

This also addresses another side of the search bar differentiation that we've been seeing in user testing: It's unclear that the product search bar only applies to the current, nested category.

**Comment by sterlinghirsh** [comment]
@erinemay I created #401 to hopefully smooth out the search confusion.

**Comment by dhmacs** [comment]
cc @mmarcon91

**Comment by mmarcon91** [comment]
I agree with @sterlinghirsh's solution
