### ISSUE TITLE
Update product-list.json seed and add documentation

### ISSUE THREAD

**Issue by batbattur** [iFixit/react-commerce#387]
## Description
Currently the devices/models on `/Parts` page are different on [prod](https://fr.ifixit.com/Parts) and [dev](https://react-commerce.vercel.app/Parts). 
It looks like the data on dev are seeded from the files in [ `backend/src/plugins/seed/server/seed` folder](https://github.com/iFixit/react-commerce/tree/main/backend/src/plugins/seed/server/seed/data). 

I'm adding cypress tests for the collections pages in https://github.com/iFixit/ifixit/issues/43590 and would like the data/behavior on dev to be same as prod. I couldn't find any documentation on how to update the [`product-list.json` seed file.](https://github.com/iFixit/react-commerce/blob/main/backend/src/plugins/seed/server/seed/data/product-lists.json)

|dev|prod|
|-|-|
|![dev](https://user-images.githubusercontent.com/58952979/177428887-9f7b7bd1-bd5a-44dd-b392-7e7077734e8d.PNG)|![live](https://user-images.githubusercontent.com/58952979/177428890-8df05a83-896d-4e4a-9e8a-a587c5afbfff.PNG)|

## To do
1. Document how to update the seed files with the most recent data.
2. Update `product-list.json`.

cc: @dhmacs @sterlinghirsh

**Comment by sterlinghirsh** [comment]
Not sure how feasible it is, but it would be nice if we could pull down a copy of the live data instead of hard-coding the seed data. If not, let's make sure to add some tool collection pages to the seed.

**Comment by dhmacs** [comment]
This has been addressed by #611
