### ISSUE TITLE
Text rendering artefacts

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#389]
We're seeing some strange effects on text. This doesn't seem to happen on other pages. Maybe this is related to some css having to do with antialiasing or something. This was noticed by @jeffsnyder at 100% scaling at 2160x1440, but it doesn't show on my screen at 200% 4k.

![image](https://user-images.githubusercontent.com/589425/177433130-24a54a5c-9766-430a-a9a1-42e027fd6535.png)
![image](https://user-images.githubusercontent.com/589425/177433140-2b234aed-460a-4b18-bc64-88ac481c458d.png)

**Comment by federicobadini** [comment]
There is no explicit reference in our code to either the non standard [`font-smooth`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth) property or the [`text-rendering`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering) property.

Libraries and default stylesheets introduce some declaration of those properties - both standard and vendor-prefixed.
The final set of active properties seems coherent though (at least on my OS and browser)

<img width="265" alt="Screenshot 2022-12-29 at 12 32 14" src="https://user-images.githubusercontent.com/7805759/209945379-8f6b8acd-3a29-4417-a4d7-7032bc1cb7d1.png">

If you look at the browser compatibility table of `text-rendering`, different browsers may imply different defaults and sometimes different interpretation of the same associated value.

So - if this is still happening - it would be very useful to know which configuration triggers this problem.

**Comment by kwiens** [comment]
Can't reproduce.

**Comment by jeffsnyder** [comment]
I still see the artifacts. I am unable to reopen this issue but I believe it needs to be solved. I see this in Chrome, I do not see it in Firefox. Happy to provide more info, but I'm not sure what specifically you need. Here are the properties I see on the div in the ProductList scereenshot above:

![image](https://user-images.githubusercontent.com/7053450/210886388-b809da95-710d-498d-814e-ae4e443ab42e.png)

**Comment by sterlinghirsh** [comment]
I see it too and it's annoying.

**Comment by federicobadini** [comment]
> I see it too and it's annoying.

@sterlinghirsh Are you seeing this on your device too? 
If so, do you have any further hints in order to try to reproduce it? Maybe something you and @jeffsnyder have in common in terms of OS, browser versions, screen resolution etc

**Comment by sterlinghirsh** [comment]
It shows up for me when I'm at 100% scaling at 4k on my big screen but not 200% scaling at 4k on my small screen. I'm on Windows 10 on Chrome.

**Comment by sterlinghirsh** [comment]
Just messed around with it. It repeatably happens for me that the Ps look wrong on our main body text on this page https://www.ifixit.com/Parts which is almost certainly an antialiasing problem. Switching from 16px font-size to 17px fixes the Ps but breaks the As and Es. 
![image](https://user-images.githubusercontent.com/589425/211086174-e27095d2-65bc-4bf4-af50-9a8c6e2d670a.png)

This is also fixed when we use the default system font, which indicates to me it may be problem with the font itself (perhaps some optimization). In any case, if we switch font stacks, this will probably be resolved, so I'll close this for now.
