### ISSUE TITLE
Sort and hide Facets

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#390]
[`sort-and-hide-facets`](https://github.com/iFixit/react-commerce/compare/sort-and-hide-facets)

Algolia's Facet Display doesn't work for nested facets like facet_tags. We'll have to sort them in code.

On Parts pages:
* Item Type
  * Alphabetize
* Part or Kit
* Remaining facets sorted alphabetically
  * Values sorted by number of hits unless otherwise specified (i.e. Capacity)

On Tools pages:
* Tool Type
* Price Range

**Comment by masonmcelvain** [comment]
The issue title is `Sort and hide Facets`, but hiding isn't mentioned in the description. When should facets be hidden?
