### ISSUE TITLE
Refine search results in auto-generated item-type product lists

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#391]
In https://github.com/iFixit/react-commerce/pull/380, we added item type product lists, like https://d3lnoy3aplwg2k.cloudfront.net/Parts/iPhone/Batteries. 

Searching for the item type on the category product list provides better search results than viewing these item-specific pages. 

Examples:

<details><summary>iPhone Batteries</summary>

Item product list: https://d3lnoy3aplwg2k.cloudfront.net/Parts/iPhone/Batteries
- Contains battery products for other devices besides the iPhone

Search equivalent: https://d3lnoy3aplwg2k.cloudfront.net/Parts/iPhone?q=Batteries
- Contains only iPhone battery products

</details>

<details><summary>iPhone Cables</summary>

Item product list: https://d3lnoy3aplwg2k.cloudfront.net/Parts/iPhone/Cables
Contains products I probably don't care about if I'm looking for a cable.

![image](https://user-images.githubusercontent.com/72166715/177431983-930c9e9b-2cd3-4865-9d4e-47f7d2ed6a14.png)

Search equivalent: https://d3lnoy3aplwg2k.cloudfront.net/Parts/iPhone?q=Cables
Has more relevant results. 
![image](https://user-images.githubusercontent.com/72166715/177431940-4f4c4fee-c18c-4dbf-a966-47d40705c47a.png)

</details>

**Comment by erinemay** [comment]
Another clear example:
https://d3lnoy3aplwg2k.cloudfront.net/Parts/Vacuum_Cleaner/Batteries
![image](https://user-images.githubusercontent.com/72166715/177609388-e40634c2-62c6-4a91-a48c-e9da89cd3c4d.png)

**Comment by dhmacs** [comment]
This is probably due to [Configure](https://www.algolia.com/doc/api-reference/widgets/configure/react-hooks/) component that if used multiple times in the DOM it doesn't add up all the filters, it just keeps the last one encountered.
I didn't notice this before. The fix should be to combine the two instances where `Configure` is used into one.
