### ISSUE TITLE
Managing ProductList Descriptions in Strapi

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#396]
Two pain points discovered while reviewing ProductList in Strapi with @sterlinghirsh . We decided we should create an issue to document the frustration, but we don't know what can actually be done or if the work would be worth the outcome. 

1) We can't filter by Description in ProductList

![image](https://user-images.githubusercontent.com/7053450/177606700-6bff99eb-af3b-41c3-80cf-0b7594a582b7.png)

It looks like the general search option includes "Description" in the search. 

![image](https://user-images.githubusercontent.com/7053450/177606974-22660344-9793-4e0a-99de-14d7cd194381.png)

But the search is looking in multiple attributes, not _just_ the Description. 

2) We can't see Description in the ProductList view / can't add it to the view.

![image](https://user-images.githubusercontent.com/7053450/177608757-fee79bb8-37bf-44e2-8f2c-d2868e27ccac.png)

![image](https://user-images.githubusercontent.com/7053450/177608625-efce1bf5-aa92-49d5-a4df-4c5bad283658.png)

These two items in combination mean that if I'm looking to update a specific phrase in a ProductList description, I have to search for the phrase and potentially get more results than I want and then manually click through the search results to find what needs updating. The immediate need I have can be solved by the search feature (the phrase I'm searching is specific enough) but this will come up again, especially when we start building out bulk update features. 

CC @dhmacs @sterlinghirsh

**Comment by dhmacs** [comment]
@jeffsnyder over time I came to realize that Strapi collection search is a little bit silly, but unfortunately I don't have an answer yet for that. I'll research more about this topic and see what can we do to improve the UX here
