### ISSUE TITLE
ProductList `relatedPosts` issues

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#400]
1) Dates are incorrect. All items have today's date. 

![image](https://user-images.githubusercontent.com/7053450/177618847-faeae7a9-9141-46b7-b8c6-2720ec6ff5b4.png)

2) We should _never_ include offsite links, even if it's to our own offsite content (Right @kwiens ?)

This item on `/Parts/iPhone` links off to YouTube:

![image](https://user-images.githubusercontent.com/7053450/177618961-387acbe3-988d-460d-85f1-e76d262b54d4.png)

3) We should not include non-English items in `relatedPosts`. (Or we should filter items by the user's language preference.)

From `/Parts/iPhone_11`: 

![image](https://user-images.githubusercontent.com/7053450/177619402-a786f9f7-e5ee-4184-b200-735069f67741.png)

4) Finally, a question: How do these tags work? What are we matching against? 

![image](https://user-images.githubusercontent.com/7053450/177620136-4b4f85a4-61d4-4ce5-ad0f-cdac7a90ca04.png)

CC @dhmacs @sterlinghirsh @kwiens

**Comment by dhmacs** [comment]
> 1. Dates are incorrect. All items have today's date.

Fixed in #419 

> 3. We should not include non-English items in `relatedPosts`. (Or we should filter items by the user's language preference.)

The API call currently does not send languages. Let me know if we need to pass language preference to the api

cc @sterlinghirsh 

> 4. Finally, a question: How do these tags work? What are we matching against?

These tags are passed to the API, I would ask @sterlinghirsh how these are used on the backend

**Comment by jeffsnyder** [comment]
> The API call currently does not send languages. Let me know if we need to pass language preference to the ap

@dhmacs I think we must do this. @sterlinghirsh agree?

**Comment by sterlinghirsh** [comment]
Yes I opened a pull. https://github.com/iFixit/ifixit/pull/43737

This will use the current language subdomain to specify the language of related posts. I think that will work for now, though it will mean that if testing on es.ifixit.com, the results will be in Spanish.

**Comment by sterlinghirsh** [comment]
For external links like the youtube ones, maybe we can make them open in a new page.
