### ISSUE TITLE
Mini-Cart: Empty Cart emoji isn't rendering on Windows + Chrome Desktop

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#412]
![image](https://user-images.githubusercontent.com/72166715/177872981-0b99d88f-99d9-4c31-98ed-c3274661f1ba.png)

Confirmed not working on Windows 10 and lower on Chrome (102,103, and 104-beta). ❌ 

Confirmed working on:
- iOS + Safari ✔️ 
- Android + Chrome ✔️ 
- MacOS + Safari ✔️ 
- MacOS + Chrome ✔️ 
- Windows + FF ✔️ 

(All tested via Browserstack)

Also, are we sure the smiling/crying emoji is what we want here?
![image](https://user-images.githubusercontent.com/72166715/177873112-e7f831b0-2452-4ad3-8e39-82f928c23eb0.png)

## Do This
Make it a shopping cart icon

**Comment by dhmacs** [comment]
> Also, are we sure the smiling/crying emoji is what we want here? ![image](https://user-images.githubusercontent.com/72166715/177873112-e7f831b0-2452-4ad3-8e39-82f928c23eb0.png)

This was a temporary solution. @mmarcon91 will think about this

**Comment by danielbeardsley** [comment]
How about change it to just a slightly larger shopping cart icon?

**Comment by mmarcon91** [comment]
I created a new empty state with font-awesome icon : https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=284%3A17687
