### ISSUE TITLE
Top level breadcrumbs still link to /Store/path

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#413]
On https://es.ifixit.com/Parts/iPhone, the parent breadcrumb `All Parts` links to `/Store/Parts`. It should link to `/Parts`.
![image](https://user-images.githubusercontent.com/72166715/177874303-20e52fb0-053f-4fc4-9ad6-d99c8e707520.png)

Similarly, on https://es.ifixit.com/Tools/iFixit_Exclusives, `Repair Tools` links to `/Store/Tools`. It should link to `/Tools`.
![image](https://user-images.githubusercontent.com/72166715/177874261-d8d111a1-3801-4ee1-8a96-587a81bc70eb.png)

### Note:
Children breadcrumbs are correct. For example, on https://es.ifixit.com/Parts/Kindle_7th_Generation, each of the sub-category breadcrumb links are correct. Only the `All Parts` breadcrumb link contains `/Store`:
![image](https://user-images.githubusercontent.com/72166715/177874546-12dc3d95-1dfe-4372-9527-feda62ae99ad.png)

**Comment by danielcliu-ifixit** [comment]
This was an issue in the production level data. Changed `Repair Tools` type from `marketing` to `all-tools` to fix this issue. Parts already had this solution implemented.
