### ISSUE TITLE
Hidden mobile breadcrumbs aren't useful to users

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#415]
![image](https://user-images.githubusercontent.com/72166715/177877582-eadfa324-8714-4bc0-99a5-9c80ebd310e7.png)

## History
The breadcrumbs were abstracted behind the button with ellipses ⬆️ because they would get cut off on mobile and look bad. https://github.com/iFixit/react-commerce/issues/201

### TLDR 
The breadcrumb button is not obvious, and users got frustrated trying to figure out how to navigate back up the hierarchy. It was easy to navigate down and use the search bar from high level categories like `/Parts` or `/Tools`, but once they got too deep and needed to back out, they couldn't get there.

### Details
There was a clear problem noted by every tester: It's difficult to navigate back up the device hierarchy. It was almost impossible on mobile. 

Almost every single person who tested on mobile didn't realize that breadcrumbs were available to them. 

Several users stated that they would expect some hierarchy here, but didn't know how to use it.

A few noted that the ellipses button looked like an admin setting button or generally not something meant for them. 

Users got frustrated. Some noted that this might be the point at which they give up on trying to find a product. One asked "Am I just a dumb user?"

Other ways users tried to navigate back up the hierarchy when they got blocked:
- Navigating to a product page where they know there are breadcrumbs and then using those to get to the live /Store/Parts page
- Clicking on the "Parts" slider of Parts/Guides/Answers
- Manipulating the filters (One user, who entered on a nested category page, suspected that there might be some filters that were set without them knowing, which caused them to have limited results on their current page)

**Comment by dhmacs** [comment]
cc @mmarcon91

**Comment by danielbeardsley** [comment]
What about just changing the `...` to `< Back` or just `Back`?

When they click, it'll show the menu and they can choose where to go back to.

**Comment by mmarcon91** [comment]
@erinemay I agree that the icon of the three dots without any reference can be confusing.

@danielbeardsley  changing the button to "Back" could confuse the user even more. I think when clicking back the first thing that comes to mind is a link.

Another point, I am a bit worried about the size of the tabs, in some languages ​​it could be big enough not to allow more space

I have created a new version to try to fix these problems.
1) Always keep the title, this makes the breacrumbs icon more contextual
2) Create a new bar only for the tabs, so even if there are problems of width it could slide horizontally

Here a couple of tests:
https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=206%3A15167

Together with the navigation bar and comparison with the other version:
https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=206%3A15699

Open Breadcrumbs:
https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=206%3A15595

Let me know what you think, so I delete the versions we won't use

**Comment by sterlinghirsh** [comment]
I think putting Parts/Guide/Answers on a separate bar on mobile makes sense.

**Comment by erinemay** [comment]
I agree. I think this is my favorite.
![image](https://user-images.githubusercontent.com/72166715/178562006-873b8467-e400-498e-92a4-81307e1c2366.png)

**Comment by davidrans** [comment]
I like it! I agree that this is worth fixing and that multiple rows makes sense on mobile. I think we should apply this same design to devices, guides, and answers too.

Does it make sense to have the breadcrumbs above or below the Parts/Guides/Answers tabs?

With Parts/Guides/Answers on top it kind of looks like top-level navigation (i.e. /Parts, /Guide, /Answers) instead of navigation _within_ Macbook Pro 15"
