### ISSUE TITLE
Add page management links to ProductList and Product Detail Pages

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#416]
We have very helpful links on Product List Pages and Product Pages that get us straight to the editor for the page we're on. (Now Legacy) Product List Pages: 

![image](https://user-images.githubusercontent.com/7053450/177881754-848a6722-ff12-4c3a-b027-0e04c075da2d.png)

And (soon-to-be Legacy) Product pages: 

![image](https://user-images.githubusercontent.com/7053450/197943407-d3f19154-0cf8-4a4e-9eb9-1fcdd2645c84.png)

It's fairly time consuming to find the correct edit page from a given ProductList or Product Page. Let's add Admin-only links to the pages. 

ProductList --> Strapi
ProductDetail --> Edit Images
ProductDetail --> View Inventory
ProductDetail --> Shopify
ProductDetail --> Akeneo

@dhmacs @sterlinghirsh

**Comment by sterlinghirsh** [comment]
If we don't add a link on the page, this might be a good use case for a bookmarklet similar to the `Shopify > OM` one I wrote. We probably just need to include the strapi product list id somewhere and then it's just a matter of grabbing it and redirecting to https://strapi.ifixit.com/admin/content-manager/collectionType/api::product-list.product-list/1234

**Comment by jeffsnyder** [comment]
@sterlinghirsh issue expanded to include new Product Detail Page.

**Comment by mmarcon91** [comment]
I designed a more generic bar, it is inspired by Shopify's UX for non-headless stores.
So it can be used in multiple contexts.

https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=1134%3A31139
