### ISSUE TITLE
Truncate long breadcrumbs

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#427]
Long breadcrumbs aren't getting truncated and are cut off by the Parts/Guides/Answers element
https://es.ifixit.com/Parts/MacBook_Pro_17%22_Unibody

![image](https://user-images.githubusercontent.com/72166715/178350709-7c4d0a4e-2d7e-42c4-8ade-551caf67a951.png)

**Comment by erinemay** [comment]
There's another (probably data) bug here. Stand by for seeing if we have real breadcrumbs that will be long enough to overflow like this.

**Comment by dhmacs** [comment]
This was fixed a while ago. Closing this

**Comment by dhmacs** [comment]
Actually, it looks like the new `PageBreadcrumb` component is being used only in the product page. I'll reopen this to address the breadcrumbs in product list pages (e.g. https://www.ifixit.com/Parts/MacBook_Pro_13%22_Unibody_Mid_2010)

**Comment by dhmacs** [comment]
Actually, it looks like the new `PageBreadcrumb` component is being used only in the product page. I'll reopen this to address the breadcrumbs in product list pages (e.g. https://www.ifixit.com/Parts/MacBook_Pro_13%22_Unibody_Mid_2010)

**Comment by danielcliu-ifixit** [comment]
https://ifixit.slack.com/archives/C047GHDFYHZ/p1674179520456689 jared worked on some autosizing breadcrumbs

**Comment by dhmacs** [comment]
Take a look at `frontend/components/common/PageBreadcrumb` component being used by the product template. It's responsive, and works without JS, so it's SSR compatible and doesn't have CLS issues
