### ISSUE TITLE
Empty facets box for single product collections

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#429]
In https://github.com/iFixit/react-commerce/issues/388, facets that returned the same number of products displayed were hidden.
When there is only one product or the logic meets the requirements to hide all the facets, there's still the remnant of the facet box left on the page.

https://es.ifixit.com/Parts/Lenovo_ThinkPad_A275
![image](https://user-images.githubusercontent.com/72166715/178358471-de258e27-3a53-40b8-9262-eec6dbf1b0c2.png)

**Comment by erinemay** [comment]
Should we have something like the box for empty facets without the "0 results"? 
![image](https://user-images.githubusercontent.com/72166715/178551785-62868025-b748-47e4-826d-19bd198617f2.png)

**Comment by dhmacs** [comment]
I think we need to decide how we're going to handle these edge cases. Simply hiding the cart wouldn't work because the empty space would still be awkward

cc @mmarcon91

**Comment by erinemay** [comment]
Closing as duplicate of https://github.com/iFixit/react-commerce/issues/461 which is in progress.
