### ISSUE TITLE
Exclude buttons that lead to empty item-type product lists

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#432]
Item-type product lists were added in https://github.com/iFixit/react-commerce/pull/380, and they work great!

Unfortunately, we don't have all the products to fill each model for each product list. This causes links to a bunch of empty collections:
For example, we don't sell iPhone 13 batteries, so the entire top row of model buttons each link to empty collections on https://es.ifixit.com/Parts/iPhone/Batteries.
![image](https://user-images.githubusercontent.com/72166715/178549275-0bc42cb0-a97b-4a5d-8fd7-1152fd5f1041.png)

Another example: We only offer 6 iPhone brackets, but https://es.ifixit.com/Parts/iPhone/Brackets is populated with the entire list of iPhone models to choose from.

**Comment by sterlinghirsh** [comment]
Maybe it's possible to intersect the subdevices displayed with the values returned from the Device facets.

**Comment by erinemay** [comment]
Closing as a duplicate of https://github.com/iFixit/react-commerce/issues/462
