### ISSUE TITLE
Drawbacks in hiding refinement items

### ISSUE THREAD

**Issue by federicobadini** [iFixit/react-commerce#436]
In #399 it was decided to hide some facets if they did not contribute effectively to filter the result set.
However this has some implications like the one you can see in this video:

https://user-images.githubusercontent.com/7805759/178791097-87d19284-28ca-4dea-9ea2-fed89fef83d0.mov

Here the `Part only` facet was filtered out because it was not going to add any specificity to the selection. However, as soon as `Fix Kit` is selected, the option shows up again because it can expand the result set.

This is kind of unexpected for a user, because he sees a filter popping out of nowhere.

**Comment by danielbeardsley** [comment]
> This is kind of unexpected for a user, because he sees a filter popping out of nowhere.

We (@masonmcelvain and @sterlinghirsh and I) definitely discussed this (at length) while implementing #399 . We know this is unexpected and not really desired. It's certainly a lot more visible on mobile.

I think it comes down to which of the two scenarios happen more often. Though... something to think about, the behavior described here *feels* like a bug. What if we instead just put the word `all` or something in place of the count if it doesn't narrow the search? That way Options wouldn't pop in and out, while still conveying the "clicking this doesn't do anything" notion.

**Comment by federicobadini** [comment]
Most of the facets are now single select so this issue is not actual anymore
