### ISSUE TITLE
"Back to shopping" button on mini cart is interactive when invisible

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#444]
![image](https://user-images.githubusercontent.com/72166715/179037323-2360cfe4-e4f9-4aee-bdef-85a076ff8257.png)

Not sure if it's meant to be gone entirely or visible in this case. It still works when clicked on. Just invisible.

**Comment by dhmacs** [comment]
it might be there just to make it easy to animate. It shouldn't be visible, and definitely not clickable 👍

**Comment by sterlinghirsh** [comment]
Should this be closed or is there something to do here?

**Comment by dhmacs** [comment]
@sterlinghirsh the invisible button should be interactive

**Comment by sterlinghirsh** [comment]
OK I was confused by "It shouldn't be visible, and definitely not clickable"
