### ISSUE TITLE
Screen reader experience sub par with each model button image name as the image alt text 

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#446]
The model button image alt text is the image name and is read allowed while navigating the page with a screen reader.
![image](https://user-images.githubusercontent.com/72166715/179053708-b8b26c77-6a4a-4708-862a-b4ef48fc4af5.png)
The above 3 buttons get read allowed as:
imc-resized.png + Mac Parts - "imc resized dot png iphone parts"
iphone_x.png + iPhone Parts - iphone underscore x dot png iphone parts
pixel16.jpg + Android Phone Parts - pixel16 dot jpg android phone parts

Is the image alt text here necessary? If so, can we clean it up? The screen reader experience is very sub par as is.

**Comment by dhmacs** [comment]
> Is the image alt text here necessary? If so, can we clean it up? The screen reader experience is very sub par as is.

It's probably not necessary as we have device name there, setting alt to `""` should hide it to the screen reader
