### ISSUE TITLE
Show grayed out facet empty state when no facets are available

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#461]
If your search ends up with no facets visible, it's a weird looking empty state, so let's at least show some facets grayed out.

**Comment by jeffsnyder** [comment]
I think this looks worse: 
![image](https://user-images.githubusercontent.com/7053450/181072005-a977799b-88e4-4421-95ac-accc01b55359.png)

Maybe it's not so bad if we need to hide Tool Category and Worksin.

**Comment by jeffsnyder** [comment]
Er, maybe that's what's being discussed in the pull. I can't follow this very well https://github.com/iFixit/react-commerce/pull/465

**Comment by erinemay** [comment]
> I think this looks worse: ![image](https://user-images.githubusercontent.com/7053450/181072005-a977799b-88e4-4421-95ac-accc01b55359.png)
> 
> Maybe it's not so bad if we need to hide Tool Category and Worksin.

@jeffsnyder, I totally agree. I think they're separate issues (empty list vs the single item list). 

@sterlinghirsh @sumukhipandey Or is it all the same code and can be handled in the same PR? I made a new issue for this behavior. If it should all be handled in one PR, go ahead https://github.com/iFixit/react-commerce/issues/500
