### ISSUE TITLE
ProductList flair is missing on some products

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#471]
This URL filters by facet option `oem_partnership = google_pixel`. 

`https://es.ifixit.com/Parts/Google_Phone?filter%5Boem_partnership%5D%5B0%5D=Genuine%20Google%20Pixel%20Part`

_But_ not all items show the "Genuine Google Pixel Part flair on the product card. All items should have that flair. 

![image](https://user-images.githubusercontent.com/7053450/180293524-dc2391d3-ab41-4b46-a93a-d366748938e7.png)

Also, the Lifetime Warranty flair is not showing up consistently. In that same screenshot, the top item ([Google Pixel 4a Screen - Genuine](https://www.ifixit.com/Store/Android/Google-Pixel-4a-Screen--Genuine/IF356-268?o=2)) has a Lifetime Warranty but does not have the appropriate warranty flair. 

I clicked many products. It looks like flair is missing when products are out of stock. 

@sterlinghirsh @dhmacs

**Comment by sumukhipandey** [comment]
So regardless of whether the product is in stock/for sale or not we want to display the labels
