### ISSUE TITLE
Marketing collections on /Shop

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#473]
/Shop/{handle} should support marketing collections.

**Comment by djmetzle** [comment]
This needs to be routed to Vercel from CloudFront?

**Comment by masonmcelvain** [comment]
If that's what we do for /Parts/* and /Tools/* pages, then yes. I'm not sure what our current infrastructure looks like.

**Comment by djmetzle** [comment]
Here's the current origin behavior for Parts and Tools:
https://github.com/iFixit/ifixit/blob/3eaf4b3220d1e36ce937dbbbf75284f723d5263d/terraform/cloudfront/prod/main.tf#L211-L313

**Comment by masonmcelvain** [comment]
Thanks for the link! I started a pull, feel free to make comments/push to it
https://github.com/iFixit/ifixit/pull/43946
