### ISSUE TITLE
Collections: canonical tags should use absolute URLs, not relative

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#487]
Use absolute URLs, not relative, for all canonical tags. 

This is best practice. It's what we do on current (legacy) Collections.

**Comment by masonmcelvain** [comment]
I think this was unintentionally solved in https://github.com/iFixit/react-commerce/pull/496. Please re-open if you're still seeing relative canonicals @ifixitmaxb.
