### ISSUE TITLE
Seed data from the Strapi production instance

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#498]
https://github.com/iFixit/react-commerce/pull/496 was done to fix the production mini cart checkout, but in the process, we lost relative URLs that made it possible to have a prod preview. This preview was immensely helpful for testing. 

> ~~I'll open another pull to use relative urls in some places, and always us absolute urls in others so that the prod preview works again.~~

We don't want to go back to be using production strapi in a development preview, but we want production data to allow for easier and more confident testing. 

> The problem of seeing the same set of data is solved by improving how we seed the strapi preview instances in Govinor. I'm planning to make them able to seed data from the Strapi production instance, so they'll be virtually the same.

https://github.com/iFixit/react-commerce/issues/498#issuecomment-1195954150

CC: @masonmcelvain @dhmacs

**Comment by masonmcelvain** [comment]
@erinemay Based on the comment here https://github.com/iFixit/react-commerce/pull/496#issuecomment-1195682558, it seems like the concern is that we're seeing dev strapi data in `react-commerce-prod` previews, and we expect to see the same strapi data as production.

From @dhmacs comment here https://github.com/iFixit/react-commerce/pull/493#issuecomment-1195560483, I think we might be able to fix this by setting `NEXT_PUBLIC_STRAPI_ORIGIN=https://strapi.ifixit.com` in the Vercel dashboard for `react-commerce-prod`. I thought @dhmacs already did this though, so I'm not sure why we see the same Strapi data in both previews.

**Comment by dhmacs** [comment]
@masonmcelvain @erinemay I think previews should use staging instances of strapi (that is Govinor instances), not the production one (otherwise we can't really play with the strapi instance without affecting production). The problem of seeing the same set of data is solved by improving how we seed the strapi preview instances in Govinor. I'm planning to make them able to seed data from the Strapi production instance, so they'll be virtually the same.

**Comment by masonmcelvain** [comment]
Thanks for the quick response! Sounds like we can close this issue then @erinemay? Or use this as a tracker for @dhmacs's future work?

**Comment by erinemay** [comment]
I didn't realize that was the case. I thought the prod preview links were just that - dev deployment with prod data.

**Comment by erinemay** [comment]
>I'm planning to make them able to seed data from the Strapi production instance, so they'll be virtually the same.

This is fine. This is what we want.

**Comment by erinemay** [comment]
Just updated this into a tracking issue for seeding production data to govinor for the prod preview.

**Comment by erinemay** [comment]
@dhmacs quick question...

The preview links deployed from branches seem to be seeded from main.govinor.com. Is that the case? Or do they all come from some other source of truth? Specifically, if I edit some data in main.govinor.com, will that reflect in all the subsequent previews generated from pull requests? 

For example, in the interim (between now and when we get production data), if I were to go into main.govinor.com and add some data, will it show up in all subsequent branch previews? 

Specifically, `/Tools` doesn't have any children in main.govinor.com and I suspect it's caused a few bugs to get through (https://github.com/iFixit/react-commerce/issues/451, https://github.com/iFixit/react-commerce/issues/502). I'd like to add some children in main.govinor.com, but only if they'll persist through pull request previews.

**Comment by dhmacs** [comment]
@erinemay No, currently seed data is just a static json file. It's built with a script that can take any strapi instance as input for the seed data, but it's a manual process, not automated. Part of the job is to take that script and integrate it in the Strapi bootstrapping, so we can get fresh data every time
