### ISSUE TITLE
Add back /Tools breadcrumbs on desktop

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#502]
In https://github.com/iFixit/react-commerce/pull/466, the [empty toolbar on mobile](https://github.com/iFixit/react-commerce/issues/470) was fixed, but we lost the breadcrumbs on desktop. Now, there's no way to get back to the parent /Tools on desktop.
`/Tools` is as expected, but any downstream collections like `/Tools/<collection>` don't look great.

`/Tools/iFixit_Exclusives` on mobile
![image](https://user-images.githubusercontent.com/72166715/181122772-8f3375e9-51b3-42db-ad90-3591073b7949.png)

`/Tools/iFixit_Exclusives` on desktop
![image](https://user-images.githubusercontent.com/72166715/181122736-db1ec164-6727-4183-9657-9893c3e8d2bb.png)

**Comment by masonmcelvain** [comment]
> /Tools is as expected

So we _don't_ want the breadcrumbs to show on /Tools? Right now I see them on /Parts on desktop. Happy to drop them in both places if that's what we want.

![image](https://user-images.githubusercontent.com/52104630/181294620-c8cc92a2-d100-4bd3-93d9-e31858847f20.png)

**Comment by erinemay** [comment]
> > /Tools is as expected
> 
> So we _don't_ want the breadcrumbs to show on /Tools? Right now I see them on /Parts on desktop. Happy to drop them in both places if that's what we want.
> 
> ![image](https://user-images.githubusercontent.com/52104630/181294620-c8cc92a2-d100-4bd3-93d9-e31858847f20.png)

Ok wait. I haven't done a good job here in differentiating between the `/Tools` root page and individual `/Tools` collection pages. The `/Tools` root page is ok. I just want the behavior between mobile and desktop to be consistent. This might be a bigger design decision. 

This is what I'm seeing and what I think it should be, but I'm very open to feedback. Everything looks as I would expect except for the `/Tools/<collection>` desktop page marked with ❌.

### Root pages:
On `/Parts`
- Desktop: We keep the "All Parts" no link breadcrumbs because the header contains the parts/guides/answers section. ❔ we probably don't need it there, but I don't think it looks bad keeping it. 
- Mobile: Header only has parts/guides/answers because the title doesn't fit on that line and it's not necessary to have a second nav bar just to say "All Parts"

On `/Tools`
- Desktop: No header or breadcrumbs, because without the parts/guides/answers section, the header saying "Tools" would be pointless.
- Mobile: Same

### Children collection pages:
On `/Parts/<collection>`
- Desktop: Breadcrumbs fit in the same nav bar as parts/guides/answers
- Mobile: Secondary nav bar for breadcrumbs

On `/Tools/<collection>` (like on https://www.ifixit.com/Tools/Microsoldering which is a grandchild of /Tools)
- Desktop: Breadcrumbs are missing because the entire nav bar is missing ❌ (I believe we should add the breadcrumbs back to these pages because, without them, there is no other way via the ui to navigate back to the root `/Tools` page.)
- Mobile: Breadcrumbs are present - identical to secondary nav bar in `/Parts/<collection>` pages.
![20220727_104155](https://user-images.githubusercontent.com/72166715/181314270-dd23b175-cca0-4f99-95f5-e6964a83ed7c.jpg)


I'm open to suggestions. If https://github.com/iFixit/react-commerce/issues/306 gets implemented, I could see the argument for getting rid of the breadcrumbs.
