### ISSUE TITLE
Default results appear when switching single-select facets

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#526]
### Overview:

There is a brief flash of the no-filtered results when switching from one single-select facet to another

![search](https://user-images.githubusercontent.com/95656772/181639990-0d789021-d3fc-4edd-adb6-d5290e0f2147.gif)

https://react-commerce-ifixit.vercel.app/Parts
https://www.ifixit.com/Parts

**Comment by sumukhipandey** [comment]
This is probably happening [here ](https://github.com/iFixit/react-commerce/blob/dc15c19fbd5d0ed3a08ef263cd4acdbf56eb2653/frontend/components/product-list/sections/FilterableProductsSection/RefinementSingleSelect.tsx#L99). I think the quick clearing of refinements causes the default page to appear briefly.
