### ISSUE TITLE
Collections page numbers in page title - is there another way?

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#540]
It's not a great look. As I understood it, this is for SEO... Do we have any way around this while keeping good SEO form?
![image](https://user-images.githubusercontent.com/72166715/181657345-fb3e29f8-e6e3-46bd-9e16-f58a121617fc.png)
![image](https://user-images.githubusercontent.com/72166715/181657494-a126def9-47a2-4d19-9b61-32375cd0d7b3.png)

cc: @ifixitmaxb

**Comment by dhmacs** [comment]
cc @mmarcon91

**Comment by mmarcon91** [comment]
@ifixitmaxb Are pages beyond 1 indexed? Can we remove "Page X" from H1 and make it as a subtitle?

**Comment by dhmacs** [comment]
@ifixitmaxb can you look at this when you have some time?

**Comment by ifixitmaxb** [comment]
I'm sorry for allowing this to slip through the cracks. 

I don't see this Issue as being worth addressing. I spoke with Sterling yesterday - I'm not quoting him but we both generally agreed this isn't a high priority, even if we did think it was worth addressing or fixing. 

In my opinion, it's a non issue. I describe in this video. 
https://www.loom.com/share/08507b6f8df54423836debdbff67a89c

If you strongly disagree with this assessment, that it is indeed a massive eye sore and should really be addressed, then please comment and explain. I'm not going to "die on this hill" - this isn't a huge deal for SEO so if y'all think we should change what we're doing here, let me know and I'll reassess.

**Comment by dhmacs** [comment]
I don't have a strong opinion either, @erinemay should we do it or should we close this?

**Comment by erinemay** [comment]
No. We can close 👍
