### ISSUE TITLE
Collections: Bug: these pages serve a 308 status code

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#542]
No idea why but these 4 important pages serve a 308 status code:

https://www.ifixit.com/Parts/MacBook_Pro_13"_Retina_Display/SSDs
https://www.ifixit.com/Parts/MacBook_Air_13"/SSDs
https://www.ifixit.com/Parts/iPhone_12_Pro_Max/Lenses
https://www.ifixit.com/Parts/MacBook_Air_11"/SSDs

**Comment by ifixitmaxb** [comment]
I don't fully grasp what is going on here and perhaps it's just an issue with my crawler (Screaming Frog) but SF says that the below URLs serve a 308 status code:

https://www.ifixit.com/Parts/iPhone_12_Pro_Max/Lenses
https://www.ifixit.com/Parts/MacBook_Pro/Wireless
https://www.ifixit.com/Parts/MacBook_Pro/Hinges
https://www.ifixit.com/Parts/MacBook_Air_13"/Hinges
https://www.ifixit.com/Parts/iPhone_11_Pro/Lenses
https://www.ifixit.com/Parts/MacBook_Pro_13"_Retina_Display/SSDs
https://www.ifixit.com/Parts/iPhone/Flash
https://www.ifixit.com/Parts/MacBook_Air_11"/SSDs
https://www.ifixit.com/Parts/iPhone_8/Lenses
https://www.ifixit.com/Parts/iPhone_12_Pro_Max/Flash
https://www.ifixit.com/Parts/Lenovo_IdeaPad/Hinges
https://www.ifixit.com/Parts/iPhone_X/Flash
https://www.ifixit.com/Parts/MacBook_Air_13"/SSDs
https://www.ifixit.com/Parts/iPhone_12_Pro/Flash

**Comment by ifixitmaxb** [comment]
It appears the above (and probably way more examples too) have multi-hop redirects where the legacy Collection URL 301s to the apples-to-apples new Collection URL which then 308s to a different final URL. Here's an example:
![image](https://user-images.githubusercontent.com/86265382/181827206-d460d3d4-24d0-4ab1-a217-657cb0454b24.png)

**Comment by ifixitmaxb** [comment]
Where I'm still seeing this behavior of multiple hops from legacy Item Type to new Item Type:
/Adhesive_Strips --> /Adhesives
/Hard_Drives_(SATA) --> /Hard_Drives
/Lightning_Connector --> /Cables
/Logic_Boards --> /Motherboards
/Rubber_Feet --> /Case_Components
/Upgrade_Kits --> /Hard_Drives

When I load the legacy Item Types in my browser, I get no results, but if I refresh again, I get sent to the proper page.

**Comment by sterlinghirsh** [comment]
It's ones with underscores on the legacy side trying to link to unencoded item types with spaces.

**Comment by ifixitmaxb** [comment]
Are we able to update our redirect logic so that Item Types with spaces get pointed to their final destination without multiple "hops" in the redirect? Or do we just have to accept multi hop redirects? It's not even that multi hop redirects are bad for SEO, it's also that it seems like the user hits the empty pages and then would have to know to hit refresh to get to the final correct destination.

**Comment by sterlinghirsh** [comment]
The collections with an item type with an underscore loading with no products before a refresh is fixed here https://github.com/iFixit/ifixit/pull/44065

**Comment by sterlinghirsh** [comment]
Turns out 308 is on purpose. Next.js docs on redirects (search 308) https://nextjs.org/docs/api-reference/next.config.js/redirects

**Comment by sterlinghirsh** [comment]
OK I think 308 is right here, and we've fixed a few bugs around this already. If we have specific problems, either reopen this with updated examples or create a new issue.

**Comment by ifixitmaxb** [comment]
https://github.com/iFixit/react-commerce/issues/599
