### ISSUE TITLE
Collections: exempt important 1-product Item Type collections from no-index logic

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#543]
There are 40 really important legacy Item Type Collections that used to rank for important keywords but they only have 1 product result so the new Collection is no-indexed. For these 40 URLs, could we write custom override redirects to redirect the legacy Collection to the corresponding product page instead of the new Collection? The reason is to pass the SEO juice (the good keyword rankings) to the product page instead of a no-indexed Collection. 

Here are the URLs (there could be more cases of this but these are the top 40):
https://www.ifixit.com/Store/Mac/MacBook-Pro/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone/Logic_Boards
https://www.ifixit.com/Store/Game-Console/PlayStation-5/Motherboards
https://www.ifixit.com/Store/iPad/iPad-Pro-12.9"
https://www.ifixit.com/Store/Game-Console/Xbox-One-S/Motherboards
https://www.ifixit.com/Store/Mac/MacBook-Air/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Pro-12.9"/Batteries
https://www.ifixit.com/Store/Mac/iMac/SSD_Upgrade_Kits
https://www.ifixit.com/Store/Parts/Google-Pixel-5a/Screens
https://www.ifixit.com/Store/Parts/OnePlus-7-Pro/Batteries
https://www.ifixit.com/Store/Mac/MacBook-Pro/SSD_Upgrade_Kits
https://www.ifixit.com/Store/iPhone/iPhone-XS-Max-A1921/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-XS/Logic_Boards
https://www.ifixit.com/Store/Parts/Microsoft-Surface-Laptop/Batteries
https://www.ifixit.com/Store/Parts/Google-Pixel-6/Screens
https://www.ifixit.com/Store/Mac/MacBook-Air-13"-Model-A1466/Logic_Boards
https://www.ifixit.com/Store/Parts/Samsung-Smartwatch
https://www.ifixit.com/Store/Mac/MacBook-Pro/SSD_Enclosures
https://www.ifixit.com/Store/Parts/DJI-Spark/Batteries
https://www.ifixit.com/Store/Parts/Microsoft-Surface-Laptop
https://www.ifixit.com/Store/iPad/iPad-mini-5/Screens
https://www.ifixit.com/Store/Mac/MacBook-Pro-15"-Touch-Bar-2019/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Pro-12.9"/Batteries
https://www.ifixit.com/Store/iPad/iPad-Air-3/Screens
https://www.ifixit.com/Store/iPhone/iPhone-X/Lightning_Connector
https://www.ifixit.com/Store/Mac/MacBook-Pro/Rubber_Feet
https://www.ifixit.com/Store/Mac/MacBook-13"-Unibody/SSD_Upgrade_Kits
https://www.ifixit.com/Store/Parts/Google-Phone/Buttons
https://www.ifixit.com/Store/Mac/MacBook-Pro-13"-Touch-Bar-Mid-2017/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Pro-12.9"-4th-Gen/Screens
https://www.ifixit.com/Store/iPhone/iPhone-12-Pro-Max/Batteries
https://www.ifixit.com/Store/Mac/iMac/Logic_Boards
https://www.ifixit.com/Store/Game-Console/PlayStation-3/Thermal_Pads
https://www.ifixit.com/Store/Parts/Microsoft-Surface-Laptop/Screens
https://www.ifixit.com/Store/iPhone/iPhone-11/Lightning_Connector
https://www.ifixit.com/Store/Mac/Mac-mini-Model-A1347/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-XS/Lightning_Connector
https://www.ifixit.com/Store/Mac/MacBook-Pro-15"-Touch-Bar-Mid-2018/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13"-Early-2020/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Pro-12.9"

**Comment by masonmcelvain** [comment]
> Do I need to create a csv of the old Store URL and the corresponding target URL (product page)?

Thanks for offering, but when I click all of these links I'm redirected to the target URL, so it shouldn't be too hard to come up with them.

However, the new item type filters are sometimes different than the legacy item type filters, which makes things complicated. For example, I tried clicking on the first [link](https://www.ifixit.com/Store/Mac/MacBook-Pro/Logic_Boards), and there are no results for https://www.ifixit.com/Parts/MacBook_Pro/Logic_Boards. Perhaps we're just missing a redirect mapping for this specific case.

As far as the request itself, I think this would be much easier/quicker to implement if we instead exempted these collections from being no-indexed, despite only having 1 result. Does that sound reasonable?

**Comment by ifixitmaxb** [comment]
I'm definitely open to your suggestion in your last paragraph. I go back and forth on what is best. My intuition says that if Google wants to rank our Collection for these great keywords then we shouldn't try to "change their mind" by throwing a product page in their face and hope they rank it instead. If that didn't make sense: yes, I do like the idea of exempting these collections from being no-indexed. 
How difficult would it be to "exempt" these? How would we implement that and how would/could we do it at scale if we did it for more pages?

**Comment by ifixitmaxb** [comment]
For example, our legacy Collection /PlayStation-5/Motherboards ranks #1 in Google for "ps5 motherboard". I have no idea why. Why wouldn't our product page rank? It's a singular keyword so you'd think a product page is a better UX. But alas, I can't argue with Google. I want to rank #1 regardless of which page we prefer to rank #1.

**Comment by masonmcelvain** [comment]
> How difficult would it be to "exempt" these?

It would be easy for us to exempt these in code.

> How would we implement that and how would/could we do it at scale if we did it for more pages?

We could either keep a hard coded list of pages in code (like we do for the redirects), and if you want to make changes, you'd have to open an issue like this. Alternatively, we could add a true/false Strapi field like `forceIndex` (open to naming suggestions) that you would be able to edit whenever you want.

**Comment by ifixitmaxb** [comment]
Sounds great to me! 

I'll admit that I should have caught this sooner and requested these options sooner. Alas, maintaining rankings of our super high traffic Item Type Collections like the ones listed in this original Issue is my highest priority right now. 

If we can implement the hard coded list option today that would be magical. I can create a list.

**Comment by masonmcelvain** [comment]
It does get trickier for item types, but I'm sure we can keep a list of no-index exempt item types for each collection.

For example, I see we want to always include the canonical for Macbook pro rubber feet and logic boards. The item type exemptions for macbook pro could look like
```js
   Rubber_Feet,
   Logic_Boards,
```
