### ISSUE TITLE
Make something like disableCacheGets

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#548]
When updating pages in strapi, it would be nice if there was an option to bust the cache on nextjs. Maybe this is something that can be triggered on save, but it would also be nice to be able to force a cache miss.

**Comment by sterlinghirsh** [comment]
_vercel_no_cache=1 might do what we need. Will have to experiment. It looks like that bypasses the cache get and the set, but it seems like what we want is to force revalidate. I see there's an option for using an Authorization header to trigger a revalidate, but I don't really understand how that works just from reading that description, since it seems like an Authorization header also prevents caching entirely.

**Comment by danielbeardsley** [comment]
> When updating pages in strapi, it would be nice if there was an option to bust the cache on nextjs. Maybe this is something that can be triggered on save, but it would also be nice to be able to force a cache miss.

Can you be more explicit here?

Do you mean the strapi cache? The cache that vercel might have in front of our next.js app? The caching that cloudfront does on responses it gets from vercel?

**Comment by sterlinghirsh** [comment]
Yeah pretty much any of it would be nice to be able to bust
