### ISSUE TITLE
Unable to save new ProductList Collections in govinor

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#561]
1. Go to main.govinor.com/admin
2. Create a new ProductList
3. Attempt to save the ProductList

See the error in the UI
![image](https://user-images.githubusercontent.com/72166715/182255752-a832167d-89c5-442d-876a-b65144ba252b.png)

and the console error:
![image](https://user-images.githubusercontent.com/72166715/182255732-c3d22798-29ab-4541-86d4-845ddcce64ec.png)

**Comment by dhmacs** [comment]
We had the same problem described [here](https://github.com/strapi/strapi/issues/12493). I'm not really sure what caused it (maybe the fact that I've shut down the containers recently), but I've fixed it 👍
