### ISSUE TITLE
"Type" filter doesn't show up in strapi.ifixit.com

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#567]
On strapi.ifixit.com, there's no "Type" option in the filters dropdown on the ProductList collection type. main.govinor.com does have this option. One odd thing is that all the filter options on strapi.ifixit.com are capitalized, while they're all lowercase on main.govinor.com. Why the discrepancy and how can we fix it?

Update: @masonmcelvain was able to see the field. I checked our permissions, and I was marked as Super Admin, Editor, and Author, while he was just a Super Admin. I checked the role permissions for Author and Editor, and both had no permissions on Type and a few other fields, including the English locale. I tried to update the roles to add those types, but I got a 400 validation error on Strapi saying that permissions needed to be updated all at once. Not sure what that means, but it didn't work. I then removed my Author and Editor permissions, and that did work, so now I can see them. So then I think this issue is: why can't I update role permissions? Is it normal that we added fields and the roles didn't get updated too?

**Comment by dhmacs** [comment]
Do you have Strapi server logs for the 400 response?

**Comment by sterlinghirsh** [comment]
No I don't. Do you get the same error when you try to adjust role permissions?

**Comment by dhmacs** [comment]
@sterlinghirsh yes I do. I'll try to see if I can replicate on Govinor

**Comment by sterlinghirsh** [comment]
If nobody else is having this problem, I'm going to close this.
