### ISSUE TITLE
Use 301, not 302, to redirect non-english subdomain /Parts pages to www.

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#574]
For all non-english subdomains, like es. and it. etc., where we used them as sort of "staging" before new Collections launch, we need to 301, not 302, all those URLs. 

For example, es.ifixit.com/Parts/iPhone should 301, not 302, to www.ifixit.com/Parts/iPhone. 

PSA: there is almost never a case where Devs should use 302s for redirects. I can't think of scenarios where we do a "temporary" redirect.

**Comment by danielcliu-ifixit** [comment]
do you have another example of this bug? I'm not sure that our dev environment is setup to do this type of `es` -> `en` type routing and would like to test my changes easily
