### ISSUE TITLE
Collections: ability to change the Title of Item Type collections

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#590]
It would be ideal if we could edit (optimize) the Title field of Item Type collections. 

The best, current use case is to override the Title field of all /Motherboards Item Types for Apple products to "[DeviceTitle] Logic Boards". (If we had this ability, we wouldn't need to add the Logic Boards tag to all Apple products and then have both Motherboards and Logic Boards facets, which are redundant, but Logic Boards is technically correct. It would be ideal to not have both Item Types because they are the same thing just unique vernacular to certain devices (manufacturers). This Logic Boards use case is certainly not the only reason I'm asking for this feature.)
![image](https://user-images.githubusercontent.com/86265382/182979177-82ad9a4d-5f76-4021-964e-55aa2e00f00e.png)
![image](https://user-images.githubusercontent.com/86265382/182979234-0f2dbbba-99dd-4b8e-ba4a-7d9f5c355540.png)

This request is similar to #589

**Comment by ifixitmaxb** [comment]
Related: https://github.com/iFixit/react-commerce/issues/589

**Comment by sterlinghirsh** [comment]
Closing since I'm merging this with #589
