### ISSUE TITLE
Collections: redirect /Store /Logic_Boards item type collections directly to /Motherboards

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#599]
Likely related to #542, we should remove a "hop" in our redirect routing of formerly /Store/<device>/Logic_Boards. Right now, they all first 301 to /Logic_Boards, which then 308s to /Motherboards. We should 301 redirect directly to /Motherboards. 

For example, https://www.ifixit.com/Store/Mac/MacBook-Pro/Logic_Boards:
https://www.ifixit.com/Store/Mac/MacBook-Pro/Logic_Boards > 301 to > https://www.ifixit.com/Parts/MacBook_Pro/Logic_Boards
https://www.ifixit.com/Parts/MacBook_Pro/Logic_Boards > 308 to > https://www.ifixit.com/Parts/MacBook_Pro/Motherboards
Instead we should:
https://www.ifixit.com/Store/Mac/MacBook-Pro/Logic_Boards > 301 to https://www.ifixit.com/Parts/MacBook_Pro/Motherboards

**Comment by ifixitmaxb** [comment]
The following "vital few" (80/20 rule, highly important) Collections all have the multi-hop with the 308s:
https://www.ifixit.com/Store/Mac/MacBook-Pro/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-XS-Max-A1921/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-XS/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13"-Model-A1466/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-15"-Touch-Bar-2019/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13"-Touch-Bar-Mid-2017/Logic_Boards
https://www.ifixit.com/Store/Mac/iMac/Logic_Boards
https://www.ifixit.com/Store/Mac/Mac-mini-Model-A1347/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-15"-Touch-Bar-Mid-2018/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13"-Early-2020/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Pro/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13"-Retina-Late-2013/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-16"-2019/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Air-2/Logic_Boards
https://www.ifixit.com/Store/Mac/Mac-mini/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13"/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-15"-Touch-Bar-Mid-2017/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-15"-Touch-Bar-Late-2016/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-7/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Pro-12.9"/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13"-Retina/Logic_Boards
https://www.ifixit.com/Store/Mac/iMac-Intel-27"/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13"-2018/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-7-Plus/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13"-Touch-Bar-Late-2016/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Air/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13"-Retina-Early-2015/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-6s/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13"-Model-A1369/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13"-Retina-Mid-2014/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-11"-Model-A1465/Logic_Boards

**Comment by masonmcelvain** [comment]
PHP is doing the first redirect (the 301) and Next.js is doing the second redirect (a 308). The only way I can think to solve this is to duplicate the [item type](https://github.com/iFixit/react-commerce/blob/main/frontend/legacyPartCollectionRoutes.js) and [tool category](https://github.com/iFixit/react-commerce/blob/main/frontend/legacyToolCollectionRoutes.js) redirects that we currently have in Next.js to PHP, and do a single redirect in PHP. That will make maintaining these redirects more laborious, but maybe that's the only thing we can do here without setting up an API to share these redirects.

@sterlinghirsh

**Comment by sterlinghirsh** [comment]
Yeah I think that's the right answer. Maybe we can import the mapping from react-commerce if we make it a straight json file since react-commerce is a submodule, though we'll have to update the submodule reference first probably.

**Comment by ifixitmaxb** [comment]
I've got 3 more important pages that are doing this same behavior (I think). It's not just 3 unique pages but 3 Item Types (I assume):
- https://www.ifixit.com/Store/Game-Console/PlayStation-3/Thermal_Pads to https://www.ifixit.com/Parts/PlayStation_3/Thermal_Pads
- https://www.ifixit.com/Store/Mac/Mac-mini-Model-A1347/Hard_Drives_(SATA) to https://www.ifixit.com/Parts/Mac_Mini_Unibody/Hard_Drives_(SATA)
- https://www.ifixit.com/Store/Parts/ASUS-Laptop/SD_Card_Slots to https://www.ifixit.com/Parts/Asus_Laptop/SD_Card_Slots

@sterlinghirsh @masonmcelvain

**Comment by masonmcelvain** [comment]
Thanks for catching this @ifixitmaxb. There's a bug where we still see the 301 -> 308 behavior for product tag filters that don't map to an item type. I'll fix it 👍🏻 

> Is that really the best thing we can do here? I assume Hard Drives SATA could/should point to Hard Drives? And SD Card Slots to Ports?

This redirect mapping is still hard coded in a [json](https://github.com/iFixit/react-commerce/blob/main/frontend/legacyFilterSlugs.json) file. If you would like to revise the mapping, please copy and revise it and send it to us, and we'll happily upload a new version.

I think we had discussed keeping this mapping in Strapi instead of a json file so that you could more easily maintain the mapping, but I can't remember what we decided. @sterlinghirsh does that ring a bell? Were there performance concerns or something?

**Comment by masonmcelvain** [comment]
> I assume Hard Drives SATA could/should point to Hard Drives?

I also just noticed that this specific case _has_ a redirect mapping, but we're missing it in PHP because of some leading slashes. I'll fix that too.
