### ISSUE TITLE
Improve First Input Delay on Mobile for collections pages

### ISSUE THREAD

**Issue by andyg0808** [iFixit/react-commerce#602]
We saw a spike in the number of pages with long First Input Delay on mobile when we shipped the collections pages:
![image](https://user-images.githubusercontent.com/1283490/183768629-d4e11cba-8628-4ffe-b786-fcdd1274092b.png)

We don't know what's going on, but it looks like we spend a lot of time evaluating script:
https://pagespeed.web.dev/report?url=https%3A%2F%2Fifixit.com%2FParts&form_factor=mobile

**Comment by danielbeardsley** [comment]
Here's a little more detail:
![image](https://user-images.githubusercontent.com/26855/183772738-7420ba02-5137-4996-b9ee-fcbcba7e5ec8.png)

**Comment by federicobadini** [comment]
This is not present anymore on react-commerce
