### ISSUE TITLE
Item Type: Facet selection not moving to the top

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#635]
### Overview:

I noticed that selected facets in the **Item Type** filter option don't move up like other single-select options
This can be closed if it is intentional, but I wanted to bring it up as an issue just in case this isn't

![firefox_G0UpvBIeDl](https://user-images.githubusercontent.com/95656772/185481672-3afc5317-311a-4d07-b992-11d58293f0bd.gif)

**Comment by sterlinghirsh** [comment]
It's intentional

**Comment by sterlinghirsh** [comment]
Wait looking again I think there is a bug here since Item Type stays but Device Brand floats. We should at least be consistent. I think leaving them in place makes sense.
