### ISSUE TITLE
Use standard translation icon next to Help Translate in the footer

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#638]
We should use the standard translation icon next to "Help Translate" in the new footer. Something more like [this](https://icons.iconarchive.com/icons/marcus-roberto/google-play/256/Google-Translate-icon.png) or [this](https://cdn-icons-png.flaticon.com/512/2793/2793765.png). 

We can still use the global gateway globe icon next to the Store selector, instead of or in addition to the country flag, but I'll leave that up to Mattia and team to decide. 

Perhaps we should increase the spacing a bit more between the store selector and Help Translate to help further distinguish the two CTAs.

**Comment by sandrahiller** [comment]
Using the global gateway globe icon implies that users can choose both store and language from there, which would actually make a big improvement on UX. Showing the store selector next to the translation CTA will likely cause confusion. Even more so as they do not have any option to change their view language.

**Comment by mmarcon91** [comment]
> We should use the standard translation icon next to "Help Translate" in the new footer. Something more like [this](https://icons.iconarchive.com/icons/marcus-roberto/google-play/256/Google-Translate-icon.png) or [this](https://cdn-icons-png.flaticon.com/512/2793/2793765.png).

Updated with FontAwesome icon `language`.
https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=408%3A19632

> We can still use the global gateway globe icon next to the Store selector, instead of or in addition to the country flag, but I'll leave that up to Mattia and team to decide.

I am not a big fan of flags, but from experience I have noticed that the user is able to associate the meaning faster than a generic icon, having different flags as a toggle allows the user to immediately identify which region he is in.

> Perhaps we should increase the spacing a bit more between the store selector and Help Translate to help further distinguish the two CTAs.

I think in the Figma link it is already more spaced

**Comment by ifixitmaxb** [comment]
It looks good to me.
