### ISSUE TITLE
Finish Store Selector

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#652]
Right now, we only have the US and EU store in the footer store selector. They are just links to the urls listed in Strapi ⬇️ 
![image](https://user-images.githubusercontent.com/72166715/186770679-3bf41e3e-39ae-4c93-a3c0-9d451ba8d5e5.png)

There are only two store entries in Production Strapi
![image](https://user-images.githubusercontent.com/72166715/186770884-42366695-b4f0-46bb-992a-bb0d20278abd.png)

CC @jeffsnyder @ifixitmaxb

**Comment by erinemay** [comment]
Is there additional functionality we wanted to add around the store selector? Or do links to appropriate store home pages suffice?

**Comment by jeffsnyder** [comment]
I didn't realize this section manages the Store Selector. A single link from this selector is fine IMO. A couple questions I have about this admin page: 

1. What does `shopifySettings` do?
2. How do we customize the flag? I don't see where/how.
3. Do we need to fill in the footer now? I don't think it matters until we move the given store to use Strapi/React.

[Cominor ](https://www.cominor.com/Parts)screenshot, [Govinor link](https://main.govinor.com/admin/content-manager/collectionType/api::store.store/3): 
![image](https://user-images.githubusercontent.com/7053450/186787692-34f3598a-043a-435c-8943-d7fccd5e22a8.png)

**Comment by dhmacs** [comment]
> 1. What does `shopifySettings` do?

It stores the name and storefront token of the Shopify store that's used for that region. Not needed until we support those regions, but it's probably a good idea to fill in the value now
 
> 2. How do we customize the flag? I don't see where/how.

Flags are rendered based on the content of the `code` field in Strapi. Supported values right now are:

- `au` = Australia
- `ca` = Canada
- `de` = Germany
- `fr` = France
- `gb` = United Kingdom
- `eu` = Europe
- `us` =  United states


> 3. Do we need to fill in the Header and Footer sections in Strapi now? I don't think it matters until we move the given store to use Strapi/React.

They won't be displayed until we support different store, like you're saying. So it's up to you if you want to do it now, or postpone it.

**Comment by jeffsnyder** [comment]
Another fiddly question for you @dhmacs 

I can't figure out why the items are ordered in the way they are ordered in the dropdown (this is all in Govinor/Cominor): 

![image](https://user-images.githubusercontent.com/7053450/187552938-38934e15-5041-4292-b296-33e4329ce5e5.png)

It doesn't match the sort order on any of the items in Strapi. Sorting by ID, code, name, or URL don't match this pattern: 

![image](https://user-images.githubusercontent.com/7053450/187553006-1f6ea42e-99f3-46f0-9e9e-aba84abe1616.png)

What are we sorting by? And can we customize it?

**Comment by dhmacs** [comment]
Ehi @jeffsnyder @erinemay is there anything we could do here, or should we close this?

**Comment by erinemay** [comment]
Actually, that looks like a bug related to https://github.com/iFixit/react-commerce/issues/969. I think we can close this, and I'll open up a separate bug issue for that.

**Comment by erinemay** [comment]
That issue: https://github.com/iFixit/react-commerce/issues/1174. 

This issue was meant to add the other stores and links to the store selector. That's done.
