### ISSUE TITLE
Design: Product Description Container

### ISSUE THREAD

**Issue by Annika29** [iFixit/react-commerce#66]
## Design Reference
<img width="1071" alt="Screen Shot 2021-08-17 at 2 33 23 PM" src="https://user-images.githubusercontent.com/35045100/129803579-44cde724-4dcf-43f8-b3ca-240298347615.png">

## What we are looking for
Elements:
* Part title
* Image
* Price
* Include the text "Lifetime Warranty"
* Review stars
* Include the text "Ships today if ordered by 5pm"
* Display product availability (create sense of urgency, i.e. “Only 6 left in stock - order soon.”)

We would like a high fidelity design of an individual product on a collections page and a list of product descriptions.

**Comment by dhmacs** [comment]
Hey @Annika29, is this a task that should be assigned to our designer (Mattia) ?

**Comment by Annika29** [comment]
Hey @dhmacs, yes that was the intention but let's have @kwiens confirm that.

**Comment by dhmacs** [comment]
@Annika29 Mattia has been working on this, and has updated the [Figma mockup](https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit-Shopify-Working-Files?node-id=501%3A7165) with two new proposal ("collection 5" and "collection 6").

"collection 6" design, which separates items, allows to make more visible the item in focus, for example by increasing the shadow level to visually raise it.

An "Add to cart" button has been added to quickly add the item to cart, useful if the customer already knows the product. Moreover the presence of this button allows to easily manage "Out of stock" products.

The discounts have been highlighted with a different color and a label with the discount percentage. The labels part allows flexible management of other features.

Which one do you prefer? Let us know your feedback

**Comment by dhmacs** [comment]
@Annika29 the mockup has been updated (see collection 6). We opted to drop the image of the workbench device compatibility and just use a label. Image + label does not work since either you have a lot of space around the text, or the image is so small that it can barely convey any information

**Comment by JFleischhauer** [comment]
> We opted to drop the image of the workbench device compatibility and just use a label.

Looks good imo!
