### ISSUE TITLE
Collections: I can't figure out why this page is indexable, with only one product

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#663]
It'd be good to investigate why this page is indexable, and if others like it exist: https://www.ifixit.com/Parts/Microsoft_Surface_Laptop/Batteries

**Comment by danielcliu-ifixit** [comment]
Its because this was one of the exempt 1-product Item Type collections I believe. I believe this functionality was requested in https://github.com/iFixit/react-commerce/issues/543 and implemented in https://github.com/iFixit/react-commerce/pull/552. Do we not want this functionality anymore?

**Comment by ifixitmaxb** [comment]
Oh yeah! Thanks!

**Comment by ifixitmaxb** [comment]
And for now, yes, let's keep the functionality.
