### ISSUE TITLE
Collections: Display 4 rows "devices" on /Tools parent collection

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#682]
Just for /Tools parent collection, display 4 rows instead of the default 3. We want all the current child collections to show and not be hidden by "Show more".

**Comment by ifixitmaxb** [comment]
I'd like to propose doing this exact same thing but for https://www.ifixit.com/Parts/Electronics. (Imo, we should show Vacuum, Television and VR parts and not hide behind "Show more")

**Comment by federicobadini** [comment]
How we are supposed to handle this for smaller screen sizes?
At the moment we are showing a different number of columns according to the screen size:
```
base: 1,
sm: 2,
md: 3,
lg: 4,
```
So small screens already show a much shorter list of items.
