### ISSUE TITLE
Fix Typescript types regressions on `ui` package

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#695]
PR #639 has broken Typescript types for the cart component. Digging through the code I see that we're importing dependencies in the `ui` package that should only be visible in the `frontend` package, e.g.:

![Screenshot 2022-09-13 at 14 58 05](https://user-images.githubusercontent.com/4640135/189907180-f59f1d16-07f5-4edd-8c31-f738976357bd.png)

## Do this

`ui` package should not depend on the `frontend` package, so we need to refactor the code to remove these dependencies.
Part of the refactor is to put components into the ui package (e.g. `IFixitImage`), and part of the refactor is declare props locally (For example we don't want our `ui` package to depend on types exported from the models of our `frontend` app. Let's decouple the type definitions).

## Bonus

There is a git hook that should have prevented us from pushing code with TS errors. I'd like to learn how these errors weren't catched, @hcutrone did you force push or is the git hook not working on your machine?
I think it might be worth to create a Github action to perform the ts check.

**Comment by hcutrone** [comment]
Hm, no I did not force push or by-pass any tests. It stopped me from pushing when there were other type errors, but it never warned me about those.

**Comment by dhmacs** [comment]
@hcutrone are you running on Windows? I think we should have a Github action in place anyway 🤔

**Comment by hcutrone** [comment]
@dhmacs I'm running Linux (Ubuntu). Agreed that a Github action is probably the right idea here. 
Also, we're working away on some dependency issues that arose trying to use the footer in the iFixit/ifixit repo. Do you think this could be causing extra issues?

**Comment by dhmacs** [comment]
@hcutrone I think so. It's weird to me that it was good enough to pass QA, because the code is basically importing stuff that it shouldn't know anything about. Like `@models/menu` is something that only the `frontend` app knows how to resolve (since its a path alias set on the `frontend` `tsconfig.json`). It would really surprise me if you are able to use these components in other projects 🤔
