### ISSUE TITLE
Bug: Changing filters on paginated results doesn't reset to page 0

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#697]
I don't know how yet, but Google is finding and crawling paginated Collections with 0 results. For example, these were all crawled on Sept 9 ([as reported in Search Console](https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fwww.ifixit.com%2FParts%2F&item_key=CAMYCCAC&hl=en)):

- https://www.ifixit.com/Parts/Microsoft_Surface_Book/Hard_Drives?p=2
- https://www.ifixit.com/Parts/MacBook_Pro_16%22_2019/Microphones?p=2
- https://www.ifixit.com/Parts/iMac_Intel_24%22/Cables?p=2
- https://www.ifixit.com/Parts/iMac_Intel_24%22/Graphics_Cards?p=2
- https://www.ifixit.com/Parts/iMac_Intel_24%22/Accessories?p=2

Do this:
It would be ideal if we could figure out how/where Google is finding links to these pages and then eliminate those links. It seems like there is no reason for these pages to even be created in the first place, let alone linked to. It's a waste. 

@erinemay

**Comment by sterlinghirsh** [comment]
I found that if you go to https://www.ifixit.com/Parts/Microsoft_Surface_Book?p=2, all the item type links also include p=2. Let's make sure filtered pages do not link to page 2, even if you're on page 2 of the device parts.

**Comment by rickisXP** [comment]
> How is this going @rickisXP? Is this "in Sprint" or just researching/exploring at this point?

@ifixitmaxb I'm still researching the issue, but I'll be working on getting a pull out within the next week

**Comment by danielbeardsley** [comment]
This was fixed (the page resetting bug) by #1004
