### ISSUE TITLE
Collections: Bug: /Hard_Drives_ Item Type

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#698]
Seems like maybe we added an additional Hard Drives Item Type facet on accident. For example, https://www.ifixit.com/Parts/iMac_Intel_17%22/Hard_Drives_.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/86265382/190004327-c8b6410d-0e5e-4a8b-8970-c11aa5b752b4.png">

I don't know how prevalent this is but we should find out and then fix it. @erinemay

**Comment by erinemay** [comment]
@ifixitmaxb, where did you get the link <https://www.ifixit.com/Parts/iMac_Intel_17%22/Hard_Drives_> with that trailing underscore?

On <https://www.ifixit.com/Parts/iMac_Intel_17%22/Hard_Drives_> with the trailing underscore, I see the duped facets.
![image](https://user-images.githubusercontent.com/72166715/192652905-e80080a8-cd37-4d12-aa49-0b2f0aca8d88.png)

It looks like github scrubbed out the underscore and made the link to the version of the page without it... which looks correct. https://www.ifixit.com/Parts/iMac_Intel_17%22/Hard_Drives

cc: @sumukhipandey

**Comment by sumukhipandey** [comment]
> @ifixitmaxb, where did you get the link https://www.ifixit.com/Parts/iMac_Intel_17%22/Hard_Drives_ with that trailing underscore?
> 
> On https://www.ifixit.com/Parts/iMac_Intel_17%22/Hard_Drives_ with the trailing underscore, I see the duped facets. ![image](https://user-images.githubusercontent.com/72166715/192652905-e80080a8-cd37-4d12-aa49-0b2f0aca8d88.png)
> 
> It looks like github scrubbed out the underscore and made the link to the version of the page without it... which looks correct. https://www.ifixit.com/Parts/iMac_Intel_17%22/Hard_Drives
> 
> cc: @sumukhipandey

Yeah I wasn't sure if this was still happening or if I just couldn't find where it was happening. However, the PR I got out that's linked to this issue should get rid of the problem anyways.
