### ISSUE TITLE
Add "Featured products" section to product page

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#710]
<img width="984" alt="Screenshot 2022-09-19 at 16 58 21" src="https://user-images.githubusercontent.com/4640135/191048370-e283d46c-3340-41c5-9192-74f6027a1c34.png">

**Comment by dhmacs** [comment]
@sterlinghirsh I think there's no metafield for telling whether the product variant is pro or not. Should we infer it from the price tier metafield?

**Comment by sterlinghirsh** [comment]
You can't infer whether a product is "pro only" from the price tiers. We'll have to add something for that, but for now, don't worry about pro only, and we'll add the restriction later. I don't expect any pro only products in the featured products section anyway.
