### ISSUE TITLE
Collections: /Mac_mini capitalization nuances

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#711]
For the most part, we default all Mac mini URLs to use capitalization so all our Mac mini Collections are actually /Parts/Mac_Mini (with the second "M" being capitalized, even though that doesn't follow the page title). That's fine. But we're inconsistent on 2 Mac mini devices and I'm not sure why and I assume we should be consistent to avoid issues. 
The following Mac mini pages use lower case "mini", and all their corresponding Item Type collections. 
https://www.ifixit.com/Parts/Mac_mini_Late_2018
https://www.ifixit.com/Parts/Mac_mini_(PowerPC)

1. Why and how do we force the "mini" to be lower case for these two devices?
2. Can we and should we fix it? Standardize it? Or ignore?

**Comment by sterlinghirsh** [comment]
This is how it is on the device page. If you want to fix it, I think we just have to change it there.

**Comment by sterlinghirsh** [comment]
You can probably change it yourself or talk to Tech Writing, but this isn't going to be a code change so I'm going to close this.
