### ISSUE TITLE
Product Page: Tool product breadcrumbs lead back to parts

### ISSUE THREAD

**Issue by rickisXP** [iFixit/react-commerce#716]
On tool products such as the [Pro Tech Toolkit](https://react-commerce.vercel.app/Products/pro-tech-toolkit), the breadcrumb for this product points back to `/Parts` rather than `/Tools`

![image](https://user-images.githubusercontent.com/95708883/191379124-5838b4d0-4f70-457c-99b5-302b126920b7.png)

**Comment by dhmacs** [comment]
@sterlinghirsh is the breadcrumb metafield ready?

**Comment by sterlinghirsh** [comment]
It should be there in a product metafield "ifixit.breadcrumbs"

**Comment by dhmacs** [comment]
@sterlinghirsh is that the updated one? I remember that we said this a legacy metafield. Has this been updated?

**Comment by sterlinghirsh** [comment]
I think it should be good to use.

**Comment by dhmacs** [comment]
Reporting here a summary of the Slack conversation I had with @sterlinghirsh:

The metafield can be used, but the data needs some polishing. Currently the metafield contains sometimes only ancestors, and sometimes ancestors and the current page. It will be uniformed to contain **only ancestors**. 
We might also consider to rename it to `ancestors` to be explicit about its content.
