### ISSUE TITLE
No-index all react-commerce.vercel.app pages

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#722]
I don't know how Google found them but at least 60 are now indexed. It was 52 earlier today so it seems like more and more are getting indexed. https://www.google.com/search?q=site%3Areact-commerce.vercel.app

**Comment by danielbeardsley** [comment]
And 1400 from here: https://www.google.com/search?q=site%3Areact-commerce-prod.vercel.app
