### ISSUE TITLE
Product Page: Implement shipping restriction details hover

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#729]
![image](https://user-images.githubusercontent.com/72166715/192049306-c484a973-b0ca-43c6-bc4f-18fa5d336162.png)

Data will be provided in a variant metafield `shipping_restrictions`, which is an array of codes like `is_battery` or `us_only`.

Instead of displaying "Shipping restrictions apply" in all cases, we'll have a short `notice` and a long `text` (that shows in a tooltip) for each restriction, though some of these do have "Shipping restrictions apply" as their notice. We'll only ever show one restriction, for now, even though we're including an array of all of them. The array has been pre-sorted to have the most relevant first.

When a "link" is specified for a given restriction, add a "Learn more" link at the bottom of the tooltip as shown here:
![image](https://user-images.githubusercontent.com/589425/196542529-fb7d9f03-4e29-4f07-b82c-35866c537bc2.png)
(https://www.ifixit.com/Store/Tools/iOpener/IF145-198?o=9)
For reference, the priority order is:

- battery
- dangerous
- us only
- does not ship to mexico

But this shouldn't need to be coded into the frontend.

Additionally, when a product is fulfilled via dropshipping, we'll include the 'fulfilled_via_dropshipping' key in shipping_restrictions. In this case, we'll show an identical (additional) indicator with the fulfilled_via_dropshipping message specified below. This is the only case where we'll show multiple "shipping restrictions".

Currently this is implemented in ifixit/ifixit: carpenter-frontend/Cart/Product/shipping_flag_notice.js . We should be mostly copy/paste this.

```js
 const attributeToInfo = {
    is_battery: {
       notice: 'Shipping restrictions apply',
       text: 'Batteries may only be shipped within the contiguous USA at this time and may only ship via standard shipping.',
       link: 'https://help.ifixit.com/article/195-battery-shipping-warnings',
    },
    is_dangerous: {
       notice: 'Shipping restrictions apply',
       text: 'New safety regulations for dangerous goods may cause shipping delays.',
       link: 'https://help.ifixit.com/article/264-what-are-the-shipping-restrictions-for-orders-containing-dangerous-goods',
    },
    us_only: {
       notice: 'US shipping only',
       text: 'Due to shipping regulations, iFixit may only ship this product within the United States of America.',
    },
    does_not_ship_to_mexico: {
       notice: 'Mexico shipping unavailable',
       text: 'Due to shipping regulations, iFixit may not ship this product to Mexico.',
    },
    fulfilled_via_dropshipping: {
       notice: 'Partner fulfilled',
       text: 'This product will be packed and shipped by one of our fulfillment partners.',
    },
 };
```

**Comment by dhmacs** [comment]
What kind of content should go in the shipping restriction popover?
I see a couple of product variant metafields that could be relevant, but how should I use them?

<img width="477" alt="Screenshot 2022-10-05 at 18 15 09" src="https://user-images.githubusercontent.com/4640135/194110131-ce85e5b2-839b-4ce9-93e8-c697dd4ad0aa.png">

cc @erinemay @sterlinghirsh

**Comment by sterlinghirsh** [comment]
I updated the description. Let me know if you have any more questions on this.
