### ISSUE TITLE
Product Page: Repetitive value propositions

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#730]
There are two sections on the product page that are almost identical. It's particularly noticeable on mobile because you have to scroll past both sections to get down the page.

| Under the add-to-cart button | Between details and reviews |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/72166715/192048974-7fbcf4e9-9e73-469e-b5be-03757864395f.png) | ![image](https://user-images.githubusercontent.com/72166715/192049086-64554bfb-4ca2-4bab-b8e5-1c0db2e6935d.png) |

**Comment by erinemay** [comment]
Maybe this is just a content issue early on? Do we have additional content to display here?

**Comment by erinemay** [comment]
I think it makes more sense on desktop. The second element contributes positively to the overall look of the page, and I don't have to specifically scroll past both sections to get down the page. It seems more likely that a user might miss one of the sections on desktop. 
![image](https://user-images.githubusercontent.com/72166715/192051332-9bf125e3-9447-4c4a-bdd9-eeee05a42bce.png)

**Comment by sterlinghirsh** [comment]
Maybe let's hide one or the other of these on Mobile. @mmarcon91 thoughts?

**Comment by mmarcon91** [comment]
The two sections were designed in this way:

1) Incentives on the product detail are product-related, with product-specific points.
2) The page section is store related and should be global incentives that help convert

The mob
<img width="332" alt="Screenshot 2022-10-13 at 09 15 15" src="https://user-images.githubusercontent.com/2742361/195528489-7a78ca8b-76e5-4bf9-bb26-22cb18fc1c31.png">
ile version should be a more condensed. 


I would try to keep it on mobile as well and if it is possible we could do a/b test with and without to see if it scrolls/converts more.

**Comment by sterlinghirsh** [comment]
Closing this since they're duplicated on purpose.
