### ISSUE TITLE
Collections: Display 4 rows "devices" on /Parts/Electronics parent collection

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#741]
On [/Parts/Electronics parent collection](https://www.ifixit.com/Parts/Electronics), display 4 rows instead of the default 3. We want all the current child collections to show and not be hidden by "Show more".

Similar to https://github.com/iFixit/react-commerce/issues/682

**Comment by ifixitmaxb** [comment]
I saw your comment before, Federico, about this all depends on screen size. That's fair. I'm focused here on the large screen size where each row has 4 columns. The most common screen size viewing iFixit.com is 1900 wide so I'm focused on this for now. I'd like to show 4 rows for the largest/widest screen size (resolution?). Is it possible to code this change for the largest/widest resolution and not affect the other sizes/resolutions? @federicobadini

**Comment by federicobadini** [comment]
Would a Strapi flag like `showAllChildrenCollectionsOnLargeScreen` solve this?
Just let me know if this would suffice or if you would like to have an even more granular control on this.

**Comment by ifixitmaxb** [comment]
@jeffsnyder what do you think?

**Comment by jeffsnyder** [comment]
@federicobadini Yes, that would solve the problem.

**Comment by ifixitmaxb** [comment]
Are we going to default to not show all? And the toggle in Strapi would only be used if we want to override the default and show all? It seems like this new feature is causing some page creation/editing issues.

**Comment by sterlinghirsh** [comment]
I don't think this needs any more spec. Let me know if there's anything missing here.
