### ISSUE TITLE
Search indexing: Add robots.txt

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#743]
Attacking the concerns in #734 from a different angle, let's prevent search engines from even crawling our non-production pages.

### Do This
***Wait until a month or two after we merge #734***

Add a `robotos.txt` page that responds with plain text and just renders two lines:
```
User-agent: *
Disallow: /*
```

~~Maybe use a middleware.~~

Note: www.ifixit.com doesn't proxy this path to us, so this will only be accessible from non-production pages.

**Comment by sctice-ifixit** [comment]
Note that this doesn't (to my understanding) cause anything to be _removed_ from the index. If we do this before search engines pick up the no-index changes, disallowing via robots will prevent them from seeing that we've no-indexed.

**Comment by danielbeardsley** [comment]
> . If we do this before search engines pick up the no-index changes, disallowing via robots will prevent them from seeing that we've no-indexed.

I remember lots of discussion around this, but I don't remember if it was based on guesses and hearsay or evidence.

**Comment by sctice-ifixit** [comment]
> I remember lots of discussion around this, but I don't remember if it was based on guesses and hearsay or evidence.

https://developers.google.com/search/docs/crawling-indexing/block-indexing

> Important: For the noindex directive to be effective, the page or resource must not be blocked by a robots.txt file, and it has to be otherwise accessible to the crawler. If the page is blocked by a robots.txt file or the crawler can't access the page, the crawler will never see the noindex directive, and the page can still appear in search results, for example if other pages link to it.

> … We have to crawl your page in order to see meta tags and HTTP headers. If a page is still appearing in results, it's probably because we haven't crawled the page since you added the tag. You can request that Google recrawl a page using the URL Inspection tool. Another reason could also be that the robots.txt file is blocking the URL from Google web crawlers, so they can't see the tag.

**Comment by sctice-ifixit** [comment]
However:

https://developers.google.com/search/docs/crawling-indexing/robots/robots-faq?visit_id=637998313330959905-3125693854&rd=1#h17

> Blocking Google from crawling a page is likely to remove the page from Google's index.
>
> However, robots.txt disallow does not guarantee that a page will not appear in results: Google may still decide, based on external information such as incoming links, that it is relevant and show the URL in the results. If you wish to explicitly block a page from being indexed, use the noindex robots meta tag or X-Robots-Tag HTTP header. In this case, don't disallow the page in robots.txt, because the page must be crawled in order for the tag to be seen and obeyed.

Maybe if there are no inbound links they're likely to remove stuff from the index… eventually? That's my best reading of all of the above. I think we've been conservative in the past because the best practices from Google aren't particularly clear, and we _know_ that getting Google to see a `noindex` directive definitely works as soon as they see it.

**Comment by danielbeardsley** [comment]
Thanks for the references @sctice-ifixit !

**Comment by sterlinghirsh** [comment]
Max says we're good to go on this.

**Comment by sterlinghirsh** [comment]
static file /public/robots.txt
