### ISSUE TITLE
Alert on downtime

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#753]
We deployed a change with an accidentally updated pnpm lock. This ended up breaking the collection page in some cases. Unfortunately, this meant we served many many error pages (28k according to [sentry](https://sentry.io/organizations/ifixit/issues/3627482296/events/8e2e2f8f0e4e414fbea87e55f4ac2127/?project=6469069&query=is%3Aunresolved)). We should add some alerting so we can catch this sooner.

**Comment by masonmcelvain** [comment]
I think we can close this now that we set up alertra in https://github.com/iFixit/ifixit/issues/46312
