### ISSUE TITLE
Enable product page in production without linking to it

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#770]
We want to start testing the product page in production by enabling it but without linking to it from product list pages

## Proposed solution

Right now we use the `PRODUCT_PAGE_ENABLED` flag to decide whether we should 404 or not. By removing this check the page will be visible in production, and the product lists still won't link to it.
Should we also return a no-index header to prevent search engine from indexing the page until we go live? 

cc @sterlinghirsh

**Comment by sterlinghirsh** [comment]
I think removing the check to make it visible in prod makes sense, but we should keep the links the old way. I think the noindex header is okay, though hopefully it doesn't get stuck like that when we turn it off. We may want to remove the noindex header a day or two before we switch the links.

**Comment by dhmacs** [comment]
Great, then let me know when you want to proceed with this so I'll open the PR for that 👍

**Comment by sterlinghirsh** [comment]
Let's proceed with activating the page noindexed for now but keep the links on the feature switch.
