### ISSUE TITLE
Support variant enabled metafield

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#784]
This is similar to disable_when_oos, but we should treat the variant as enabled only when the metafield is true, regardless of inventory.

**Comment by sterlinghirsh** [comment]
Note: Still waiting on the metafield definition.

**Comment by federicobadini** [comment]
I implemented this in a separate branch.
As soon as the metafield definition is ready this just needs to be tested

**Comment by federicobadini** [comment]
I am starting to see the enabled2 metafield on some variants so I suppose it is now correctly populated. I'll file the PR soon
