### ISSUE TITLE
Product Page: Change "Variant Text" to "Style"

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#787]
The Shopify option `Variant Text` is currently displayed on the product page. 
![image](https://user-images.githubusercontent.com/72166715/194405758-801017d8-ce1b-4e68-872b-2cf65c770af0.png)

We didn't include any option text on the old product pages, so it wasn't a problem.
![image](https://user-images.githubusercontent.com/72166715/194406857-452b4100-a0f3-4498-8919-c8b98573628c.png)

**Comment by erinemay** [comment]
@jeffsnyder thoughts on what to call this section?
Are there other odd option types that shouldn't be displayed?

**Comment by erinemay** [comment]
Should say "Style"

**Comment by sterlinghirsh** [comment]
We should make sure that nothing in shopify-v2 depends on it being called "Variant Text"

**Comment by jeffsnyder** [comment]
The attribute label has been updated already. We assumed that updating the attribute label would automatically update the label on the product page.

**Comment by sterlinghirsh** [comment]
Maybe it's just out of date on cominor.

**Comment by sterlinghirsh** [comment]
I figured it out. We have to change it to Style on the label attribute of Akeneo's variant axes.

**Comment by sterlinghirsh** [comment]
OK I fixed this live. This should be fixed as we re-push products.

![image](https://user-images.githubusercontent.com/589425/194946360-2bdbac49-5b8c-41f7-8191-45bd53d0d477.png)

**Comment by jeffsnyder** [comment]
@sterlinghirsh thanks for fixing this. I didn't realize it was `variant_axes` that needed to change.

**Comment by sterlinghirsh** [comment]
I didn't either until yesterday.
