### ISSUE TITLE
Variant Selector: When there's only one option, don't show a selector

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#793]
[`variant-selector-singular-ui`](https://github.com/iFixit/react-commerce/compare/variant-selector-singular-ui)

It's awkward to have something that looks like a dropdown or a button with only one option, but we still want to indicate e.g. `Condition: New`

**Comment by masonmcelvain** [comment]
@sterlinghirsh Is this what you had in mind

Before
![image](https://user-images.githubusercontent.com/52104630/194962665-86be810c-06e5-4a8f-b93d-18f9ce32c4c8.png)

After
![image](https://user-images.githubusercontent.com/52104630/194962680-68cc323b-3fae-40e2-8d4d-fd19baa83b63.png)

**Comment by sterlinghirsh** [comment]
Yeah. I think it's an improvement but I'm not married to it.
