### ISSUE TITLE
Product Page Layout Shift Part 2

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#795]
There's some more layout shift from the product page. It's happening intermittently, but usually on first load for me. 

https://user-images.githubusercontent.com/72166715/194435866-1371faea-00c1-4997-9d89-8d90b18c32d5.mp4

**Comment by federicobadini** [comment]
I tried to reproduce this with several browsers (Brave, Chrome, Safari etc) but non of them seems to show that bug even with super slow connections.
Here is a screen capture of what I'm seeing:

https://images.zenhubusercontent.com/362534038/206dcded-a5af-4c3f-aefb-3e884c4426e1/screen_recording_2022_10_07_at_15_37_47.mov

**Comment by erinemay** [comment]
Let me take a look and see if I can get you reliable repro steps. 👍

**Comment by federicobadini** [comment]
I've tried again on other Mac devices but as far as I cannot reproduce it.
I'm going to test it out also on a windows machine soon.

**Comment by erinemay** [comment]
I'm not sure about repro steps.

I'm only seeing it intermittently on Windows 10+Chrome, but only on my device. I can't repro it with the same combination or on other device/browser combos on browserstack. 

I'm gonna close this for now and if other people are seeing it when we do a full page crawl, we can re-open with more specifics.
