### ISSUE TITLE
Add Videos

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#798]
https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=5107%3A51360

**Comment by erinemay** [comment]
I don't see product video metafields for products on ifixit-test. It's probably just a missing metafield.

**Comment by dhmacs** [comment]
The metafield is this one:

<img width="656" alt="Screenshot 2022-10-07 at 17 16 54" src="https://user-images.githubusercontent.com/4640135/194589007-2d521b31-dc13-4f19-a949-62e7aa8d2a62.png">

This is a product that has a video: https://react-commerce.vercel.app/Products/iphone-7-replacement-battery

**Comment by erinemay** [comment]
Awesome! Thank you ❤️

**Comment by dhmacs** [comment]
Can I close this? 😊

**Comment by erinemay** [comment]
Yes! Totally. Sorry I should have with my comment 👍
