### ISSUE TITLE
Product Page: Sync item quantity available with cart additions

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#799]
Part 1
Restrict amount that can be added to cart by the amount available. 
Repro steps: There were only 3 products available, but I was able to add more than those available to my cart. I should only be able to add 3 to my cart.

https://react-commerce.vercel.app/Products/iphone-11-pro-screen?_vercel_no_cache=1&variant=32965709365338

![image](https://user-images.githubusercontent.com/72166715/194439234-52a0c399-1340-438d-b761-ed2fa1c8853f.png)

Part 2
Apply an overall limit to how many of a single item a person can add to their cart. Right now, it's 20 for regular customers.
@jeffsnyder - Is there any limit to pro customers?

Part 3
Adjust the count on the product page when an item is added to the cart. 
In the image above, when one was added to the cart, the product page should say 2 left. When 3 were added, the product page should say 0 left.

This is restricted to user session. It should only display the modified amount available to that user with the items in their cart.
So, if another user comes across that same page, they should still see the amount available in stock.

**Comment by dhmacs** [comment]
@erinemay I noticed that the inventory level in Shopify is different from the `maxToAdd` returned by the cart api

<img width="258" alt="image" src="https://user-images.githubusercontent.com/4640135/194487708-0d2c3e43-deef-4102-94c1-43ad551c5959.png">

cc @sterlinghirsh

**Comment by sterlinghirsh** [comment]
Sorry about the mismatch. In prod, we regularly sync inventory between our db and Shopify, both whenever there's a change and on a cron task just in case. On ifixit-test it doesn't run the crontask, and since we're not buying and stocking products all the time, it can get out of sync. I just ran a manual resync and it updated 3850 products with mismatches. That could be the source of the problem. In the future, we may want to update the available number based on maxToAdd, but if it works well enough for now after syncing the inventory, then I'm okay with it for now.

**Comment by dhmacs** [comment]
> Part 2
Apply an overall limit to how many of a single item a person can add to their cart. Right now, it's 20 for regular customers.

How does this work? Is this something that the us store is already implementing? Because I've been able to add more than 20 items without seeing any warning

**Comment by erinemay** [comment]
>I noticed that the inventory level in Shopify is different from the maxToAdd returned by the cart api

I may be wrong about the 20. I remember it being implemented somewhere, maybe on a Shopify-v2 branch, but I hadn't heard since what our limits are or if they've changed. If that field exists, it might be that. 

I'll rely on @jeffsnyder to say what cart limits are beyond availability.

**Comment by jeffsnyder** [comment]
@erinemay there is no limit enforced for ifixit.com. 

We have a limit defined in Shopify Theme Settings: 

![image](https://user-images.githubusercontent.com/7053450/194929826-e4c714a4-4736-408b-881c-d8a1b0d8d767.png)

But the Shopify Theme doesn't manage the ifixit.com product page so this is not enforced. We do have the limit set in AU/CA and EU Stores.

**Comment by dhmacs** [comment]
@jeffsnyder do we want to add a limit or can we keep it as it is right now?

**Comment by jeffsnyder** [comment]
@dhmacs I don't care about this feature in US/AU/CA and I don't want to figure out how to manage this differently for different stores until we start consolidating multiple stores on the react framework. Hopefully this will not be a requirement for the EU. Is that fair @sterlinghirsh or am I being too lazy? 😅

**Comment by sterlinghirsh** [comment]
I'm fine with having no limit for now. We can always add it later. I think the only thing to do here is updating the count after adding to cart. I think the count shown should always be qty in stock - qty in cart.
