### ISSUE TITLE
Add product list subnavigation

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#8]
## ✨ Updated

This idea has evolved into a more structured sub-navigation for product lists:

<img width="949" alt="Screenshot 2022-01-12 at 09 05 59" src="https://user-images.githubusercontent.com/4640135/149087916-3cf2bd31-c9d2-41a3-bed9-5be7f2e7ca96.png">

So the task is now to implement this new navigation. 

- [x] Add "Guides" link to device page (e.g. https://www.ifixit.com/Device/iPhone_X)
- [x] Add "Answers" link to answers page (e.g. https://www.ifixit.com/Answers/Device/iPhone_X)

This sub-navigation should be recreated across device and answers page too, but that work should be tracked separately.

> ## Outdated description
> The collection page should show a section titled "Model history" like this:
> 
> ![Screen Shot 2021-05-10 at 18 26 43](https://user-images.githubusercontent.com/4640135/117692403-489b3a80-b1bd-11eb-8637-81bbe88b1b71.png)
> 
> ## ❓Open questions
> 
> - Is this applicable to every collection?
> - What API should we use to get the content of the section?
> 
> ## UPDATE
> 
> - [x] Add text field `deviceTitle` in Strapi collection
> - [x] Decide where to put the link
> - [x] Create the link following this pattern: `https://www.ifixit.com/Device/<DeviceTitle>` where `<DeviceTitle>` should be replaced with the device title with spaces replaced by `_` and then it should be url encoded.

**Comment by sterlinghirsh** [comment]
There's no api for this yet. We have a heading in some of our device wikis called model history, but there's currently no standardization or code support around this yet.

**Comment by kwiens** [comment]
For now, let's just display all information returned as body text for the device page. For [this page](https://www.ifixit.com/Device/MacBook_Pro_15%22), that's everything below Background and Identification.
https://www.ifixit.com/api/2.0/doc/Wikis#list-wikis

**Comment by JFleischhauer** [comment]
What's the benefit of copying that text from the device pages to the store collection pages? What's the long-term strategy? 
I'm all for adding information to the collection pages, but that should be beneficial to the user, helpful for his buying decision, building trust in iFixit, etc., or at least improve our internal linking. 

These are our most important store collections, and it would _really_ help to have useful text and links here. The API can only pull text from devices (right?), so `/Tools/*` remains empty. `/Store/Parts` has no matching device, so it's empty as well. 

URL | Organic Clicks (Last 3 months)
-- | -- 
https://www.ifixit.com/Store/Tools/Toolkits | 16,259 
https://www.ifixit.com/Store/Tools | 8,118 
https://www.ifixit.com/Store/Parts | 6,964 
https://www.ifixit.com/Store/iPhone | 4,012 
https://www.ifixit.com/Store/Mac/MacBook-Pro | 3,367 

Having an API pulling text automatically sounds nice, but we need to be able to manually edit that text to actually benefit from it.

**Comment by dhmacs** [comment]
> For now, let's just display all information returned as body text for the device page. For [this page](https://www.ifixit.com/Device/MacBook_Pro_15%22), that's everything below Background and Identification.
> https://www.ifixit.com/api/2.0/doc/Wikis#list-wikis

@kwiens I'm sharing the same concern of @JFleischhauer here. 
Generally speaking, having duplicated content can harm SEO, do we really want to have duplicated content? 

Seems there's a lot of overlapping content between device pages and collection pages anyway. As a user I would probably like this to be a fully integrated experience (finding products that I need while I browse guides to fix my stuff).
I know this looks like a lot of work so my question is: what does "model history" add to the collection page, given that we already have the collection description? Couldn't we just add a link to the device page instead?

**Comment by JFleischhauer** [comment]
Don't get me wrong—I'm all for having some kind of collection description. There are many great examples of online stores doing this, just scroll to the bottom of any of these: [Eis.de](https://www.eis.de/erotische-literatur) (including some nice FAQ content related to the collection), and [Bergfreunde](https://www.bergfreunde.de/sonnenbrillen/), [Koro Drogerie](https://www.korodrogerie.de/superfoods/) and [HHV](https://www.hhv.de/shop/en/merchandise) (all including great internal links and additional information). Others have it at the top with a "Show More" accordion, which also works great.

**Comment by dhmacs** [comment]
@JFleischhauer we already have a collection description on the page. Look here for example:
https://react-commerce-gapb3dn71-ifixit.vercel.app/collections/iphone

<img width="1401" alt="Screen Shot 2021-06-23 at 14 51 43" src="https://user-images.githubusercontent.com/4640135/123099501-88974380-d432-11eb-84b1-0bfb3be93114.png">

**Comment by JFleischhauer** [comment]
No idea why in your collection the text refers to the PowerBook G4, so I'm taking the [iPhone 8 collection](https://react-commerce-gapb3dn71-ifixit.vercel.app/collections/iphone-8) as an example. 

- The first half is identical over all collection pages with only the device name and category being changed. 
"Grab a toolkit for your [device name] model and fix your broken [category name]! iFixit has you covered with parts, tools, and free repair guides. Repair with confidence! All of our replacement parts are tested to rigorous standards and backed by our industry-leading warranty." 
- The second half is release information that can be found everywhere on the internet, it doesn't include any internal links or additional information about the repair of the specific device. 

How is that a useful text for customers or SEO? In conclusion, I would say it doesn't matter if we have that text or not—there is no benefit for customers or search engines in reading this text.

**Comment by dhmacs** [comment]
> No idea why in your collection the text refers to the PowerBook G4, so I'm taking the [iPhone 8 collection](https://react-commerce-gapb3dn71-ifixit.vercel.app/collections/iphone-8) as an example.
> 
> * The first half is identical over all collection pages with only the device name and category being changed.
>   "Grab a toolkit for your [device name] model and fix your broken [category name]! iFixit has you covered with parts, tools, and free repair guides. Repair with confidence! All of our replacement parts are tested to rigorous standards and backed by our industry-leading warranty."
> * The second half is release information that can be found everywhere on the internet, it doesn't include any internal links or additional information about the repair of the specific device.
> 
> How is that a useful text for customers or SEO? In conclusion, I would say it doesn't matter if we have that text or not—there is no benefit for customers or search engines in reading this text.

The data is coming from a test store, so my guess is that it's like a lorem ipsum description. Obviously I agree with you, this eventually needs to contain some description that is useful and unique to the collection. The point is that probably another section containing another description is not necessary, we can just keep the collection description at the top and maybe add a link to the device page so that the user can find more details.

**Comment by JFleischhauer** [comment]
we can just keep the collection description at the top and maybe add a link to the device page so that the user can find more details.

> yep, agree on that!

**Comment by dhmacs** [comment]
The next step here is to add a link to the device page somewhere below the collection description and skip this section.

**Comment by dhmacs** [comment]
@sterlinghirsh Can you confirm that I can build the link to device pages like this `https://www.ifixit.com/Device/<DeviceTitle>` where `<DeviceTitle>` comes from Strapi ProductList model?

**Comment by sterlinghirsh** [comment]
Yes that should work. We transform that value slightly by replacing spaces with underscores and then urlencoding. In php it's `return urlencode(str_replace(" ", "_", $title));` There's also a separate display title for the device we use sometimes. I might end up wanting to make another strapi field in the future to store that but for now using the title with that transformation should be fine if that works for you. Also this isn't strictly related to this issue but we should probably have a config setting for the domain of these urls so we can point the dev version at cominor.

**Comment by dhmacs** [comment]
@sterlinghirsh I was planning on adding that setting to the store model
