### ISSUE TITLE
Create collections on Strapi

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#80]
Collection data (like title, description, breadcrumb, etc) is fetched from Strapi. We need to make sure that we have all categories available on Strapi by syncing them from iFixit api.

@evannoronha let me know when you want to discuss about this

**Comment by lithobraking** [comment]
I believe this issue is no longer relevant!
<img width="855" alt="Screen Shot 2021-11-23 at 2 54 12 PM" src="https://user-images.githubusercontent.com/34843669/143141863-de48422c-adea-464a-8bbb-b6619dffbff4.png">
