### ISSUE TITLE
Make sure we don't canonical redirect away from ?worksin filtered pages

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#817]
These are pages we get to from workbench. I've seen page loads where after the page load completes, we canonical redirect. This might be related to algolia's url handling.

Example: https://www.ifixit.com/Parts/PlayStation_4?worksin=PlayStation%204%20CUH-11XXA (From workbench after adding a specific topic)

**Comment by sterlinghirsh** [comment]
Note to self: example

**Comment by masonmcelvain** [comment]
[Algolia url handling](https://www.algolia.com/doc/api-reference/widgets/history-router/react-hooks/) is stripping any query params that are not used by algolia.

The `worksin` param is not used by Algolia, so it is stripped. The syntax Algolia recognizes is https://www.ifixit.com/Parts/PlayStation_4?filter[worksin][0]=PlayStation%204%20CUH-11XXA. Notice that the filter is applied, and the url is unmodified.

![image](https://user-images.githubusercontent.com/52104630/200396215-9cb62e23-0788-4954-a2a4-e9383caf1717.png)

Should this issue be "don't strip unused query parameters"?

Or "detect the worksin parameter and map it to the syntax algolia recognizes"?
