### ISSUE TITLE
Render but hide additional Item Types (RefinementSingleSelect)

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#819]
[`render-all-item-types`](https://github.com/iFixit/react-commerce/compare/render-all-item-types)

## Problem
We show the first 10 item types with a "Show More" button if there are more. We make these selections links and include an href for SEO reasons (i.e. to tell Google to index these item type pages). However, because we only render the first 10, we won't necessarily show Google the whole list.

## Do This
Similar to how we render the Child Product Lists with their Show More button, let's render the whole list of Item Type links, but use CSS to hide the remainder of the list rather than omitting the components.

**Comment by dhmacs** [comment]
This was done with [this issue](https://web.dev/dom-size/) in mind. By the way,  are we sure that the crawler would care about the whole list if it's visually hidden? I might be wrong, but from what I know google performs a visual analysis on the page to decide how to index it 🤔

**Comment by sterlinghirsh** [comment]
I agree we should avoid excessive dom size, but I really only care about doing this for this one facet, since it's the one with real links. Even if we did it for all singleselects, though, I don't really think it's that many more nodes. I'm bringing it up because IIRC when we do crawls for testing, the tool we use doesn't find the links hidden behind the show more button. Google's tool is certainly more complex, but I still don't know if they'll click every "show more" button to find more links that aren't in the dom. I remember hearing that they will find links inside disclosure elements, but I don't know if there's a special way we have to tag it or what.
