### ISSUE TITLE
ProductList: Do not include "empty" ProductLists in gallery of Children

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#822]
The E-commerce Team doesn't have a good way to know when we should publish new ProductList Collections.

When we create a Product for a new Device, we create the Device and we create the ProductList. We then leave the ProductList disabled until the compatible Products are activated in our store. If we enabled the ProductList as soon as we create it, we'd have empty ProductList pages super prominently linked in lists of Children. If we wait to enable the ProductList when we enable the Product, we need to keep track of which new/disabled Products will require ProductList enabling when the Product is enabled ... that's a rather annoying thing to keep track of. 

We'd like to be able to create, fully configure, and publish ProductLists in one step. And then have the ProductList "show up" in a list of Children once it has Products enabled. 

![image](https://user-images.githubusercontent.com/7053450/195453696-775f7457-ba75-464e-baa3-394f7ad82647.png)

We already noindex ProductLists with 0 Products. 

Please drop ProductLists with 0 Products from the list of Children. 

CC @dhmacs @sterlinghirsh

**Comment by sterlinghirsh** [comment]
We talked about this a bit before, but I think we can use the list of values from the device facet and intersect it with the list of children. This approach may not work if there are >200 devices in the facet list, but let's try it and see if it works.

**Comment by jeffsnyder** [comment]
Here are a couple current examples. We've created pages but products are not yet for sale. These are prominent/high up the browse tree: 

https://www.ifixit.com/Parts/Computer_Hardware
https://www.ifixit.com/Parts/Samsung_Galaxy_S22

**Comment by dhmacs** [comment]
We've been working on this [here](https://github.com/iFixit/react-commerce/pull/1091), but the solution we picked presents its own challenges.
An easier fix for this might be to just add a flag on the product list strapi record

cc @sterlinghirsh

**Comment by jeffsnyder** [comment]
How is a flag different from just disabling the ProducList? We don't want to disable because of what I said initially:

> The E-commerce Team doesn't have a good way to know when we should publish new ProductList Collections.

**Comment by dhmacs** [comment]
> How is a flag different from just disabling the ProducList? We don't want to disable because of what I said initially:
> The E-commerce Team doesn't have a good way to know when we should publish new ProductList Collections.

My bad, I've forgot about this context. Btw I'll keep discussing this on the PR
