### ISSUE TITLE
Product Page Feature Image Alt Text 

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#823]
On this page, https://react-commerce.vercel.app/Products/iphone-11-screen, and I assume all other products, the alt text for the main feature image of the product is the item # (alt="IF426-000-2" in this case). Compared to our current product page where the alt text of the main feature image of the product is essentially the product variant name (for https://www.ifixit.com/Store/iPhone/iPhone-11-Screen/IF426-000?o=2, it's "alt="iPhone 11 Screen / Fix Kit / New"") - I actually don't know exactly what we're using but it's pretty close to the product variant name, I'm sure a Dev can see easily what we're using. 

Can we make the alt text for our main feature image of the product something better than the item #? It seems like sticking with what we do currently is fine for now. 

This is also relevant for any product image. It seems like we're using item # for any/all images in the gallery. We should at least just do what we're doing currently. We can come up with even better templates in v2.1 or later.

**Comment by sterlinghirsh** [comment]
We set the alt text field in Shopify to the sku as a hack to enable mapping our product images to shopify variants, but we can override that in the template with the product title. @ifixitmaxb I don't know if you care whether we say "iPhone 11 Screen" or "iPhone 11 Screen / Fix Kit / New". It's slightly easier imo to use the product title for all the images, but if you think the variant specifier will matter then we can do it.

**Comment by ifixitmaxb** [comment]
Eventually, ideally, I'd like for each image to have unique alt text and to be actually descriptive, explicit, to each image. So if the image is of the contents of the fix kit then "iPhone 11 Screen Fix Kit" and if it's an image of the part only then "iPhone 11 Screen" or "iPhone 11 Screen Part Only" or something like that. It's ideal if the alt text is as descriptive as possible and that not every image has the same alt text. But for v2 launch, anything is better than the item #, which means nothing to anybody, especially visually impaired. So I'm find with "iPhone 11 Screen" for now and we can improve it later?
