### ISSUE TITLE
Add structured data on Product Page

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#853]
Add jsonld

This doc lists "Required" properties, as well as some other properties that it'd be great to implement later: https://docs.google.com/document/d/1gprBDfp7ZQ7nG57DE45JOMG4YNr8F7uqr2lCQTBiMyA/edit#

**Comment by ifixitmaxb** [comment]
In general, my hope is that we simply keep the same Schema that we have on legacy for v2.0. But I found at least one example of an issue on legacy Schema that we should try to fix, which would be an improvement/iteration, for v2.0. 

For the example page, https://www.ifixit.com/Store/Mac/MacBook-Pro-13-Inch-Retina-Early-2015-Battery/IF123-054?o=1, here is the Rich Results Test,
https://search.google.com/test/rich-results/result/r%2Fproduct?id=BEByUQRlYj_hNUl3ew5XbQ, the 2 "non critical issues" says we're missing review and aggregate review:
![image](https://user-images.githubusercontent.com/86265382/198345642-ff51bd83-c2ba-4211-85c0-0eee2e5eff54.png)

**Comment by sterlinghirsh** [comment]
Any movement here? @davidrans said that we've lost "rich results" on the new pages, so we should get this working again asap.

**Comment by davidrans** [comment]
Here's an example of what we're passing on the Pro Tech Toolkit page: https://search.google.com/test/rich-results/result?id=QqXl7U1WWc98tIXer8yAAA

**Comment by ifixitmaxb** [comment]
I'll have more direction on structured data I can share on Tuesday next week.

**Comment by ifixitmaxb** [comment]
https://docs.google.com/document/d/1gprBDfp7ZQ7nG57DE45JOMG4YNr8F7uqr2lCQTBiMyA/edit#
