### ISSUE TITLE
Product review count in Featured Products inconsistent

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#859]
<details><summary>In the Featured Products section, the PTT has 1361 reviews, and the Mako has 390</summary>
https://react-commerce.vercel.app/products/2-tb-ssd-hybrid-3-5-hard-drive

![image](https://user-images.githubusercontent.com/72166715/197233680-e6734e5d-c7ff-42ff-be51-111129dbbedb.png)

</details>

On the product page, the PTT has 1447, and the Mako has 420
https://www.cominor.com/Store/Tools/Pro-Tech-Toolkit/IF145-307#productReviews
![image](https://user-images.githubusercontent.com/72166715/197233779-0561290f-ef31-4f78-90f8-9b8b72100bd3.png)

https://react-commerce.vercel.app/products/mako-driver-kit-64-precision-bits#reviews
![image](https://user-images.githubusercontent.com/72166715/197233816-293895bc-0915-4ff3-b0b0-9f95bf6b6b06.png)

**Comment by dhmacs** [comment]
Just for context: featured products get the review count from a Shopify metafield, while the product page review count comes from the iFixit api, so it's likely a data sync issue

**Comment by dhmacs** [comment]
@masonmcelvain Is there anything that prevents us from keeping the data in sync?

**Comment by erinemay** [comment]
I don't think it's worth it to keep the pages looking synced just in dev. It would be nice if we could keep ifixit-test more up to date. Is this a similar issue to the issue here https://github.com/iFixit/react-commerce/pull/829#issue-1407932357?

**Comment by dhmacs** [comment]
> Is this a similar issue to the issue here [#829 (comment)](https://github.com/iFixit/react-commerce/pull/829#issue-1407932357)?

Not exactly, in that context it made sense to use more up to date data from the ifixit api as the user made changes to his cart.
Here instead we would have to make more requests to the ifixit api. Besides this, I remember that @sterlinghirsh was thinking about putting reviews into metafield. If we do so, the problem described by this issue would disappear entirely

**Comment by masonmcelvain** [comment]
> @masonmcelvain Is there anything that prevents us from keeping the data in sync?

Just so I understand correctly, the metafield we're concerned with is `product.metafields.reviews.rating_count`, correct?

I think we would have to repush all product data every time a user makes a product review in order to keep this metafield up to date. This is easy to do, but I don't think we are currently doing it.

> Besides this, I remember that @sterlinghirsh was thinking about putting reviews into metafield.

@sterlinghirsh is this planned? If not, we should repush product data to Shopify when a review is made instead.

**Comment by sterlinghirsh** [comment]
I think keeping the values up to date when reviews happen is a good call. I'm curious if we'll see things get out of sync in prod, but we'll keep an eye on it. I don't think I want to try to put the reviews themselves in a metafield at this point. Maybe we'll put the first 3 to simplify the initial load and then use the api for subsequent pages, but unless performance is an issue, I'm not in a hurry to change it now.

**Comment by sterlinghirsh** [comment]
Since https://github.com/iFixit/ifixit/pull/45303 is merged, I'll close this issue for now and we can reopen it if we're still getting inconsistent results.

**Comment by danielcliu-ifixit** [comment]
I still see these occasionally on the live site 
![Screenshot from 2022-11-01 22-49-00](https://user-images.githubusercontent.com/109113415/199408659-038316d0-d71e-4cf6-a67f-d5b6d5986d9f.png)

![Screenshot from 2022-11-01 22-49-13](https://user-images.githubusercontent.com/109113415/199408676-8c245d10-9050-45ce-9110-5aa20cda63e4.png)

**Comment by masonmcelvain** [comment]
It seems like we calculate the review count differently in different places. Maybe that's causing the mismatch?

In `ProductBodyFactory`, we use the rating count of the first variant in the group.

https://github.com/iFixit/ifixit/blob/94806252542b636642ce66755fd36d5181fcebc4/iFixit/Service/ShopifyWebhook/ProductBodyFactory.php#L413-L414

In `AlgoliaProductGroupHandler`, we call through to [`ProductReviews`](https://github.com/iFixit/ifixit/blob/94806252542b636642ce66755fd36d5181fcebc4/Cart/Objects/ProductReviews.php) which uses a query to come up with the rating count.

https://github.com/iFixit/ifixit/blob/94806252542b636642ce66755fd36d5181fcebc4/Cart/Objects/Review.php#L45-L54

**Comment by erinemay** [comment]
There's also a difference within a single product page: 
https://www.ifixit.com/products/lightning-to-usb-charging-cable

Review count at the buy box:
![image](https://user-images.githubusercontent.com/72166715/204669891-661eca3a-4634-41cd-8fb5-eb512a954992.png)

Review count at the review section: 
![image](https://user-images.githubusercontent.com/72166715/204669915-bc59a97e-245f-4950-b534-9bdd88c2f4f6.png)

If this isn't closely enough related, I can make a new issue.

**Comment by dhmacs** [comment]
@erinemay it's the same issue, one piece comes from metafields, another one from the API
