### ISSUE TITLE
Frequently Bought Together selection retained when returning to a product page

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#860]
When you enter a new product page via a link on the page like the Frequently Bought Together and return to that page without prompting a full page refresh, the frequently bought together selections are retained.

Video:
Flipping back and forth between the portable anti-static mat and the magnetic mat: Each time I get to the new page, my previously selected frequently bought together options on that same page were still selected.

https://user-images.githubusercontent.com/72166715/197232413-b2c1ce6e-4c83-4f6e-8fd0-fe5950cf4608.mp4

**Comment by sterlinghirsh** [comment]
@danielbeardsley recommends putting a `key={selectedVariantid}` at a high level or at least on the featured product components, since he says that will separate the state.
