### ISSUE TITLE
Add scroll buttons to image thumbnail list

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#861]
Without scroll indicators, it's unclear that there are more thumbnail images available to click on.

This product has more images than can fit in the row of thumbnails.
https://react-commerce.vercel.app/products/Precision-Tweezers-Set

![image](https://user-images.githubusercontent.com/72166715/197079481-8890fc5c-2d12-40c1-9143-f742099e55a8.png)

**Comment by dhmacs** [comment]
cc @mmarcon91

**Comment by mmarcon91** [comment]
The first thing we can do is to put the active image always as the first in the list.
Example: https://g4pu3l.csb.app/

Alternatively, we could bring the navigation arrows next to the list. But I would have to rethink the design
