### ISSUE TITLE
Retain scroll position after clicking back button

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#863]
After clicking on ~~the warranty link~~ a link and then using the back button to return to the product page, I'm farther down the page and not well oriented as to where I am.

This is present on desktop and mobile 
<details><summary>Screen recording in on Windows + Chrome</summary>

https://user-images.githubusercontent.com/72166715/197239360-c9710528-8cc2-472f-8ec9-ccb51c915bc1.mp4

</details>

<details><summary>Also present on mobile. Screen recording is on Pixel 6/Android 13 + chrome</summary>

https://user-images.githubusercontent.com/72166715/197239735-8e3dbdce-632d-46b7-a5d1-ee411d4179ee.mp4

</details>

**Comment by federicobadini** [comment]
In one of the latest refactoring I see that the variant warranty link is now opening with `target=blank` - see [here](https://react-commerce.vercel.app/Products/iphone-11-screen)

If `target=blank` is the desired behaviour, this issue is obsolete.
Other links on product page seems to behave correctly.

**Comment by erinemay** [comment]
Oh perfect. That works 👍

**Comment by sterlinghirsh** [comment]
Turns out this is a bug on non-warranty pages too. From Jeff: "When clicking on a Featured Product link, then clicking back, the browser zips down to the bottom of the page and then back up. It's a wild ride."

**Comment by jeffsnyder** [comment]
I filed an issue for this and a possibly related problem in react-commerce: https://github.com/iFixit/react-commerce/issues/945

**Comment by federicobadini** [comment]
closed in favour of #945
