### ISSUE TITLE
iFixit News URLs are doubled stacked with iFixit Domain

### ISSUE THREAD

**Issue by ardelato** [iFixit/react-commerce#88]
# Description

While QAing https://github.com/iFixit/react-commerce/pull/87 I noticed that while hovering over the iFixit news cards that the url it links to has `ifixit.com` declared twice

![News Article links are doubled stacked](https://user-images.githubusercontent.com/22064420/134376861-a69b2b91-df41-462f-a447-4e0ccc4f5ed3.png)

https://user-images.githubusercontent.com/22064420/134376872-ea9879df-561e-43f7-bf09-8f1a38868d94.mp4

**Comment by dhmacs** [comment]
@ardelato I get this directly from the API. Can you tag someone who can fix this?

![image](https://user-images.githubusercontent.com/4640135/134388787-39198aa3-5a62-4b42-9093-71576dc82d4f.png)

**Comment by ardelato** [comment]
@batbattur or @Annika29 does this have to do with anything on Valkyrie's side?

**Comment by batbattur** [comment]
Yes, it was added in https://github.com/iFixit/valkyrie/pull/502. @dhmacs do you need just the `/News/...` permalink part without the site URL?

**Comment by ardelato** [comment]
@dhmacs looks like it is on our API side.

Would you prefer to close this issue or use it for tracking and close it once we resolve it on our end?

**Comment by dhmacs** [comment]
@ardelato let's keep this open, so when we review the status before going live we'll remember to double check that this is fixed

**Comment by ardelato** [comment]
Rodger that 👍

**Comment by batbattur** [comment]
Now the extra domains are removed and permalinks have been fixed.

Preview: https://www.ifixit.com/api/2.0/related-posts?data={%22tags%22%3A[%22Parts%22%2C%22android%22]}

Feel free to close this issue 👍
