### ISSUE TITLE
Collections: "Choose a tool type" vs "Choose model"

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#882]
We aren't currently using Parent and Children functionality for our Tools Collections. We want to asap. For example, making "Tri Point Screwdrivers" a child of "Drivers and Wrenches". 

Currently, the "choose a model" section on https://www.ifixit.com/Tools actually shows "Choose a tool type":
![image](https://user-images.githubusercontent.com/86265382/197865808-c30ed02a-4d88-415b-ac53-9c5d77c0f9fb.png)

If I create a child collection, the section is then "Choose a model", which is what we use on Parts but I'm not sure if it's best for Tools:
![image](https://user-images.githubusercontent.com/86265382/197865979-f050243b-c4cb-4324-a236-bf7f34a9f770.png)

Should we change "Choose a model" to "Choose a tool type" or "Choose a type"?

**Comment by sterlinghirsh** [comment]
I don't think this is right. Pretty sure we do use parent/child in tools. There's a field called childrenHeading in strapi to control this. For example, I just updated the drivers and wrenches page childrenHeading:

![image](https://user-images.githubusercontent.com/589425/197913469-24082b93-fbc1-4443-add2-086cb5d61d10.png)

**Comment by ifixitmaxb** [comment]
I'm sorry, I didn't know there was this childrenHeading field in Strapi. That's great! Thank you!
