### ISSUE TITLE
Fix decimal point display

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#886]
As a pro user, the trailing 0 on the price is truncated: https://react-commerce.vercel.app/Parts?q=macbook%20battery
![image](https://user-images.githubusercontent.com/72166715/197895970-1565a25c-9505-40d2-8c47-2a6b1169c191.png)

**Comment by danielbeardsley** [comment]
I'd bet this happens with non-pro prices too, we just don't have many that end in 0.

**Comment by dhmacs** [comment]
We've recently introduced a component to standardize how we show prices (`ProductVariantPrice` in the `@ifixit/ui` package). I think just refactoring that code to use this new component would fix this
