### ISSUE TITLE
Pro discounts can be pointlessly small

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#887]
![image](https://user-images.githubusercontent.com/72166715/197897265-e3555e07-5d7f-4a59-a3ce-c8a8fdf4e3fe.png)
https://react-commerce.vercel.app/Tools

While logged in as a pro user.

**Comment by erinemay** [comment]
Not sure what we want to do here instead. cc @sterlinghirsh @jeffsnyder

**Comment by danielbeardsley** [comment]
Put a lower limit. Don't show normal price *nor* a discount % if less than 2% ?

Or leave this and check our pro prices. 3.95 vs 3.99 is unintentional I'm sure. Might be worthy of query and a dashboard.

**Comment by jeffsnyder** [comment]
This is something Scott / E-commerce will fix in Akeneo. I do not believe this is purposeful.

**Comment by dhmacs** [comment]
Closing as this will be fixed in Akeneo
