### ISSUE TITLE
Make links more obvious

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#888]
"Learn more" is now a link, but it doesn't look like it. Let's make that link blue.
![image](https://user-images.githubusercontent.com/72166715/197900720-fba98d13-9ef7-4566-b69c-b9d2d927391b.png)

https://react-commerce.vercel.app/products/google-pixel-3a-xl-replacement-battery-genuine

Some of these are links too (in the kit contents dropdown)
![image](https://user-images.githubusercontent.com/72166715/197900905-ddb7e55a-2339-42e1-8959-812922cb8082.png)

**Comment by dhmacs** [comment]
I've run this by @mmarcon91 and he'd like links to be bold and underlined instead of blue, since they look better against colored backgrounds.
