### ISSUE TITLE
Use variant metafield "Description"

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#889]
This product's variants have different descriptions, but they don't change when variant is switched. 
https://react-commerce.vercel.app/products/p5-pentalobe-screwdriver-retina-macbook-pro-and-air

![image](https://user-images.githubusercontent.com/72166715/197901338-c23abc21-300b-464d-b8fe-d215ce4a621b.png)

Here are the two variants on ifixit
https://www.ifixit.com/Store/Tools/P5-Pentalobe-Screwdriver-Retina-MacBook-Pro-and-Air/IF145-090?o=2
https://www.ifixit.com/Store/Tools/P5-Pentalobe-Screwdriver-Retina-MacBook-Pro-and-Air/IF145-090?o=8

**Comment by dhmacs** [comment]
This is using the product description. So I guess we should use the variant `Description` metafield instead
