### ISSUE TITLE
Make pro only products not for sale

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#897]
Example product: https://react-commerce.vercel.app/products/20-lb-steel-shot-bag
![image](https://user-images.githubusercontent.com/72166715/197907773-72e35aae-66e4-4a74-8b5f-bf275df2f4c1.png)

**Comment by erinemay** [comment]
This is a better example and a more important one. We're contracted to only show and sell this to pros.
https://www.ifixit.com/Store/Tools/Surface-Display-Debonding-Tool-M1214770-001/IF265-010?o=1

cc: @jeffsnyder @sterlinghirsh

**Comment by dhmacs** [comment]
@erinemay The not for sale UI should be shown to non-pro users right?

@mmarcon91 I think we need a "Not for sale" UI here

**Comment by mmarcon91** [comment]
I work on it today

**Comment by mmarcon91** [comment]
I made a new design: https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=7573%3A115651

**Comment by dhmacs** [comment]
@sterlinghirsh How do I know that the product is pro only? By looking at the product tags?
