### ISSUE TITLE
Collections: add a Display Title or "h1" field in Strapi

### ISSUE THREAD

**Issue by ifixitmaxb** [iFixit/react-commerce#898]
I want to optimize the h1 of our Collections for SEO but sometimes that keyword is longer than it needs to be for other purposes, like breadcrumb or other navigation links like the "Choose a model" links. 

For example, I want our "Precision Phillips Screwdrivers" page to have the h1 optimized for that keyword but ideally the link under Choose a model would just be "Phillips Screwdrivers" or even just "Phillips". 
<img width="769" alt="image" src="https://user-images.githubusercontent.com/86265382/197947455-00992657-c1f6-48a2-b658-cbe876a89d73.png">

So either we would need a field for "display title" or "h1" or else a way to edit the navigation and breadcrumb link anchor text.

**Comment by ifixitmaxb** [comment]
@jeffsnyder loves more fields

**Comment by jeffsnyder** [comment]
Can we make it an "override default when exists" field rather? If so, go for it.

**Comment by ifixitmaxb** [comment]
This is definitely what I would want too. I think that is how the meta title field works already.
