### ISSUE TITLE
Prop 65 visible when it shouldn't be

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/react-commerce#907]
Currently, the Prop 65 warning required for California residents shows up no matter where the user is located. This should not be the case. The warning being visible should be dependent on the user's location. In California, show the warning. Not in California, do not show the warning.

![image](https://user-images.githubusercontent.com/33426643/198110041-0c9e2665-a7de-4378-9c3e-48bd93ffbc22.png)

**Comment by sterlinghirsh** [comment]
We show it everywhere because geoip is not completely reliable and it's worse to not show it than to show it to too many people.
