### ISSUE TITLE
Variant redirects append default variant param allowing users to have multiple variant params

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#919]
@ifixitmaxb was testing redirects and found https://www.ifixit.com/Store/iPhone/iPhone-11-Battery/IF426-001?o=2 is redirected to https://www.cominor.com/products/iphone-11-replacement-battery?variantid=39333882822746.

That variant is the default variant so it's url is actually https://www.cominor.com/products/iphone-11-replacement-battery, without the param.

Once a user gets to that page with the default variant param, if they choose the other variant, it appends the next variant param to that url to get https://www.cominor.com/products/iphone-11-replacement-battery?variantid=39333882822746&variant=32965709430874.

**Comment by dhmacs** [comment]
We saw this with @sterlinghirsh during the call, it's a type on where you set the redirect, the param is `variant` not `variantid`
