### ISSUE TITLE
Incorrect variant redirect

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#920]
(Also not entirely sure if this is on the ifixit or react side)

https://www.cominor.com/Store/Mac/MacBook-Pro-13-Inch-Retina-Early-2015-Battery/IF123-054?o=1 is redirected to the incorrect variant: https://www.cominor.com/products/macbook-pro-13-retina-early-2015-battery?variantid=32965716115546

Found by @ifixitmaxb

**Comment by sterlinghirsh** [comment]
It should be variant vs variantid.

**Comment by danielcliu-ifixit** [comment]
closing in favor of #919 its the same issue
