### ISSUE TITLE
Featured Products section is fixed when zooming

### ISSUE THREAD

**Issue by jordycosta** [iFixit/react-commerce#921]
### Issue Overview:

When I zoom out of one of the product pages, it appears that all sections except for the featured product images will be zoomed out also. Here is an example shown below

![featured-products](https://user-images.githubusercontent.com/95656772/198346067-ec2f8f66-1c4e-4555-aece-f4a6cb38533f.png)

### Reproduction Steps:
1. Navigate to [a product page](https://react-commerce.vercel.app/products/iphone-11-pro-max-screen)
2. Scroll down to the featured products section
3. Zoom out of the webpage

**Comment by dhmacs** [comment]
What's the reason we care about this? Are there realistic use cases that require using big screens? Asking this since currently we're not optimizing the site for huge screens. 
A possible patch would be to add a wrapper at something like 2400px.

**Comment by jordycosta** [comment]
> What's the reason we care about this? Are there realistic use cases that require using big screens? Asking this since currently we're not optimizing the site for huge screens. A possible patch would be to add a wrapper at something like 2400px.

Not necessarily a specific reason, I just noticed that it wasn't following the same behavior as other page elements and wanted to point it out in the case this wasn't intended

**Comment by sterlinghirsh** [comment]
It is funny looking but I'm willing to say let's not deal with it for now.
