### ISSUE TITLE
Product Page buy box: spacing issues

### ISSUE THREAD

**Issue by davidrans** [iFixit/react-commerce#923]
Found a couple spacing issues:
![image](https://user-images.githubusercontent.com/806152/198363534-621dfb94-ce11-4934-93ef-c13ef7556667.png)

1. Need more space between "Only 2 left" message and Add to Cart button
2. The value props bullets look funny to me. I think they ought to be separated by the same amount of vertical space even if some are only 1 line

https://www.cominor.com/products/macbook-pro-14-2021-a2442-and-16-2021-a2485-antenna-cable-bracket

**Comment by sterlinghirsh** [comment]
Part 2 wontfix
