### ISSUE TITLE
Frequently Bought together: products should be links

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/react-commerce#924]
I don't know if this was discussed when the feature was made, but I think at least *some* portion of the product card ought to be a link that takes you to a product page, and it should be obvious which part.

![image](https://user-images.githubusercontent.com/26855/198366687-734fcf89-a710-4c9a-b348-19ff12d5b869.png)

I really doubt that people will add something to their cart without even being able to go to the product page

CC @sterlinghirsh @federicobadini

**Comment by dhmacs** [comment]
Looking at Amazon, the entire card link to the product, and the only the checkbox let's you deselect the product. We might do the same. Thoughts?

<img width="1082" alt="Screenshot 2022-10-28 at 13 49 38" src="https://user-images.githubusercontent.com/4640135/198580461-fd42839b-6994-4714-82a0-26d468fb006d.png">

**Comment by danielbeardsley** [comment]
> We might do the same. Thoughts?

Seems reasonable to me. Making it hard to learn more about the product is a turn-off when I'm interested in buying something. I don't think adding a product to the cart is a barrier in our system, so I don't think we need to push that.

**Comment by jeffsnyder** [comment]
E-commerce wants to match Amazon closely.

**Comment by dhmacs** [comment]
> E-commerce wants to match Amazon closely.

Like Amazon, but gorgeous 😂

**Comment by jeffsnyder** [comment]
@dhmacs that's _exactly_ what I meant 🎉
