### ISSUE TITLE
International Buy Box Banner

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#930]
We want to let people know when they're viewing a product page that is available in a store close to them. e.g. If a Canadian customer looks at a product, they should get a message suggesting they purchase from the Canadian store.

We use GeoIP to detect where the customer is, but you can force it on our legacy product page by adding a country=ca parameter to the product url, e.g. 
https://www.ifixit.com/Store/iPhone/iPhone-6s-Battery/IF314-011?o=10&country=ca

This is what it looks like:
![image](https://user-images.githubusercontent.com/589425/198401148-5059c4a1-1f92-4966-b836-0037c7b96d0a.png)

This replaces the Add to Cart button and quantity selector.

The buy from Canada Store link takes you to https://canada.ifixit.com/products/iphone-6s-replacement-battery (though it looks like we add a url param for tracking, so it ends up as https://canada.ifixit.com/products/iphone-6s-replacement-battery?pk_vid=ba9f6a8e9107d2f1166690605321f03f). The buy from USA Store simply hides this section and re-adds the Add to Cart section.

The GeoIP api is documented at https://www.ifixit.com/api/2.0/doc/Internal#returns-info-about-whether-a-product-is-available-in-a-non-us-store
The request is to https://www.ifixit.com/api/2.0/internal/international_store_promotion/buybox?productcode=314011 (or to force the country, https://www.ifixit.com/api/2.0/internal/international_store_promotion/buybox?productcode=314011&country=ca)

The api response looks like
```json
{
    "countryCode": "CA",
    "storeid": "ca",
    "storeName": "Canada",
    "storeUrl": "https:\/\/canada.ifixit.com\/",
    "salesChannel": "shopify.ca",
    "products": {
        "9": {
            "sku": "3140119",
            "optionid": 9,
            "productURL": "https:\/\/canada.ifixit.com\/products\/iphone-6s-replacement-battery",
            "price": "CA$34.99",
            "currency": "CAD",
            "avail": 1,
            "salesChannel": "shopify.ca",
            "gaSku": "314011-9"
        },
        "10": {
            "sku": "31401110",
            "optionid": 10,
            "productURL": "https:\/\/canada.ifixit.com\/products\/iphone-6s-replacement-battery",
            "price": "CA$42.99",
            "currency": "CAD",
            "avail": 1,
            "salesChannel": "shopify.ca",
            "gaSku": "314011-10"
        }
    }
}
```
Note that the response includes an entry for each variant keyed on its optionid. We may change this format later to make it simpler to use without trying to extract the optionid from the sku, but in the interest of getting this out asap, let's just use a regex to extract the sku from the current variant. There may not be a corresponding variant in the foreign store (CA) for each variant on the current store (US). Note that the entry includes the productURL for each variant. We still have to add a variant specifier to the productURL, but we can make that change separately. Just use the url as-is and accept that it may not match the selected variant.

We have Google/Matomo event tracking on this feature that we should make sure works.

When the International Buy Box is present / unresolved, we must hide the "Frequently Bought Together" section to ensure no "Add to Cart" action is available on the page.

The existing buy box is implemented in ifixit/ifixit
* Cart/UI/templates/Product/international_buy_box.phtml
* carpenter-frontend/Cart/international_product_banner.js
* Objects/Cart/InternationalStorePromotion/InternationalStorePromotionProductBanner.php

**Comment by sterlinghirsh** [comment]
TODO: Create an issue to update the response format on ifixit/ifixit.

**Comment by jeffsnyder** [comment]
Two things to add: 
1) We have Google/Matomo event tracking on this feature that we should make sure works. 
2) When the International Buy Box is present / unresolved, we must hide the "Frequently Bought Together" section to ensure no "Add to Cart" action is available on the page.

**Comment by danielbeardsley** [comment]
Work in progress:
https://github.com/iFixit/react-commerce/compare/intl-buy-box?expand=1

**Comment by masonmcelvain** [comment]
Oof, please assign yourself next time, I've been working on this for 30 min. Here's what I had so far, for your reference: https://github.com/iFixit/react-commerce/compare/intl-buybox

I'll let you keep working on it since it seems like you're farther ahead 👍🏻

**Comment by danielbeardsley** [comment]
I'm sorry Mason. I screwed up. Sterling asked me to work on it and I was jumping around and forgot. We can pair on it on Monday if you want.

**Comment by masonmcelvain** [comment]
No hard feelings! It happens. Lmk if you want to pair on it, but I'm happy to just give CR.

**Comment by jeffsnyder** [comment]
@sterlinghirsh Unsure if it's covered by this issue, we also need to make sure that switching countries in the country selector takes you to the correct page. 

Using the header selector in https://canada.ifixit.com/products/essential-electronics-toolkit takes you to https://www.ifixit.com/products/essential-electronics-toolkit. 

Using the footer selector in https://www.ifixit.com/products/essential-electronics-toolkit takes you to https://canada.ifixit.com.

**Comment by danielbeardsley** [comment]
> Unsure if it's covered by this issue, we also need to make sure that switching countries in the country selector takes you to the correct page.

Different code, different bug, still important. I think that belongs in a new issue.
