### ISSUE TITLE
Handle long lists of worksins

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#931]
https://www.cominor.com/products/HP-Pavilion-G4-G6-and-G7-Fan
<details><summary>yikes</summary>

![image](https://user-images.githubusercontent.com/72166715/198405180-307ac519-c597-4493-8571-20c0bf12a8cb.png)

</details>

We're not handling it on the legacy pages, but we should still fix it here.
https://www.ifixit.com/Store/PC-Laptop/HP-Pavilion-G4-G6-and-G7-Fan/IF273-014?o=1

<details><summary>yikes, but legacy</summary>

![image](https://user-images.githubusercontent.com/72166715/198405369-b1eacb64-5093-40bc-8676-a28beac18639.png)

</details>

**Comment by erinemay** [comment]
After https://github.com/iFixit/react-commerce/pull/935 was merged, a [ux issue was brought up by Jackie](https://ifixit.slack.com/archives/C0252FETV2S/p1667837002655909). (product: https://www.ifixit.com/products/galaxy-note10-plus-replacement-battery)

![image](https://user-images.githubusercontent.com/72166715/200360884-d176214c-f604-406a-9a9d-d1cca463a59d.png)

Users expect the "And 4 other devices..." to be an expandable element that shows the rest of the devices. It is not clear that this is a truncated version of the full list lower on the page. On products with more than 3 device compatibilities, we get the see all compatible devices link that goes to the full list, but 3 or fewer devices don't show that link.
![image](https://user-images.githubusercontent.com/72166715/200362568-3310b3fa-5215-461b-a5e5-d7f9b1ec5150.png)
 
Maybe the "And 4 other devices..." could link to `#compatibility` on the page?

cc: @danielcliu-ifixit, @sterlinghirsh

**Comment by sterlinghirsh** [comment]
use the term models instead of devices to refer to variants
