### ISSUE TITLE
Discount is overriding pro pricing

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#937]
If there's a discount and pro pricing, pros are seeing the discount regardless of pro pricing. 

Go to https://www.cominor.com/products/fix-the-world-t-shirt 

<details><summary>I set pro pricing for option 4 (default variant here), but as a pro, I'm still seeing the regular user discounted price</summary>

![image](https://user-images.githubusercontent.com/72166715/198672896-1d416a62-a173-47dd-8f89-140fb422fd2c.png)

</details>

As Pro Tier 1
![image](https://user-images.githubusercontent.com/72166715/198673254-4c9b6f40-c5bd-4399-a44e-93d0a03a4db6.png)

As Pro Tier 2
![image](https://user-images.githubusercontent.com/72166715/198673106-7c78a983-f175-41c0-9453-19b165336c7e.png)

Pros should see pro pricing instead of the discount

**Comment by erinemay** [comment]
https://github.com/iFixit/react-commerce/issues/938 is somewhat related, so I'll pull this over for clarity and posterity. 

>Only pro users should ever see the pro tag. Employees should never see the pro tag unless they are saved as pro users.
If there is a discount, but no pro prices, pros should see the discount price the same as everyone else.
The pro tag next to a price should only be shown if it is a pro price.

For this issue/product: 
Regular users and logged out should see the discount tags (working)
Employees should see the discount tags (seeing pro tags currently because of https://github.com/iFixit/react-commerce/issues/938
Pro users should see the pro discount tag alongside their corresponding tier price

**Comment by masonmcelvain** [comment]
So is the expected behavior here that the user should see the _lowest_ price available to them? For example, if the discount makes the product $4, and the pro price is $8, I would think the user should see $4.

**Comment by erinemay** [comment]
Yeah. That sounds right. I didn't think of the case where a discount would take it lower than the pro price.

**Comment by erinemay** [comment]
User should always see the lowest price available to them. If that is a pro price for a pro user, show the pro tag on the discount. If it's not, only show the red discount tag without the pro flair.
