### ISSUE TITLE
Add Variant-level information to Cart Drawer

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#946]
Our Cart Drawer does not include variant-level information (except the itemcode). Some color variant screens are _very difficult_ to tell apart visually. And things like [t-shirts](https://www.ifixit.com/products/standard-issue-t-shirt) have the same image on every size.
![image (37)](https://user-images.githubusercontent.com/7053450/198709168-a7078ac1-65ab-4225-ae20-322c57abed3c.png)

Let's add axis of variation information to product names in Cart Drawer. I suggest we use the same logic/structure as we use in our Product Reviews. 
![image (36)](https://user-images.githubusercontent.com/7053450/198709179-e17ffbc4-da41-481b-acbe-568b3ce62529.png)

(Similar issue for `/cart`: https://github.com/iFixit/ifixit/issues/45344)

CC @sterlinghirsh

**Comment by dhmacs** [comment]
cc @mmarcon91

**Comment by mmarcon91** [comment]
Cart: https://www.figma.com/file/jRG4EyQXRDMGfyLqut08KP/iFixit---Working-files?node-id=2288%3A11104

Components: https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=274%3A15335

**Comment by dhmacs** [comment]
@sterlinghirsh to move forward with this we need the iFixit cart api to return line item variant selected options

<img width="665" alt="image" src="https://user-images.githubusercontent.com/4640135/215458783-645308eb-ed37-4a39-932a-0d4720c00bec.png">

Currently this is what the API returns for products:

![Screenshot 2023-01-30 at 11 59 57](https://user-images.githubusercontent.com/4640135/215459199-c63d8928-faed-4460-9982-0d71885ef140.png)

**Comment by sterlinghirsh** [comment]
We'll need to add this to the cart api. I'm inclined to use a single string e.g. "Fix Kit / New" like we show on reviews rather than including each option name/value separately.

**Comment by dhmacs** [comment]
> I'm inclined to use a single string e.g. "Fix Kit / New" like we show on reviews rather than including each option name/value separately.

I don't have opinions on this, @jeffsnyder @mmarcon91, thoughts?

**Comment by mmarcon91** [comment]
> > I'm inclined to use a single string e.g. "Fix Kit / New" like we show on reviews rather than including each option name/value separately.
> 
> I don't have opinions on this, @jeffsnyder @mmarcon91, thoughts?

I think it's clearer with the option name + value, but if easier to manage, the list of values is fine too.

**Comment by jeffsnyder** [comment]
I'm happy with @sterlinghirsh 's suggestion. If we want to switch to include options + values, I'd probably want to standardize and make that change elsewhere as well.
