### ISSUE TITLE
Redirect Sitemap For Products

### ISSUE THREAD

**Issue by danielcliu-ifixit** [iFixit/react-commerce#950]
## Overview

Max has requested a vanity redirect for the product sitemap. So basically we'll redirect so I need https://www.ifixit.com/products/sitemap.xml to https://dozuki-sitemaps.s3.amazonaws.com/2/en/products.xml|

Similar to #488 

@ifixitmaxb

**Comment by ifixitmaxb** [comment]
I get a 404...

**Comment by danielcliu-ifixit** [comment]
i think it hadn't deployed. Confirmed working now
