### ISSUE TITLE
Design request: Change OOS Notify Me box color

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#951]
>Feedback from the team: Design request to change the color of the OOS notice. Blue vs. immediately obvious red.

https://react-commerce.vercel.app/products/macbook-pro-14-2021-a2442-right-fan
![image](https://user-images.githubusercontent.com/72166715/198714221-e4f65073-2ab0-4a24-b609-1e51b4fb9607.png)

Previously, before expanding to input email
![image](https://user-images.githubusercontent.com/72166715/198714338-1e7ea832-a17d-4778-a2cb-7e4bba5361ff.png)

cc: @jeffsnyder

**Comment by erinemay** [comment]
@jeffsnyder Any specifics here? I don't really dislike how it looks now, but I understand the need to have it clear that the item is OOS. Are you thinking change the color of the whole box, or just a portion?

**Comment by dhmacs** [comment]
cc @mmarcon91

**Comment by jeffsnyder** [comment]
Gray box with red "Out of Stock" text? Yellow box + text? I don't have a super strong opinion, just wanted to bring it up for a second consideration.

**Comment by mmarcon91** [comment]
New proposal: https://www.figma.com/file/sfj6r7Bn6eREMvuqo0f7Du/iFixit---Components?node-id=205%3A14293

I thought it would be better to separate the OOS message from the notification lead, I would avoid putting a negative color for a positive action

**Comment by jeffsnyder** [comment]
@mmarcon91 I think the proposal is great. 👍
