### ISSUE TITLE
Repeatedly increasing cart quantity can cause quantity to go back down

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#958]
## Problem
Looks like repeatedly clicking the + button in the mini cart faster than the api can respond can have unpredictable results, as if we optimistically increase the quantity, but then set it back to a lower number when an earlier api response finally comes through.

Slack Thread: https://ifixit.slack.com/archives/C0252FETV2S/p1667242703319649
Video: https://ifixit.slack.com/files/UEJ5DNB4K/F04984R7Z7T/screenshare_-_2022-10-31_11_56_44_am.mp4

## Do This
It might be best to cancel any in-progress increase-quantity request when beginning a new one, or at least only respect the most recent request's response.

**Comment by danielbeardsley** [comment]
I brought this up a bit ago when I ran across it, but we have quite a lot of code (300-400 lines) that tries to optimistically update quantities. There's a least one bug. The code is complex and has to effectively mimic how the ifixit.com API would respond after this modification. Is this complexity (bugs and maintenance) worth the benefit?

A slight delay and a loading state can help imply the change has been saved as opposed to being lost when the tab is closed.

CC @jeffsnyder

**Comment by sterlinghirsh** [comment]
I think it's worth the benefit. It feels very fast when you can add to the cart and it's snappy.

**Comment by dhmacs** [comment]
> Slack Thread: https://ifixit.slack.com/archives/C0252FETV2S/p1667242703319649
Video: https://ifixit.slack.com/files/UEJ5DNB4K/F04984R7Z7T/screenshare_-_2022-10-31_11_56_44_am.mp4

@sterlinghirsh I'm not able not access those links (I'm not part of iFixit slack). When you have attachments (like the video) or interesting bits of conversation, can you copy them over here?

**Comment by dhmacs** [comment]
@danielbeardsley I agree with you that the code can be polished so that's easier to understand, but let's not give up on optimistic update. It's less annoying when you don't have to see spinners for every little interaction that you do

**Comment by danielbeardsley** [comment]
> less annoying when you don't have to see spinners for every little interaction that you do

Heh, I'm saying that I don't mind a spinner or a delay when performing important interactions as it gives me peace of mind that my change actually was saved. There's a special kind of anxiety generated by a form that allows you change its inputs but gives no feedback about whether your changes have been persisted safely or only live as long as the open tab.

**Comment by dhmacs** [comment]
> Heh, I'm saying that I don't mind a spinner or a delay when performing important interactions as it gives me peace of mind that my change actually was saved. There's a special kind of anxiety generated by a form that allows you change its inputs but gives no feedback about whether your changes have been persisted safely or only live as long as the open tab.

I see what you're saying, but this might be only a concern of us devs that are aware of these details. I don't think the average user would be aware of this, he will only notice if it is prone to errors. Provided that this works reliably the customer will just get accustomed that adding to cart is fast

**Comment by dhmacs** [comment]
@sterlinghirsh what's the next action here? Can you share the video about the behaviour? If we aren't able to reproduce I'd say let's close this

**Comment by sterlinghirsh** [comment]
Thanks for following up @dhmacs . I checked with @c00perdanny who alerted me to this issue, and neither of us are seeing it anymore, so we'll close it.
