### ISSUE TITLE
Try connecting vercel logging to data dog

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#959]
We have Data Dog, and we'd like to be able to do some analysis of logs from our react-commerce deployment. Trying to read the logs in the vercel log viewer has been okay so far, but it's very limited. Let's see what we'd need to connect it to Data Dog for more persistence and longer-term analysis.

**Comment by danielbeardsley** [comment]
This was just a button click to add the data-dog integration!
![image.png](https://images.zenhubusercontent.com/54ff41794f7a08fbb7f24e2c/963b7786-7d3d-4907-91c6-992dc28566cc)
