### ISSUE TITLE
Product Page: Zoomed image aspect ratio

### ISSUE THREAD

**Issue by sterlinghirsh** [iFixit/react-commerce#966]
The long narrow zoomed image is kind of weird looking. Let's try to make it take up the rest of the page. The height is okay, but if we could widen it so it goes to the right edge of the screen (or close), it would be easier to see.

Example: https://ifixit.slack.com/files/UBF7UQNC9/F04924B1L10/image__11_.png

https://www.ifixit.com/products/ifixit-opening-picks-set-of-6

We also should make sure not to blow up the image past its intrinsic size when zooming. If original size of the image smaller than the gallery size, we should  not bother with the zoom at all.

**Comment by andyrrm** [comment]
![fullsize zoom](https://user-images.githubusercontent.com/53543020/199354697-734b57c3-7c3e-48e6-8c81-aaf876527c9b.jpg)
