### ISSUE TITLE
International Store Selector 

### ISSUE THREAD

**Issue by jeffsnyder** [iFixit/react-commerce#969]
Similar to International Buy Box Banner #930 but different. We also need to make sure that switching countries in the country selector takes you to the correct page.

Using the header selector in https://canada.ifixit.com/products/essential-electronics-toolkit takes you to https://www.ifixit.com/products/essential-electronics-toolkit.

![image](https://user-images.githubusercontent.com/7053450/199556845-734febfe-706d-4a99-805a-8f7ce4ae3328.png)

Using the footer selector in https://www.ifixit.com/products/essential-electronics-toolkit takes you to https://canada.ifixit.com/, _not_ the corresponding product page.

![image](https://user-images.githubusercontent.com/7053450/199556940-33505482-3aa5-49b5-8a13-3197535e199b.png)

CC @sterlinghirsh

**Comment by masonmcelvain** [comment]
Though not explicitly specified in this issue, I'd imagine this is only applicable to product pages, and not collection pages?

canada.ifixit.com/collections/parts links to www.ifixit.com/store, and www.ifixit.com/Parts links to canada.ifixit.com currently. Though it would be trivial to link /Tools and /Parts correctly, it would be pretty complex to map between different collections across stores.

**Comment by jeffsnyder** [comment]
We currently do not do anything special on Collections pages AFAIK, nor did we with the previous ProductList page. This only needs to be fixed on Product Detail Page. (But we will need to address this when we consolidate international stores onto the react framework.)
