### ISSUE TITLE
Product Page: set up `hreflang`s with other stores

### ISSUE THREAD

**Issue by davidrans** [iFixit/react-commerce#976]
Problem
---
We should add `hreflang`s on every product page, for every product that we sell in a non-US store. Now that we use the same URL structure/handle across all our stores this should be a bit easier. 

Notes
---
I think we need the hreflangs going both directions for Google to trust them, so we also need to add hreflangs pointing at the US store to the Shopify theme. Is there a significant amount of products we don't sell in the US store that we sell in other stores, or is it safe to just hreflang back to the US store on every non-US product page @jeffsnyder?

What's the best way to look up which other stores a product is sold in? Is there already an API we're using server-side that has this info? @sterlinghirsh 

Related: https://github.com/iFixit/react-commerce/issues/969

**Comment by ifixitmaxb** [comment]
YES. Should I close this? https://github.com/iFixit/ifixit/issues/43739

**Comment by sterlinghirsh** [comment]
Use a metafield with a list of storecodes where the product is available.

**Comment by sterlinghirsh** [comment]
Use a list of domains like `["canada.ifixit.com", "australia.ifixit.com"...]` and then we don't have to do any mapping on the client side. This can be a product metafield and we just won't worry about mapping variants to other variants.

**Comment by ifixitmaxb** [comment]
I don't think we should have a lot of 404ing hreflangs. If there is no equivalent in another store then I'd rather not hreflang to the non-existent equivalent.

**Comment by masonmcelvain** [comment]
We finished adding hreflangs to the product pages 🎉
